### ISSUE TITLE
Custom attributes to menu items

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#100]
Hi Edward, I have a problem too :) I must add attributes to some items. "data-toggle=, data-target=" etc.  Is it possible?
Ex:
&lt;ul class="nav navbar-nav navbar-right"&gt;
                  &lt;li&gt;&lt;a href="#"&gt;Contact&lt;/a&gt;&lt;/li&gt;
                  &lt;li&gt;&lt;a href="#" data-toggle="modal" data-target=".bs-example-modal-sm" title="Search Form"&gt; Search&lt;/a&gt;&lt;/li&gt;
                &lt;/ul&gt;

**Comment by cristovaov** [comment]
Please see my reply to your question in issue #99
That should get you on your way.
