### ISSUE TITLE
Adding NavBar elements (buttons, forms, etc...)

### ISSUE THREAD

**Issue by joviczarko** [wp-bootstrap/wp-bootstrap-navwalker#102]
What would be the propper method of adding other Botstrap Navbar elements when using this navwalker?

Since Walker is compiling whole block, it is pretty hard to hit a right place to add other components... I cannot clearly see line where is most appropriate to place code...

For example, I need to add log in button at the ent of the navbar.

``` html
<button type="button" class="btn btn-default navbar-btn">Sign in</button>
```

**Comment by cristovaov** [comment]
Hi, this can be done by removing the navigation container 
through the `wp_nav_menu` function. 
see: http://codex.wordpress.org/Function_Reference/wp_nav_menu#Removing_the_Navigation_Container

I made an example gist here:
https://gist.github.com/cristovaov/6306f833faa07608a1fe

**Comment by kylepierce** [comment]
I am having a problem how they are aligning. I need the nav to be on the right side, but the button to be in the furthest right. 

It would be cool if there was a way to add a btn class style to menu item in the appearance > menus.
