### ISSUE TITLE
Custom Post Types - Current-post-ancestor or Current-menu-parent ?

### ISSUE THREAD

**Issue by apsolut** [wp-bootstrap/wp-bootstrap-navwalker#107]
Planing to add Parent, Ancestor for CPT ?

examples:
http://wordpressclean.wordpress.com/2014/03/24/add-custom-post-type-archive-to-page-nav-menus-php/
http://stackoverflow.com/questions/21020695/custom-set-current-menu-item-class-for-specific-pages-in-wp

**Comment by SideQuestDIY** [comment]
These classes should be automatically applied as the walker doesn't strip
out standard WordPress classes.

**Comment by apsolut** [comment]
Kill me i think it was working with old version... i just started creating new site and no classes..
will check it again and get back with: what i did wrong..
ty :+1:

**Comment by jayarjo** [comment]
Would be great if it could add `active` class to parent menu items as well.

**Comment by apsolut** [comment]
My problem was WooCommerce, i have Parent with Children categories, so when im on Single Product, it add active to Parent (current-cat and cat-parent)   but not to that child category.. :+1:

**Comment by SideQuestDIY** [comment]
The issues with this is the way WooCommerce assigns categories. Because you can have more then one taxonomy assigned to a product and typically you do, WordPress doesn't know how to handle that.

**Comment by ghost** [comment]
This should be re-opened as there is no native support to show custom post types single, and add the parent classes to the archive navigation menu item.

**Comment by ghost** [comment]
> These classes should be automatically applied as the walker doesn't strip
> out standard WordPress classes.
> On Apr 29, 2014 11:06 AM, "Aleksandar Perisic" [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > Planing to add Parent, Ancestor for CPT ?
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/[/issues/107](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/107)
> > .

No, it doesn't.

**Comment by pattonwebz** [comment]
@leecollings I'm happy to look at fixing this in an upcoming version of the walker but this specific issue thread is like 5 or 6 years old and about code which is really quite different to the current walker.

I would rather have a fresh issue opened about this if it is still a problem in the v4 walker.

**Comment by ghost** [comment]
Fair enough, I'll try and gather more info/evidence, thanks for your reply.

**Comment by pattonwebz** [comment]
No need for father research, just open an issue with what you already know:)

I expect that it is still the case that this is handled the same as when this issue was opened - but afresh issue for tracking it would be good :)
