### ISSUE TITLE
WPCS

### ISSUE THREAD

**Issue by szepeviktor** [wp-bootstrap/wp-bootstrap-navwalker#11]
Check coding style
https://github.com/codeclimate/codeclimate-phpcodesniffer/issues/15#issuecomment-225018852

**Comment by bhubbard** [comment]
@szepeviktor The codeclimate config is already using WordPress, however we just removed the WordPress-VIP checks as it didn't really apply for this project. 

```
    config:
      standard: "WordPress-Core,WordPress-Docs,WordPress-Extra"
```

**Comment by szepeviktor** [comment]
Really.
https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/master/.codeclimate.yml#L16
