### ISSUE TITLE
child theme support

### ISSUE THREAD

**Issue by strebel** [wp-bootstrap/wp-bootstrap-navwalker#11]
Did something similar, then tried with your class as well.

Seems if you define the class in a parent themes functions.php, then enable a child theme of that parent with nothing fancy except the child style.css.  All the nav items are empty.

Curious if you know why?

**Comment by SideQuestDIY** [comment]
I apologize for my tardiness, I was out sick for the past few days. I have actually never tested the script with a child theme, I will do some digging.

**Comment by strebel** [comment]
It was actually user error on my end. Script works fine, great work.

## 

Joshua Strebel
Founder @ Page.ly

twitter: @strebel

**Comment by SideQuestDIY** [comment]
Perfect! Thanks for following up and the feedback!

**Comment by robhadfield** [comment]
@strebel - what was your error because I have empty links to?

Same situation, just child CSS.

Cheers
Rob

**Comment by strebel** [comment]
Have to enable the menu again when switch to child theme. :) rookie mistake

#Typed with thumbs from an iPhone; Excuse the brevity and typos#

Joshua Strebel 
Founder @ Page.ly
t: @strebel

**Comment by robhadfield** [comment]
haha! Oh yeah... I knew that of course.

Rookie or not, that's easy to overlook. (I'm sticking with that excuse)

Cheers Joshua :)
