### ISSUE TITLE
Drop Down not working

### ISSUE THREAD

**Issue by PixemWeb** [wp-bootstrap/wp-bootstrap-navwalker#111]
Hello,

I am currently attempting to implement this resource for a WordPress theme I am working on. I am developing it on my local computer. 

For some reason I can't get the drop down to work. I followed the instructions and put the necessary code into my functions.php file and the header.php and I put the nav walker into the root of the theme folder. 

Not sure why it's not working.

Am I missing something?

**Comment by pattonwebz** [comment]
Bootstrap dropdowns require a click to open them so that they are mobile compatable. I now it seems silly to ask but did you try clicking to open? I've had clients contact me saying the same thing because they had only hovered to check - never realised mobile dropdowns required that click :p

**Comment by PixemWeb** [comment]
lol, Yeah. I did click the carat and nothing happened. Not quite sure what the issue is. I've tried to trouble shoot it but no success. Am I supposed to change anything when adding the code to my theme? Should I be changing any of the CSS in the Style sheet? Thanks.

**Comment by PixemWeb** [comment]
What I did to date was place the nav walker file in the root of my Theme, placed the require code in the functions.php, registered the menu in functions.php and added the code to the header.php.

**Comment by searsandrew** [comment]
Does the rest of the menu work/render correctly? I had a similar problem once, and it was because I was not using the container in the Walker, and I was missing one of the classes needed.

**Comment by pattonwebz** [comment]
What your doing should be enough to get it working so long as your also including bootstrap CSS and js (I assume you are).

Have you looked at the markup on the page to see if it is including the drop down and just not displaying it? You can use firebug for FF or the inspector on chrome to see if it's there on the page.

Also just wondering but the code you have in header.php doesn't set the depth to 0 does it? Should have asked that first lol

I'm not at a computer just now so i can't test things out try recreate what your seeing but I'll be at my laptop in about an hour so if you're still having problems I'll be able to help out better then.

**Comment by PixemWeb** [comment]
Yeah, the menu works but the drop down doesn't. NOTE: When I resize the viewport in my browser to what would be a mobile size the hamburger menu works but is a little delayed. Not sure if that is how it's supposed to be. 

What do you mean not using the container in the walker? and what class was needed? I might have the same problem?  Thanks.

**Comment by PixemWeb** [comment]
The depth is set to 2. I literally just copied the code over verbatim. Yes, I have all the bootstrap files uploaded properly as far as I can tell. All the other bootstrap features seem to work fine. Let me check the inspector for the other item you mentioned.  Thanks

**Comment by cristovaov** [comment]
Have you included your Bootstrap javascript properly in your functions.php file? Please check previously closed issues related to your problem. If you still have problems we'll look at your code files together.

**Comment by searsandrew** [comment]
I wanted to use the Bootstrap navbar-right div so I removed the 'container' and 'container_class' from the wp_nav_menu array. This allowed me to use a WordPress menu for the main nav, and have a login/loggedin button right aligned.
But it sounds like that's not your issue.

**Comment by searsandrew** [comment]
Another thought, are you using a customized Bootstrap? If so, did you include 'navbar' and 'dropdowns' in your package?

**Comment by PixemWeb** [comment]
I downloaded the full bootstrap package.

**Comment by PixemWeb** [comment]
This is the code in my functions file. I believe it's correct. Everything else on the site works.

function theme_styles() {
    wp_enqueue_style( 'bootstrap_css', get_template_directory_uri() . '/css/bootstrap.min.css');
    wp_enqueue_style( 'main_css', get_template_directory_uri() . '/style.css');
    }

```
add_action('wp_enqueue_scripts', 'theme_styles');
```

function theme_js() {
    global $wp_scripts;

```
wp_register_script( 'html5_shiv', 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', '', '', false);
wp_register_script( 'respond_js', 'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js', '', '', false);

$wp_scripts->add_data('html5_shiv', 'conditional', 'lt IE 9');
$wp_scripts->add_data('respond_js', 'conditional', 'lt IE 9');

wp_enqueue_script('bootstrap_js', get_template_directory_uri() . '/js/bootstrap.min.js', array('jquery'), '', true );
wp_enqueue_script('theme_js', get_template_directory_uri() . '/js/theme.js', array('jquery', 'bootstrap_js'), '', true );
}

add_action('wp_enqueue_scripts', 'theme_js');
```

add_theme_support('menus');
add_theme_support('post-thumbnails');

function register_theme_menus() {
    // Register Custom Navigation Walker
    require_once('wp_bootstrap_navwalker.php');

```
register_nav_menus( array(
'primary' => __( 'Primary Menu', 'bootstrap-to-wp' ),
```

) );
    }

add_action('init', 'register_theme_menus');

**Comment by searsandrew** [comment]
It doesn't sound like the problem is in your functions file, to me, since the navwalker loads. I think its in either your nav file or in the js/css (which look like they should be loading okay)

**Comment by PixemWeb** [comment]
Interesting. Is there any css I should be including that is unique for this?

**Comment by cristovaov** [comment]
Okay guys, my notification ringtone is driving me nuts. Please take a moment to relax. Also:

It seems that my previous comment offering to help has been overlooked, not nice.

@citidm Your function file is not well written: ~~a semicolon is missing~~, 'add_theme_support(menus)' is not a valid function, ... I am preparing a gist for you that should solve your problem, stand by.
Also as a beginner I urge you to take time to read the WordPress Codex on Theme Development. 

> and maybe the GitHub docs about how to include code in comments ;)

**Comment by PixemWeb** [comment]
Thanks @cristovaov Sorry about that. I appreciate your help.

**Comment by cristovaov** [comment]
No worries - I hope I didn't come to harsh, I mean no disrespect.

Here's the gist. I provided a small comment on what to do at the top of each file
and used the default markup for the menu from the instructions page.
https://gist.github.com/cristovaov/ab0ae1a1c8ef250316f4

Let me know if it worked or if more help is needed~

**Comment by PixemWeb** [comment]
Thanks @cristovaov , for some reason it's still not working. SMH, I'm sure I'm missing something and it's probably so simple and when I find it I will be like DUH.

**Comment by cristovaov** [comment]
can you upload your whole theme to a new repository or make a gist with your functions.php file and header.php file to have a proper look?

**Comment by PixemWeb** [comment]
@cristovaov after hours of trying to figure it out I finely had that DUH moment. Plugin conflict. I previously installed this plugin http://wordpress.org/plugins/bootstrap-shortcodes/ which has great reviews. I just deleted it and the drop down finally worked.  I also tried to upload a new repository by using the mac.github client but since I've never used it before I figured I'd learn it another day. Thanks for your help and patience.

**Comment by cristovaov** [comment]
It's okay, learn anything on your own time -no rush > 
in fact I learned something too: I completely overlooked the 'plugin conflict' possibility. 
From a quick look, I think the conflict might come because the plugin loads the Bootstrap js too.
They're on GitHub too and just saw someone with the same problem as you.

If you need a starting point/reference for Bootstrap + WordPress maybe you'd like to check this link : http://www.kungfunguyen.com/make-custom-wordpress-theme-bootstrap-3-underscores/ 

I'm glad to help when I can, ping if anything. I'll now close this issue - happy learning!

**Comment by PixemWeb** [comment]
Thanks @cristovaov .

**Comment by cristovaov** [comment]
@citidm If you would still like to use the Bootstrap shortcodes, there are actually settings for the JS and CSS. Check https://github.com/TheWebShop/bootstrap-shortcodes/issues/35 -cheers

**Comment by PixemWeb** [comment]
@cristovaov thanks, I appreciate the guidance.

**Comment by rerraw** [comment]
@citidm  before some days i updated my wp from 3.9 to 4.1 and occure the same problem for me and i read this post and deleted the bootstrap sortcode plugins then solved my problem thank you for your comment

**Comment by dforeigner** [comment]
For future reference to anyone looking for help, Wp_Bootstrap_Navwalker is also incompatible with the plugin Menu Image.

**Comment by pattonwebz** [comment]
@dforeigner sounds like we are missing a filter it expects. Open up an issue with some details about how that plugin works and I'll see if it would be possible for me to work in support for it today :)

**Comment by klevinkona** [comment]
Looks like the same problem, the dropdown menu does display only in mobile version
https://pavaresia1.klevinkona.com/
