### ISSUE TITLE
Can I set 'depth' => 3?

### ISSUE THREAD

**Issue by maheshwaghmare** [wp-bootstrap/wp-bootstrap-navwalker#115]
I want to show up-to depth 3 of sub menus. I use 'depth' => 3, but it cant works. Any suggestions.

**Comment by SideQuestDIY** [comment]
Bootstrap 3 does not natively support more then two levels, so WP Bootstrap
Navwalker is purposely limited to two levels. If you would like to have
three levels you will have to modify the walker and Bootstrap's CSS.

Such modifications are outside of the scope of support with this script.

**Comment by maheshwaghmare** [comment]
Thanks...!

**Comment by wesweat** [comment]
@maheshwaghmare  did you manage a workable solution and if so do you might sharing it?

**Comment by LouisMilotte** [comment]
@wesweat If there is a solution it must be done modifying the behavior of Bootstrap and this nav-walker. At current versions Bootstrap only supports 2 deep drop down.

**Comment by ghost** [comment]
you are not supposed to have more than two level deep drop down menu, so i suggest you design your site around two level deep dropdown menu

**Comment by dannio** [comment]
just add into ur css:
 ul.dropdown-menu li > ul.dropdown-menu{
  left: 100%;
  top: 0;
} 

and
 ul.dropdown-menu li:hover > ul.dropdown-menu,  ul.dropdown-menu li:focus > ul.dropdown-menu{
  display: block
}

**Comment by pattonwebz** [comment]
@dannio could you elaborate more on what the CSS does for anyone who needs to know? Where does the 1st and 2nd dropdowns appear?

I've used similar style rules before to make this happen as well but doing it this way forces the menu to work on `:hover`. Touch input users cannot hover. 

The prefered way to make this happen would be to retain the parent's ability to be a tappable target and as such would need custom JavaScript to make it happen (as Bootstrap core doesn't support multi-level dropdowns at all).

**Comment by dannio** [comment]
ah my solution only works on non touch screens unfortunately. There's a script somewhere that adds and removes the `open` class from the main dropdown once you click off it. you'll have to find that and change it so it doesn't remove the `open` class when you click on a child item.

I ended up having to display a custom made mobile menu instead in the end as the client needed it done quickly and i didn't have time to shift through the code looking for it.

**Comment by msatpal** [comment]
@dannio 
Thanks alot, your two line css code saved lot of time and energy. 
It really worked nicely.
Thanks again.

Manish

**Comment by AssessmentDay** [comment]
This Blog post realy helped me out, [blog post](https://www.omnicoda.com/blog/wordpress-development/beginners-guide-wordpress-menus-bootstrap-navigation)
