### ISSUE TITLE
I'm having issue with Dropdown not working.

### ISSUE THREAD

**Issue by markmorris** [wp-bootstrap/wp-bootstrap-navwalker#117]
Hi, I'm having problems getting drop down menus to work, I'm not sure were to look any help would be appreciated.

I have everything setup correctly and using all default settings.

**Comment by ashiqulislam** [comment]
I think you must check again the code follow the instruction. It will be work.

**Comment by LouisMilotte** [comment]
It appears that this post is plenty old. Not even sure if this is an issue any more.
