### ISSUE TITLE
Multi-level Dropdowns not working

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#119]
Multi-level dropdowns are currently only working up to the first level.

Are there any plans to fix this? 3 Levels would be great...

Would be highly appreciated. Thanks.

**Comment by SideQuestDIY** [comment]
The walker is intentionally locked to one level of dropdown as that is all
Bootstrap 3+ supports.

**Comment by ghost** [comment]
Thanks for your quick response. Just noticed that submenu levels are not supported any longer in Bootstrap 3. Absolutely not understandable why they took out this feature:

http://stackoverflow.com/questions/18023493/bootstrap-3-dropdown-sub-menu-missing

But it would be a nice feature to have... :)

**Comment by SideQuestDIY** [comment]
They were removed because its a mobile first framework and multi level
dropdowns create terrible UX on mobile.
