### ISSUE TITLE
Extend the depth of the dropdowns

### ISSUE THREAD

**Issue by dtuts** [wp-bootstrap/wp-bootstrap-navwalker#122]
Hi, and first on all thank you so much for this great script!

It would be better if you could extend the depth of the dropdown level.

Thanks again.

Regards.

**Comment by ashiqulislam** [comment]
Ya I feel that too. That would be great.

**Comment by mindctrl** [comment]
The [readme](https://github.com/twittem/wp-bootstrap-navwalker/blob/master/README.md) says:

"The most noticeable functionality change in Bootstrap 3.0.0+ is that it only supports a single dropdown level. This script is intended to implement the Bootstrap 3.0 menu structure without adding additional features, so **additional dropdown levels will not be supported**."

This was brought up in [#119](https://github.com/twittem/wp-bootstrap-navwalker/issues/119) too.

**Comment by ashiqulislam** [comment]
Thanks for support.
