### ISSUE TITLE
Site title link now working in navar

### ISSUE THREAD

**Issue by abhikhatri** [wp-bootstrap/wp-bootstrap-navwalker#123]
I used this plugin on my bootstrap custom theme but the main title link not working. 
Can you please help me to fix it ?

when i click on it, it just take me to # 

![capture](https://cloud.githubusercontent.com/assets/6468965/3594948/778d806a-0caa-11e4-9db8-e057e233466a.PNG)

is there any way to fix it or link it dynamically to site url

**Comment by LouisMilotte** [comment]
This is not an issue of this library. Please use WordPress functionality to add dynamic links. 
`<a class="navbar-brand" href="<?php bloginfo('template_directory');?>/link/to/content">Brand</a>`

**Comment by abhikhatri** [comment]
Thanks buddy!
I am totally a beginner in this field. Your tool helps me alot.
Can you suggest me a book to learn these functionality. 
Thanks again sir.

**Comment by LouisMilotte** [comment]
Wordpress Functionality:
http://codex.wordpress.org/Theme_Development

Bootstrap Functionality:
http://www.getbootstrap.com

If you're needing information beyond this; google.

@twittem you can mark this as closed.
