### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by prionkor** [wp-bootstrap/wp-bootstrap-navwalker#125]
Can you add a composer.json file so I can use the repo via composer?

**Comment by pattonwebz** [comment]
Would a simple file that matches the example file listed [here](https://getcomposer.org/doc/articles/custom-installers.md#composer-json) be sufficient?

**Comment by prionkor** [comment]
Yes, that should do it. I've added on on my forked version. https://github.com/prionkor/wp-bootstrap-navwalker/blob/master/composer.json

I am very new to composer so we need someone confirm if that will work.

**Comment by prionkor** [comment]
I've created a pull request. Lets discuss it there. Closing this ticket.
