### ISSUE TITLE
提示 Add a menu

### ISSUE THREAD

**Issue by rebron1900** [wp-bootstrap/wp-bootstrap-navwalker#126]
默认有两个菜单，但是还是提示add a menu 我该怎么做？

**Comment by LouisMilotte** [comment]
I had to put this into google translator; I hope that you can read and write English.
"By default there are two menus, but still prompted to add a menu how can I do?".

When you first run this plugin with wordpress without having configured a menu with the set attributes; you will be provided a link in the navigation menu. Follow this link OR go to your appearences>menu options area and create a menu and assign it to the walker's identifier.

**Comment by raxan** [comment]
@LouisMilotte 

how to assign menu to the walkers identifier?

I have already a menu, how to display this?

thanks

**Comment by raxan** [comment]
fixed.
