### ISSUE TITLE
How to have parrent as a link

### ISSUE THREAD

**Issue by alexandar87** [wp-bootstrap/wp-bootstrap-navwalker#127]
Hi

i want to have my parent a to work as a link, currently i cant click on it even if there is href attribute in link.

**Comment by mindctrl** [comment]
You can't have the parent item work as a link because Bootstrap activates the dropdown on click instead of hover.

**Comment by alexandar87** [comment]
Actually you can, just pass it class "disabled" and it will work as link.

I found that here http://stackoverflow.com/questions/12630188/allow-click-on-twitter-bootstrap-dropdown-toggle-link

so i just did 
`$( ".dropdown-toggle" ).addClass( "disabled" );`

**Comment by LouisMilotte** [comment]
While you can put the parent as a link; it defeats the purpose of the framework being used by mobile devices.

Also, if you feel that you have answered your own issue; please remember to close it.
