### ISSUE TITLE
This plugin can not pass the test from wptest.io .

### ISSUE THREAD

**Issue by parahelox** [wp-bootstrap/wp-bootstrap-navwalker#13]
Please try this test file:
http://wptest.io/

The test from above site would pass when I use default wp_nav_menu.

**Comment by SideQuestDIY** [comment]
Hey parahelox,

Can you provide more information on how the script "can not pass"?

I use wptest.io datafiles to test my own themes and have never had and issue with wp-bootstrap-navwalker.
