### ISSUE TITLE
How to implement multilevel nav menu?

### ISSUE THREAD

**Issue by roniwahyu** [wp-bootstrap/wp-bootstrap-navwalker#135]
How to implement multilevel bootstrap 3.0 nav menu?

**Comment by LouisMilotte** [comment]
If you mean the layers as permitted by bootstrap, follow the wordpress documentation for adding child elements to a menu.

**Comment by SideQuestDIY** [comment]
Please search the other issues and consult the README before opening an
issue. This has been addressed numerous times.
