### ISSUE TITLE
Add custom menü item over shortcode

### ISSUE THREAD

**Issue by Stefan39** [wp-bootstrap/wp-bootstrap-navwalker#138]
Hi,

how i can put the WPML Language Switcher into the menu as menu item? It's possible to use an own shortcode like dividers?

**Comment by SideQuestDIY** [comment]
Hey @Stefan39 sorry for the late reply. 

I would add the language switcher manually. This is possible in the marker of the walker by modifying you wp_nav_menu declaration to exclude the containers, or through a menu filter in your functions.php file.

**Comment by pattonwebz** [comment]
@Stefan I realize it's been a long time since you opened this issue but are you still needing to get this done? I actually do have a solution that can add an additional menu-item to the end of the menu (but it's outside the scope of the navwalker) that I could help you get up and running.
