### ISSUE TITLE
dropdown only working on index/landing page

### ISSUE THREAD

**Issue by sOm2y** [wp-bootstrap/wp-bootstrap-navwalker#144]
so in the index.php, landing page its working perfectly, once u click any nav link and jump to page.php or single.php, dropdown doesn't working anymore. and when you click it, it only add a '#' sign in the end of url. I use all standard setting crab from document.

**Comment by sOm2y** [comment]
it's wordpress problem. fixed it.

**Comment by Marianour10** [comment]
Hey dude! How did you fix this? im loosing it

**Comment by pattonwebz** [comment]
@Marianour10 if you open up a fresh issue detailing your problem I'll take a look.
