### ISSUE TITLE
Mobile menue not opening

### ISSUE THREAD

**Issue by tawanda** [wp-bootstrap/wp-bootstrap-navwalker#146]
did as specified, but the mobile menu does not open when window is resized

**Comment by kevinruscoe** [comment]
Are the buttons ID and nav hooked up? I had an similar issue issue but the issue with my IDs. Care to post your outputted HTML?

**Comment by tawanda** [comment]
Thanks for responding here is the url of the site im designing

http://siegecommunications.com/clarko/

the html generated is

&lt;code>
&lt;button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      &lt;span class="sr-only">Toggle navigation</span>
        &lt;span class="icon-bar"></span>
        &lt;span class="icon-bar"></span>
       &lt;span class="icon-bar"></span>
      &lt;/button>
</code>

where do i hook up the ID's

**Comment by SideQuestDIY** [comment]
This issue is usually caused by a JavaScript error. Either your loading the
bootstrap JS twice (the bootstrap shortcodes plugin does this) or the JS is
not loading correctly.

**Comment by tawanda** [comment]
i have checked and bootsrap is only loaded once, i think the problem is with the nav bar code itself please see here

<code>
&lt; nav class="navbar navbar-default" role="navigation">
  &lt; div class="container-fluid">
    &lt; !-- Brand and toggle get grouped for better mobile display -->
   &lt; div class="navbar-header">
      &lt; button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        &lt; span class="sr-only">Toggle navigation</span>
        &lt; span class="icon-bar"></span>
       &lt; span class="icon-bar"></span>
       &lt; span class="icon-bar"></span>
      &lt; /button>
      &lt; a class="navbar-brand" href="<?php echo home_url(); ?>">
                &lt; ?php bloginfo('name'); ?>
            &lt; /a>
    &lt; /div>

```
    &lt; ?php
        wp_nav_menu( array(
            'menu'              => 'primary',
            'theme_location'    => 'primary',
            'depth'             => 2,
            'container'         => 'div',
            'container_class'   => 'collapse navbar-collapse',
    'container_id'      => 'bs-example-navbar-collapse-1',
            'menu_class'        => 'nav navbar-nav',
            'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
            'walker'            => new wp_bootstrap_navwalker())
        );
    ?>
&lt; /div>
```

&lt; /nav>
</code>

**Comment by mindctrl** [comment]
You have a 404 error on `http://siegecommunications.com/clarko/bootstrap/js/bootstrap.min.js`.

**Comment by tawanda** [comment]
mindctrl you are legend. there is absolutely no way i would have figured this out on my own. its working 100% now. 

Thank you all on this thread for taking the time to help out
