### ISSUE TITLE
navigate to position

### ISSUE THREAD

**Issue by Rock28** [wp-bootstrap/wp-bootstrap-navwalker#147]
Hi guys, im new and tryed to find a solution that a page is not only linked to start position it should also set a special position.

I want to add something like:
onclick="scrollWin()

<script>
function scrollWin()
{
window.scrollTo(500,0);
}
</script>

but i dont know where i have to add the code, and didnt found another solution
... searched a long time :(

**Comment by mindctrl** [comment]
You could use the "Links" feature in the menu editor and create it manually to link to the part of the page you want to scroll to. For example, the URL field would be `http://yoursite/page#jump`.
