### ISSUE TITLE
Hover dropdown menu

### ISSUE THREAD

**Issue by munkhbayaryo** [wp-bootstrap/wp-bootstrap-navwalker#150]
Hi
How to dropdown submenu when mouse over  with bootstrap 3?

**Comment by pattonwebz** [comment]
Hey munkhbayaryo,

Bootstrap 3 doesn't support hover menus (opening on `:hover` gives an extremely bad UI for touch devices).

If your willing to dig in a little bit to how it works you can make them work on `:hover` with some CSS adjustments. 

As this isn't supported by core BS3 I'm gonna close this issue but feel free to come back and reopen it if you wanted some help to figure out the CSS changes needed.

**Comment by mindctrl** [comment]
There's also this. https://github.com/CWSpear/bootstrap-hover-dropdown

**Comment by munkhbayaryo** [comment]
Thank you mindctrl.
