### ISSUE TITLE
try to add custom menu item though functions.php  - ends up on all the menus

### ISSUE THREAD

**Issue by nostahl** [wp-bootstrap/wp-bootstrap-navwalker#153]
I have implemented this walker so I can use bootstrap styled menus but I just cant figure out whats going on  im trying to add a menu item to specific menu  but it shows on all the menu's ...

wondering if this is possible cause of the walker?

**Comment by pattonwebz** [comment]
Hey nostahl,

Could you clarify what you mean by "add custom menu item though functions.php"? Are you saying that you were trying to add custom items to a menu and doing it directly in the functions.php file?

The walker is intended to be used with the default WordPress menu system (_Appearance >> Menus_ in the dashboard) so you would create your menu there and then set it as the active menu for the location that you want the Bootstrap menu to appear using the tick boxes below the menu.

![menus pattonwebz wordpress](https://cloud.githubusercontent.com/assets/3902039/5643087/9d60d334-964b-11e4-9652-e52f53516d4c.png)

**Comment by nostahl** [comment]
no I mean 

if i try to do something like this 

add_filter( 'wp_nav_menu_items', 'wti_loginout_menu_link', 10, 2 );

function wti_loginout_menu_link( $items, $args ) {
   if ($args->theme_location == 'subnav') {
      if (is_user_logged_in()) {
         $items .= '<li class="right"><a href="'. wp_logout_url() .'">Log Out</a></li>';
      } else {
         $items .= '<li class="right"><a href="'. wp_login_url(get_permalink()) .'">Log In</a></li>';
      }
   }
   return $items;
}

even though I specify the menu for it to show on   it shows on none of the menus if I specify the specific menu   if I change it to != then it shows on all of them so the code is functionally able to add stuff to the nav bars just not in the expected behavior.

**Comment by pattonwebz** [comment]
Hey @nostahl 

I see what you mean now. I use code almost exactly the same as yours (with a different theme_location that matches the one in my theme) and it works like it should. 

I know this sounds silly but are you sure the `theme_location` is called 'subnav'? Here's the function I used to make it work my end:

``` php
add_filter('wp_nav_menu_items','add_to_second_menu', 10, 2);
function add_to_second_menu( $items, $args ) {
    if( $args->theme_location == 'secondary')  {
        $items .= '<li class="menu-item menu-item-custom">' . $loginlink . '</li>';
    }
    return $items;
}
```
