### ISSUE TITLE
Classes variable not reassigned with result of nav_menu_css_class filter

### ISSUE THREAD

**Issue by lf-jeremy** [wp-bootstrap/wp-bootstrap-navwalker#156]
The `$classes` variable is not reassigned to the result of the filter `nav_menu_css_class`.

As a result, logic that relies on the state of the `$classes` array cannot be manipulated and relies on potentially stale state.

For instance, the `.active` css class is added based on the presence of `.current-menu-item` in the class list.

Someone with a menu using named anchor fragments in the uri (e.g., `#about`) may need to remove the `.active` class by removing `.current-menu-item` using the `nav_menu_css_class` filter. In this use case it would be undesirable to have multiple `.active` menu items.

**Comment by rerraw** [comment]
i update my wordpress theme to version 4.1 but the wp_bootstrap_navwalker not work and not show me the dropdwon menus also i removed the display_element function and i changed the $args->has_children to $this->has_children and also not work with me. is have the perfect solution until work with wp 4.0+?

**Comment by pattonwebz** [comment]
@lf-jeremy I see what your saying. We should reassign updated values back to make sure if something else needs fresh data after the walker is processed it can be accurately filtered.

Personally I've never come across this problem before so I don't really have a place I can test this readily available. Are you able to come up with a test unit or make a pull request with a potential solution that I could look at and merge?

**Comment by lf-jeremy** [comment]
@pattonwebz The case I described is resolved by reassigning the classes variable to the filter output and then substituting the existing call to the filter with the reassigned classes variable. I can throw together a pull request at some point with these two lines of changes. I believe the active css class is the only part of the walker really affected but having fresh data after filtering will remove any unexpected behavior where someone may try preventing a menu item from being considered active at time of page render.

**Comment by lf-jeremy** [comment]
Code to test before/after the patch: Will remove `.active` class from current menu items if their url contains a url fragment e.g. `#about` -- uses closures (PHP 5.3+)

```
add_filter( 'nav_menu_css_class', function($classes, $item, $args) {
  // Item is current page
  if ( in_array( 'current-menu-item', $classes ) ) {
    // Link has anchor -- quick and dirty for this example, no domain comparison
    $anchor_pos = strpos( $item->url, '#' );
    if ( $anchor_pos !== false ) {
      // Remove current menu item class
      $unset_index = array_search( 'current-menu-item', $classes );
      unset($classes[$unset_index]);
      $classes = array_values($classes);
    }
  }
  return $classes;
}, 10, 3);
```

**Comment by bhubbard** [comment]
@lf-jeremy We pushed out an update 2.0.5, can you please test with this new version and see if there is still an issue.
