### ISSUE TITLE
Wp_Bootstrap_Navwalker Don"t Work With Wordpress 4.0

### ISSUE THREAD

**Issue by rerraw** [wp-bootstrap/wp-bootstrap-navwalker#157]
some day ago i update my theme from 3.9 to 4.1 then i saw my dropdown menu not work and dont show me any sub menu 
I read this comment below
https://github.com/twittem/wp-bootstrap-navwalker/issues/140

i deleted the display_element function and i replaced $args_children to the $this_children.
but my problem not solved.

if anyone can manage for me the clear wp_bootstrap_navwalker.php for me until work with my Wordpress 4.1 Without any problem?

**Comment by pattonwebz** [comment]
The walker works for me without problem on WP 4.1 (and without deleting the `display_element` function). Can you post the code you're using to add it to your theme? It'll look something a little like this:

``` php
wp_nav_menu( array(
   'menu'       => 'main_menu',
   'depth'      => 2,
   'container'  => false,
    'menu_class' => 'nav',
    'fallback_cb' => 'wp_page_menu',
    //Process nav menu using our custom nav walker
    'walker' => new wp_bootstrap_navwalker())
);
```

**Comment by rerraw** [comment]
@pattonwebz  thank you for your help and reply the wp_bootstrap_navwalker.php it is work without any problem with version 4.0 and 4.1.
but any one use this plugin 
https://wordpress.org/plugins/bootstrap-shortcodes
cause the damage the dropdwon menu for wp_bootstrap_navwalker for version 4.0 
i deleted this plugin then solved my problem 
read this comment also that person occured the same problem for his.
https://github.com/twittem/wp-bootstrap-navwalker/issues/111
