### ISSUE TITLE
Images not found in the Readme file

### ISSUE THREAD

**Issue by kossa** [wp-bootstrap/wp-bootstrap-navwalker#159]
Please fix the images in the readme file :
![image](https://cloud.githubusercontent.com/assets/1175584/5902815/fe02aa00-a57d-11e4-9c10-b34429749625.png)

**Comment by pattonwebz** [comment]
Will fix this today, not sure what happened to the images :confused: 

Thanks for pointing this out! :smile:

**Comment by kossa** [comment]
You're welcome :)
I have a project, PSD to Wordpress, and I should use mega menu so I want to use your repo :)

**Comment by SideQuestDIY** [comment]
The images were uploaded to and hosted by @github and they seem to have removed them.

**Comment by bhubbard** [comment]
References for broken images have been removed. We can look into adding new images in the near future if needed.
