### ISSUE TITLE
active not yet working for all items

### ISSUE THREAD

**Issue by duikb00t** [wp-bootstrap/wp-bootstrap-navwalker#161]
Hello,

I started a new project with you wp-bootstrap-navwalker class, thank you. For all the menu items is it working except 1.

I am using the following setup:

`````` <?php
    wp_nav_menu(array(
        'menu'              => 'primary',
        'theme_location'    => 'primary',
        'depth'             => 2,
        'container'         => 'div',
        'container_class'   => 'collapse navbar-collapse navbar-ex1-collapse',
        'menu_class'        => 'nav navbar-nav',
        'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
        'walker'            => new wp_bootstrap_navwalker())
    );
    ?>```


register_nav_menus(
  array(    'primary' => __( 'Primary menu', 'MYTHEMENAMEISHERE' ), )
);
``````

I also have a post type with the same name, but I guess that can't be the issue. I've tested this by creating an other menu item name for that.

All classes getting loaded perfectly except the '.active' class.

Suggestions? Thanks.

**Comment by LouisMilotte** [comment]
I'm not sure if this is relevant or not, but why did you not include the container_id key, which value should be the id of the collapsing container.
