### ISSUE TITLE
Cannot get dropdown to work

### ISSUE THREAD

**Issue by melmulcahy32** [wp-bootstrap/wp-bootstrap-navwalker#162]
Hi there, I can't seem to get the dropdown menu to work with my custom theme. I have downloaded the bootstrap 3.3.2 (the recent one). There are no issues in the JavaScript console. However, when I resize the window on my laptop, the nav collapses, but it is not collapsing on mobile. I've been scouring the boards and have yet to find a solution that works. I've used this on other themes but for some reason it is not working on this one.

I tried disabling the Carousel Plugin, but the problem still exists. Any help would be appreciated. Otherwise, I'm going to scrap the idea of a dropdown.

Active Plugins:
CPT Bootstrap Carousel
Contact 7 Form

Wordpress Version: Current

Website: www.melissamulcahy.com
It's my personal website that I'm currently migrating from HTML documents into a custom Wordpress theme. There's still some work that needs to be done... The "About" link has two links that should show in a dropdown beneath it ("Resume", "Skills").

Header File:
<?php wp_nav_menu( array(
              'menu' => 'main',
              'depth' => 2,
              'container' => false,
              'menu_class' => 'nav navbar-nav navbar-right',
              'walker' => new wp_bootstrap_navwalker())
            );
            ?>

Functions.php:
function wpbootstrap_scripts_with_jquery()
{
    // Register the script like this for a theme:
    wp_enqueue_script( 'bootstrap-jquery', get_stylesheet_directory_uri() . '/bootstrap/js/bootstrap.js', array( 'jquery' ) );
    wp_enqueue_script( 'custom-script', get_stylesheet_directory_uri() . '/bootstrap/js/bootstrap.min.js' );
}

add_action( 'wp_enqueue_scripts', 'wpbootstrap_scripts_with_jquery' );
register_nav_menus();
 if ( function_exists( 'register_nav_menus' ) ) {
        register_nav_menus(
            array(
                'main_menu' => 'Main Menu', 'Mulcahy Custom'
            )
        );
    }

require_once('wp_bootstrap_navwalker.php');

**Comment by NedimMuhamedagic** [comment]
Hello,

I think it's necessary to have a menu_id in the wp_nav_menu array from the header file. If you criss check with the html you will notice the missing ID in the menu.

**Comment by melmulcahy32** [comment]
Does the menu_id have to be anything specific? I added in a menu_id and nothing seemed to change....

**Comment by NedimMuhamedagic** [comment]
The default is bs-example-navbar-collapse-1 but it should be the same as
data-target attribute on the button tag few lines above.

**Comment by NedimMuhamedagic** [comment]
If that doesn't work try putting the container_id value
"bs-example-navbar-collapse-1" :)

**Comment by melmulcahy32** [comment]
I tried both ways and nothing happened :(

**Comment by mindctrl** [comment]
You have 2 copies of the Bootstrap JS loaded - bootstrap.js and bootstrap.min.js. You only need one, and it's likely causing various issues.

**Comment by melmulcahy32** [comment]
Yup, once I removed the bootstrap.min.js the dropdown worked fine. Thank you all for your help!!!
