### ISSUE TITLE
How can i enable Cacheing?

### ISSUE THREAD

**Issue by cyberg33k** [wp-bootstrap/wp-bootstrap-navwalker#163]
How can i enable caching for bootstrap css file ?

**Comment by pattonwebz** [comment]
Hey @cybert33k

It's not really within the scope of a navwalker to help you with caching so I'll be closing this issue but I'm happy to help you sort something out.

Basically caching of .css files falls into the browser caching bucket. The easiest way to enable that on your site is probably by setting an expiry via .htaccess rules. You can set those rules yourself but if your not familiar with mod_expires or .htaccess rules then I'd suggest you allow a plugin to set it up for you. Both W3 Total Cache plugin and WP SuperCache have options for turning on browser caching but most caching plugins would likely have similar options.

Fell free to comment back if you need more assistance and I'll try my best to help :)
