### ISSUE TITLE
Navbar searchfield

### ISSUE THREAD

**Issue by Sajonara** [wp-bootstrap/wp-bootstrap-navwalker#167]
Hello.

Thanks for this awesome piece of code.

I'm starting to use it and I'm interested if it's possible to add a search field somehow?

Kind regards.

Alexander

**Comment by mindctrl** [comment]
See this https://github.com/twittem/wp-bootstrap-navwalker/issues/124#issuecomment-52422337

**Comment by kim07** [comment]
wow
