### ISSUE TITLE
use to list custom post type categories in nav?

### ISSUE THREAD

**Issue by nostahl** [wp-bootstrap/wp-bootstrap-navwalker#168]
how would I go about listing a custom post type's categories in a bootstrap navbar with this.

**Comment by pattonwebz** [comment]
The CPT categories you would just add to a WordPress menu the same way you would add any other link (through the **Appearance >> Menus** page of the dashboard).

If you're meaning you want to add them to the menu dynamically (IE without you needing to go in and add a new menu item each time you add a category) then that is beyond the scope of this walker but you could do that by grabbing the categories and appending them to the menu using the `wp_nav_menu_items` filter.

``` php
add_filter( 'wp_nav_menu_items', 'your_custom_menu_item', 10, 2 );
function your_custom_menu_item ( $items, $args ) {
    // you would need to grab an array of the CPT categories here

    // a conditional to add this only to a specific menu - here it is menu with ID 'primary'
    if ($args->theme_location == 'primary') {
        // you would output the categories here in an <li> element, below is an example
        $items .= '<li>Show whatever</li>';
    }
    return $items;
}
```
