### ISSUE TITLE
Modal boxes not working (Popup Maker)

### ISSUE THREAD

**Issue by sherkx** [wp-bootstrap/wp-bootstrap-navwalker#171]
Any ideas why this could be? The html is <a class="popmake-XYZ" href="#"> and the '#' appears when hovering but no modal box appears after clicking it? Love the navwalker but this is killing me right now!

thanks

**Comment by mindctrl** [comment]
Probably a javascript conflict. Got a link to the site?

**Comment by sherkx** [comment]
reinstalled and is working fine. Thanks anyway!
