### ISSUE TITLE
Dropdown menu height bug + glyphicon class

### ISSUE THREAD

**Issue by cbjewelz** [wp-bootstrap/wp-bootstrap-navwalker#172]
If you place the "dropdown-header" in the title attribute for a dropdown link, then a glyphicon span is also inserted above our menu item with class="glyphicon dropdown". Because the dropdown-header class already exists in bootstrap, this gives the span padding and height, messing up your vertical alignment of menu items.

Easy fix is to change line 112 to: 
`if ( ! empty( $item->attr_title ) && esc_attr( $item->attr_title )!= "dropdown-header")`

From the code comments, looks like the menu item has only been checked for a divider and header, not dropdown.

Also, the glyphicon class is "glyphicons" (plural), so line 114 should be changed to:

```
$item_output .= '<a'. $attributes .'><span class="glyphicons ' . esc_attr( $item->attr_title ) . '"></span>&nbsp;';
```

**Comment by pattonwebz** [comment]
This is a very old issue. In the interest of clearing out older or inactive issues to focus on active ones; I'm closing this for now. Feel free to reopen if this is still an issue.
