### ISSUE TITLE
Toggle menu not showing

### ISSUE THREAD

**Issue by moyanich** [wp-bootstrap/wp-bootstrap-navwalker#174]
the menu items are not show once the screen reaches smaller viewport size, please help
![screenshot-dev-briteeyedia pantheon io 2015-06-03 23-21-55](https://cloud.githubusercontent.com/assets/11672418/7976854/616e50ca-0a47-11e5-8394-292d32cf4065.png)

**Comment by LouisMilotte** [comment]
did you include jquery and the bootstrap.js or bootstrap.min.js

**Comment by debrajrakshit** [comment]
Most probably jQuery conflict. It's hard to tell this way unless you paste your code.

**Comment by moyanich** [comment]
thank you for responding, this is the code

<div id="page" class="page">
        <header>
            <nav class="main-nav navbar navbar-default" role="navigation">
                <div class="container">
                    
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="navbar-brand navbar-brand-centered"> <a class="brand" href="<?php echo site_url(); ?>"><?php bloginfo('name'); ?></a></div>

```
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-brand-centered">
                    <ul class="nav navbar-nav">                         
                         <?php
                            wp_nav_menu( array(
                                'menu'              => 'primary',
                                'theme_location'    => 'primary',
                                'depth'             => 2,
                                'container'         => 'div',
                                'container_class'   => 'collapse navbar-collapse',
                                'container_id'      => 'navbar-brand-centered',
                                'menu_class'        => 'nav navbar-nav',
                                'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
                                'walker'            => new wp_bootstrap_navwalker())
                            );
                        ?>                  
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <?php
                            wp_nav_menu( array(
                                'menu'              => 'secondary',
                                'theme_location'    => 'secondary',
                                'depth'             => 2,
                                'container'         => 'div',
                                'container_class'   => 'collapse navbar-collapse',
                                'container_id'      => 'navbar-brand-centered',
                                'menu_class'        => 'nav navbar-nav navbar-right',
                                'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
                                'walker'            => new wp_bootstrap_navwalker())
                            );
                        ?>  
                    </ul>


                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
```

**Comment by mindctrl** [comment]
@pixelangel not sure if this would break it, but you have duplicate IDs. Do you have a link where we can see it in action?

**Comment by moyanich** [comment]
@mindctrl the website is http://dev-briteeyedia.pantheon.io/ ..oh i did not realize i had a duplicate ID i will change it and see if that makes a difference

**Comment by moyanich** [comment]
@mindctrl so it is not the duplicate id's that the issue please look at the site and let me know that you think.

**Comment by mindctrl** [comment]
@pixelangel Try removing this: `'container_class'   => 'collapse navbar-collapse',`.

**Comment by moyanich** [comment]
@mindctrl thank you for help that solved the problem.very much appreciated.
