### ISSUE TITLE
Menu Link open in New Window

### ISSUE THREAD

**Issue by cdralderson** [wp-bootstrap/wp-bootstrap-navwalker#175]
I was wondering if anyone has found a way to configure a single Custom Link Menu Item to open in a window?

I have managed to implement the bootstrap-navwalker and it's working fine, I just have a single Menu Item that I desire to open in a new window and can't find it anywhere!

Any help would be very much appreciated!

Thanks,
Chris

**Comment by mindctrl** [comment]
@cdralderson that's a WP core feature. Under Appearance > Menus, click Screen Options in the top right and select Link Target. http://cl.ly/image/362D0d3t0E32

That will give you this option on the menu items. http://cl.ly/image/3H1g3H3f1f43

**Comment by cdralderson** [comment]
Thought it was, was just a bit stumped as wasn't on the page!
Apologies for being an idiot!!

Many thanks!
