### ISSUE TITLE
Parent menu gets disabled when submenu is added

### ISSUE THREAD

**Issue by Guboya** [wp-bootstrap/wp-bootstrap-navwalker#179]
The menu is getting implemented and all the classes seem to be working. The issue that I am having is that if I add a submenu to any menu item, that menu item gets disabled with a href=”#” as opposed to being populated with the proper link. The submenu shows up with the proper styling, but the parent menu has no link.

**Comment by SideQuestDIY** [comment]
With Bootstraps default functionality all items with a submenu do not have a parent link in order to support mobile first. 

This is functioning correctly, any functionality outside of this is not supported
