### ISSUE TITLE
code to make it default for all menus

### ISSUE THREAD

**Issue by eduardoarandah** [wp-bootstrap/wp-bootstrap-navwalker#182]
Would it be possible to add a hook in my functions.php file to make every menu implement this feature?

Why:
Menu widgets in sidebars ignore this walker

**Comment by SideQuestDIY** [comment]
No, to my knowledge this is not possible.

**Comment by pattonwebz** [comment]
There is a filter available for modifying what is passed to `wp_nav_menu();` that you can use to do this:`wp_nav_menu_args`. Adding this to your theme's functions.php file should make every menu default to using this walker.

``` php
function global_custom_walker( $args ) {
    return array_merge( $args, array(
        'walker' => new wp_bootstrap_navwalker(),
    ) );
}
add_filter( 'wp_nav_menu_args', 'global_custom_walker' ); 
```

Look at this [excelent answer](http://wordpress.stackexchange.com/a/53952) for a bit more info.

**Comment by SideQuestDIY** [comment]
Epic! I will add this to the documentation for the next version.
