### ISSUE TITLE
Fallback for menu with no content doesn't work.

### ISSUE THREAD

**Issue by B1gJ4k3** [wp-bootstrap/wp-bootstrap-navwalker#183]
If I implement this, but don't create any menu content, I would expect it to use the default fallback of wp_page_menu, but it doesn't seem to work. It just get empty list items with blank links.

I see that there's a fallback function in the code, but it also doesn't seem to do anything...

**Comment by SideQuestDIY** [comment]
The wp_page_menu fallback doesn't respect custom walker classes so in this case it would cause things to break.

The custom call back is setup so if your logged out you should see nothing, if your logged in you will see a link to the menu admin to select a menu.

**Comment by bhubbard** [comment]
We could look into offering a second fallback option to output the default wordpress page list.

**Comment by pattonwebz** [comment]
I'm going to close out this issue as the fallback menu does work. For thoughts on the idea of a 2nd fallback containing a page list we could open a dedicated issue thread for that if that was still something people were interested in pursuing.
