### ISSUE TITLE
Dropdown menu doesn't work with wordpress download manager plugin

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#184]
I've installed wp bootstrap navwalker and wpdm in my website (built with WP 4.2), then my navigation and its dropdown menu doesn'work. Did anyone have the same experience? How can I solve that problem?

**Comment by SideQuestDIY** [comment]
This is typically cause by a JavaScript conflict on the theme side with the installed plugin. If you dig in you will most likely see the code for the menu is output correctly vut cannot toggle as the JS is experiencing errors.
