### ISSUE TITLE
Images in the README broke

### ISSUE THREAD

**Issue by radscheit** [wp-bootstrap/wp-bootstrap-navwalker#185]

**Comment by SideQuestDIY** [comment]
Can you please provide some context for this.

**Comment by radscheit** [comment]
Of course, the main README file of this repo should contain images, but their linkings are all broken, please have a look on the attachement. I don't think that this is a client problem, but if you are interested in the browser i use: Chrome in the current version on Mac OS X Yosemite.
![bildschirmfoto 2015-07-26 um 23 04 43](https://cloud.githubusercontent.com/assets/6578648/8895905/ef7004fa-33ea-11e5-85ac-53fa689be35b.png)

**Comment by SideQuestDIY** [comment]
I replied from email where the title was "Links in the README broke" before you changed it to "Images in the README broke" ... an issue with no context is extremely frustrating.

This is a known issue (an open ticket #159 already exists, please search before creating new issues) that I am working to resolve. The images were hosted with GitHub and they made changes to how they are handled. I no longer have the images and I have been searching for a solution to there new hosting scheme but it is undocumented.

**Comment by radscheit** [comment]
So sorry for that. Next time I will do better.
