### ISSUE TITLE
Looking to add feature to menu items. How can this be done?

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#188]
Hey, first off thanks for this.

For me this is working just fine, but I wanted to know how we can add number of posts for dropdown menu items that are categories. For example:
- Topics
  - Category 1 (5)
  - Category 2 (8)
  - Category 3 (2)

etc...

Any help would be much appreciated, thanks.

I'm also adding a screen shot of what I currently have:

![screen shot 2015-08-03 at 11 22 40 am](https://cloud.githubusercontent.com/assets/1234484/9042095/06898840-39d2-11e5-865c-e27e77cccc91.png)

**Comment by pattonwebz** [comment]
The navwalker outputs items that are pre-set in the menu editor. If you wanted the totals to be present when the walker adds the menu to the page then the running totals would need to be set in advance.

To make that happen is a rather complicated process that would involve updating the menu items and setting them with new values each and every time one of the topics had a new post added. This is not something that a navwalker would do - it's a custom featured that would be better suited in your theme's functions.php file or a plugin.

Potentially you could update add the totals to the menu items dynamically after the page loads by querying for the post counts client-side with javascript and adding it to the page at that point. Again this isn't really something that a navwalker would handle.

**Comment by ghost** [comment]
@pattonwebz Thank you for your response. I will take a look at this a little deeper and if I find a solutions I'll make sure come back here and explain.
