### ISSUE TITLE
Dropdown button is not working 

### ISSUE THREAD

**Issue by Niklas2908** [wp-bootstrap/wp-bootstrap-navwalker#194]
hi,
i started to work theme using the latest WordPress 4.3.1
after i failed to get the Burger button to work without navwalker 
i downloaded it but i still cant get the button to show my menu items 
in the mobile or tablet sizes...
The naviagtion and all in it is shwing up on my pc the butten aswell when i am in 
on the mobile but it would show the list?
anyone having the same problems

**Comment by ghost** [comment]
I'm having the same issue, did you manage to find a workaround?

**Comment by ghost** [comment]
This is not an ideal solution but it works.  Simply put 

```
<div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-   target=".navbar-ex1-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                  </div>
```

before calling the wp_nav_menu in the header.php

**Comment by Niklas2908** [comment]
Hey figured that I just had a wrong order in my function file pretty basic mistake 

Sent from Yahoo Mail on Android
