### ISSUE TITLE
adding class active to submenu after reloading page

### ISSUE THREAD

**Issue by umanga907** [wp-bootstrap/wp-bootstrap-navwalker#195]
How can i add class active to the submenu. i have a sidebar which has depth 2 submenus but not able to add class active.

**Comment by pattonwebz** [comment]
I apologize that this issue was not dealt with at the time it was opened. In the interest of clearing out older or inactive issues to focus on active ones; I'm closing this for now. Feel free to reopen if this is still an issue.
