### ISSUE TITLE
Wrong Nav Item "active" on custom post types

### ISSUE THREAD

**Issue by marissalerer** [wp-bootstrap/wp-bootstrap-navwalker#196]
I've had this issue before but I can't for the life of me figure out how I solved it last time.
Basically I have a custom post type called "press" when I'm on the /press page it is showing the "blog" nav as the current_page_parent. Blog is my general posts page.

**Comment by bhubbard** [comment]
We have updated to 2.0.5, please update and let us know if you still have issues.
