### ISSUE TITLE
menu links are not published

### ISSUE THREAD

**Issue by sunilw** [wp-bootstrap/wp-bootstrap-navwalker#199]
This is because: within the wp_nav_menu call, the value to 'theme_location'  is outdated.

To fix this issue update to the following

'theme_location'    => 'primary navigation',

**Comment by LouisMilotte** [comment]
Did you create a pull for this? @sunilw

**Comment by pattonwebz** [comment]
Hey,

The `theme_location` entry is a pointer to the ID given to the menu when it was created with `register_nav_menu()`.
