### ISSUE TITLE
Caret in Submenu

### ISSUE THREAD

**Issue by phektiong** [wp-bootstrap/wp-bootstrap-navwalker#2]
Hi,

I used your navwalker and found that in submenu which has items, there's an caret which make it double carets (▼ and ►).
![double caret](https://f.cloud.github.com/assets/3077718/21241/b0ca86fe-4995-11e2-8446-72bdcd6b351e.JPG)

**Comment by SideQuestDIY** [comment]
That is interesting. Thanks for providing a screen shot, it really helps. I will take a look at this in the morning. 

I don't get the same issue on my install. What version of WordPress are you using?

**Comment by SideQuestDIY** [comment]
Sorry, what version of Bootstrap are you using, and is it a custom build theme or can you link to the project?

**Comment by phektiong** [comment]
Bootstrap 2.2.2, it's standard version.

**Comment by SideQuestDIY** [comment]
@phektiong It seems there was a change in the CSS for carets in the 2.2.2 update. I have updated the caret output logic to reflect the change. It was tested with WordPress 3.5 using the _s theme and Bootstrap 2.2.2

Thank you for letting me know about the issue.
