### ISSUE TITLE
no icon appears on mobile

### ISSUE THREAD

**Issue by BrianBam** [wp-bootstrap/wp-bootstrap-navwalker#202]
It appears to work great except when I get to below 768px then no icon appears to toggle the menu.  

http://drycreekpt.andfitness.com/

**Comment by LouisMilotte** [comment]
line reference?

**Comment by BrianBam** [comment]
Well when you view the source code it starts on line 459.   Is that what you were asking?  Is there a paid version for this plugin?  If I could get this plugin to work on desktop, tablet, and mobile views I'd pay or donate to this plugin.

**Comment by LouisMilotte** [comment]
According to chrome debug: You didn't include the sm/xs icon "Burger" elements.

**Comment by BrianBam** [comment]
Yes I saw that too and just don't get why some of the markup is missing.  In comparing the markup from the bootstrap page to this site I see what is missing.  Are we suppose to somehow manually add that ourselves??  
![nav_missing_markup](https://cloud.githubusercontent.com/assets/6227503/11308474/b4ffd718-8f7b-11e5-9d97-ae4410d51477.JPG)

**Comment by LouisMilotte** [comment]
When you're editing your theme; you manually add the markup as seen on 
the introduction of this plugin.

**Comment by BrianBam** [comment]
Holy cow I don't know how I missed that.  I kept reviewing the documentation and just ignored that code. Thanks I was stumped for the longest time on this.
