### ISSUE TITLE
Dropdown parent links showing # as href

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#204]
It appears that when a dropdown menu has been created, the parent menu item loses the link to the page, and is replaced by `href="#"`.

Is there anyway to retain the link to these pages, and also activating the dropdown header? Or maybe change the dropdown on click to, on hover? That way maybe all the links can be used?

**Comment by SideQuestDIY** [comment]
This is intentional as this is how the Bootstrap works, and is required for proper mobile UX. 

If you search the issues workarounds for this have been addressed many times.
