### ISSUE TITLE
Validation Error: Attribute url not allowed on element a at this point

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#205]
When using this walker class, the parent item that holds the dropdown menu comes up with a validation error stating:

> Attribute url not allowed on element a at this point.

In my example, the menu item is generated like this:

`<a title="IVR" url="http://inveroak.local/ivr/" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true">`

This can be rectified by commenting Line 82 of wp_bootstrap_navwalker.php:

`//$atts['url']    = ! empty( $item->url )         ? $item->url    : '';`

**Comment by LouisMilotte** [comment]
why are you using url as an attr and where is your href attr?

**Comment by ghost** [comment]
That's my question. The url attribute shouldn't be used. But it's being applied through the walker....

**Comment by LouisMilotte** [comment]
Which version of the walker is this coming from?

I just checked the one up right now for Master and line 82 is empty, Also, where the uri is applied the attr url doesn't exist; however, url is referenced and applied to the href attr.

**Comment by bhubbard** [comment]
This is probably related to an outdated version, closing the issue. If you continue to have problems after updating to 2.0.5 you can reopen the issue.
