### ISSUE TITLE
Drop-down top menu link not working

### ISSUE THREAD

**Issue by imalisiddique** [wp-bootstrap/wp-bootstrap-navwalker#209]
Drop-down top menu link not working.

**Comment by mindctrl** [comment]
We need more info, but usually this is caused by invalid markup or javascript errors. Check your browser dev tools console.

**Comment by jampa** [comment]
Happening to me also, when adding a sub navigation menu item, walker strips the url from parent link and makes it "#" instead of keeping the url.

Fix for this here: https://github.com/twittem/wp-bootstrap-navwalker/issues/113

**Comment by alexluecke** [comment]
I think it would be reasonable to make this a configurable parameter for the menu.
