### ISSUE TITLE
2nd level not working on iPhone

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#21]
On my installation the 2nd level doesn't work. When expanding the first level dropdown the page reloads (it seems) and the menu isn't clickable. When clicking the menu collapse and the 1st level links are clickable again. See test URL: http://bok.hoi.se/menu-bug

**Comment by SideQuestDIY** [comment]
I'm not sure I understand how to troubleshoot this issue as I do not have an iOS device. Your menu functions as it should from my android device.
