### ISSUE TITLE
Show post titles within Wordpress bootstrap Dropdown menu

### ISSUE THREAD

**Issue by rerraw** [wp-bootstrap/wp-bootstrap-navwalker#212]
I created custom bootstrap navwalker class for my wordpress theme all things work correctly i has this code below within `function start_el(){}`

When i put `<h2>Hellow World!</h2>`  within `$item_output` the dropdwon menu show the `Hello World!` four times in four column without any problem

But when i want put the `the_title()`  Wordpress function within `$item_output` like this `<h2>'.the_title().'</h2>` Show me the `Hello World!` post title above the main menu items, not within the dropdown menu

How i can solve this problem?

this is my code within `function start_el(){}`

```
if (!empty($item->divideto_4)) {
    $col = 3;
    $divide_to = 12 / $col; //4

    for ($i=0; $i<$divide_to; $i++) {
        $item_output .= '<div class="col-sm-'.$col.'"><h2>Hellow World!</h2></div>';
    }
}
```

**Comment by pattonwebz** [comment]
This is likely no longer an issue but...

What happened here is that the `the_title()` function actually echos out the title (right then and there - way before the walker starts its output) rather than it being added to the `$item_output` variable.
