### ISSUE TITLE
Conflict with the normal Walker

### ISSUE THREAD

**Issue by bicho44** [wp-bootstrap/wp-bootstrap-navwalker#213]
Hi:

Im trying to use the the Walker in my main menu, and then use anothe menu with the social icons, just like the Justin Tadlock [http://justintadlock.com/archives/2013/08/07/social-media-nav-menus] And the menus don add the classes after the first item. 
`<?php if ( has_nav_menu( 'social-media' ) ) {

```
wp_nav_menu(
    array(
        'theme_location'  => 'social-media',
        'container'       => 'nav',
        'container_id'    => 'menu-social-media',
        'container_class' => 'menu',
        'menu_id'         => 'menu-social-media-items',
        'menu_class'      => 'menu-items',
        'depth'           => 1,
        'fallback_cb'     => '',
    )
);
```

} ?>` 

If I don't use the bootstrap-walker, the social menu goes without problem, but i lost the bootstrap submenus in the main one.

**Comment by pattonwebz** [comment]
Hmm.... I don't think this is a conflict with this navwalker vs the normal navwalker - in fact the point of a custom walker is to override, or extend, the default one. 

It sounds like you have 1 menu that is normal (IE with menu-items/links etc) and another that is social icons. If that's the case I think you'd probably want 2 calls to `wp_nav_menu()`. One that uses the Bootstrap styles and outputs via the class in wp_bootstrap_navwalker.php - and then the social menu that outputs with default walker.

If you have social icons inside the menu that uses the wp_bootstrap_navwalker then this walker would need some modifications to get it outputting the social icons.

Assumedly what you have works in 1 of 2 ways: 
- URL parsing to define the social network from it's link so the right icon is output
- or your manually tagging each menu item with the correct network. 

Both those situations are beyond what the navwalker was intended to deal with.
