### ISSUE TITLE
Dropdown not working (wordpress 4.4.1)

### ISSUE THREAD

**Issue by SilentAce** [wp-bootstrap/wp-bootstrap-navwalker#214]
Your Walker class is not working with the dropdowns at all. The a elements are still missing the class="dropdown-toggle" and data-toggle="dropdown". Sub menu items are missing class="dropdown-menu".

**Comment by mindctrl** [comment]
@SilentAce it definitely works in WP 4.4.1. Can you share your implementation details? Which version of Bootstrap are you using? What does your HTML markup look like where you call `wp_nav_menu()`?

**Comment by rogerlos** [comment]
This seems to be related to the use of the minified version of bootstrap. The menus work with the unminified version, but don't work with the minified version (using the 3.3.6 download from bootstrap's site).

**Comment by nreck** [comment]
I'm also having this problem. Is there a fix yet?

**Comment by dannymichel** [comment]
Same

**Comment by evansnave** [comment]
same problem here

**Comment by AlexAHK** [comment]
Also seeing this issue.

**Comment by bhubbard** [comment]
Gonna close this issue, the latest version just released [2.0.5] works fine with the minified version of bootstrap. If you continue to have issues after updating please provide us a url and some more information so we can assist.

**Comment by evansnave** [comment]
I found a solution. Change "div" to "ul".
