### ISSUE TITLE
Mobile Drop down sub links not working

### ISSUE THREAD

**Issue by stesouthby** [wp-bootstrap/wp-bootstrap-navwalker#217]
HI Guys I have been using this on my word press site and it works in the web browser even when I place the browser into developer tools and select a mobiles screen size but soon as I go onto an actual mobile the drop downs just open and close they will not select the link i am using bootstrap v3.3.6 wordpress version 4.4.2 

here it the functions file
<?php 

function wpbootstrap_scripts_with_jquery()
{
    // Register the script like this for a theme:
    wp_register_script( 'custom-script', get_template_directory_uri() . '/js/bootstrap.js', array( 'jquery' ) );
    wp_register_script( 'jquery', get_template_directory_uri() . '/js/jquery-2.2.0.min.js', array( 'jquery' ) );
    // For either a plugin or a theme, you can then enqueue the script:
    wp_enqueue_script( 'custom-script' );
    wp_enqueue_script('jquery');
}
add_action( 'wp_enqueue_scripts', 'wpbootstrap_scripts_with_jquery' );

require_once('wp_bootstrap_navwalker.php');
register_nav_menus( array(
    'primary' => __( 'Primary Menu', 'THEMENAME' ),
) );
?>

**Comment by bhubbard** [comment]
Can you please update to version 2.0.5 and let us know if you continue to have any issues.
