### ISSUE TITLE
dropdown not working on mobile

### ISSUE THREAD

**Issue by sapna05** [wp-bootstrap/wp-bootstrap-navwalker#220]
I'm using navwalker menu for my wordpress theme it works perfect but I only have issue with mobile dropdown,currently the parent menu item is not linked it workes only as a handle for dropdown, if I link the parent menu item then on the mobile when you click on the parent menu item it drops down the sub menu item then quickly directs you to the parent menu item page.

if change the dropdown link from parent menu item and only apply it to the caret/glyphicon how would I go about this, please help i'm looking to solve this issue for a while now and I don't want to give up on navwalker menu!

**Comment by BAHO** [comment]
I'm using also this navwalker working fine for me. Can you post your code and URL so we can look what's going wrong

**Comment by WebDragon** [comment]
recommend setting the parent menu to be a Dropdown Header, and duplicating what would have been the parent menu's link, in the submenu itself. 
So,

Employers >  <-- this would be a dropdown header, not a normal link
  Employers
  Employees
  Search Jobs
etc.

**Comment by bhubbard** [comment]
@WebDragon This is how twitter boostrap nav menus work by default, the parent link doesn't work as a regular link. It was designed this way on purpose by the bootstrap developers.
