### ISSUE TITLE
Wordpress Bootstrap Navigation on Smartphone

### ISSUE THREAD

**Issue by Sarahts** [wp-bootstrap/wp-bootstrap-navwalker#221]
Hey everyone,

on my webiste http://www.casaleonmembersclub.com I would like to collapse the dropdown menu on the smartphone version, in order to avoid having an non ending menu list on mobile devices. I am using Bootstrap v3.2.0. If my website is not working for you, as it is only accessible for Germany and USA, here a screenshot http://www.teamschostek-werbeagentur.de/Bildschirmfoto%202016-04-25%20um%2016.31.54.png. I want the points of the dropdown menu to be collapsed to parent level, first on click to be opened.

I hope someone can help me out.

Thank you in advance :-)
Regards, Sarah

**Comment by pattonwebz** [comment]
This is a very old and looks to be mostly front-end related changes not handled by the walker. In the interest of clearing out older or inactive issues to focus on active ones; I'm closing this for now. Feel free to reopen if this is still an issue.
