### ISSUE TITLE
Menu renders, but drop downs don't work.

### ISSUE THREAD

**Issue by zehriya** [wp-bootstrap/wp-bootstrap-navwalker#223]
I noticed a few tickets with this issue. I tried some of those solutions and it didn't work. When I remove the walker, all the submenus become visible below the main menu. 

This is an already existing site that I have been asked to make responsive. 
Because of that I opted to do this as a plug-in. 

[http://outreach.boucherco.com/](url)

I think it might be something with the site. Prior to this I tried the ubermenu plugin. It displayed but also would not show the drop down submenus.

**Comment by pattonwebz** [comment]
Looking at the link in the issue it seems that this was either fixed or you opted to use a different walker/system. Closing for the moment but if you do have a solution it would be awesome if you posted the solution here :)
