### ISSUE TITLE
Collapsing the menu after clicking on an anchor link

### ISSUE THREAD

**Issue by ClaudiaDeLuca** [wp-bootstrap/wp-bootstrap-navwalker#226]
I have a single page website and the menu is made with anchor links.
Clicking on a link it goes to the corresponding section but the menu doesnt'collapse and remains open hiding the whole screen. Is there a way to make the expanded hamburger menu automatically close after you click on an anchor link?
Thank you in advance.

**Comment by dkrieger** [comment]
if you use jquery you could try something like...

``` javascript
// when anchor link is clicked...
$('a').click(function () {
  // check to see if dropdown is open
  if ($(yourDrodown).hasClass('in')) {
    // send click to hamburger button
    $(yourHamburgerButton).click();
  }
});
```

kind of hacky but really easy to understand

**Comment by pattonwebz** [comment]
Bootstrap doesn't have a way to close the menu automatically.

Using the jQuery posted above, or by using your own custom JavaScript, is the recommended way to do what you want.
