### ISSUE TITLE
how to create a custom navwalker?

### ISSUE THREAD

**Issue by carolinapdw** [wp-bootstrap/wp-bootstrap-navwalker#228]
Hello everybody,

i am having a bit of a problem with my current navigation. I have no idea how I can use the navwalker on my code here to maintain the custom navigation. Maybe there is also an easier way to make this navigation but this is what i came up with: 

`<div class="container-fluid">
                <div class="navbar-header">

```
                <a class = "navbar-brand visible-xs" href = "<?php echo esc_url(home_url()); ?>"><img src="<?php echo get_template_directory_uri(); ?>/images/logo.png" alt="logo">"  width="50"> 
                </a><!-- /navbar-brand visible-xs -->

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button> <!-- /navbar-toggle -->

            </div> <!-- /navbar-header -->

            <div class="collapse navbar-collapse">

                 <ul class="nav navbar-nav navbar-right  hidden-xs social ">
                    <li><a href="#"><i class="fa fa-lg fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-instagram"></i></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-500px"></i></a></li>
                </ul><!-- /hidden-xs social -->

                <ul class="nav navbar-nav navbar-center">
                    <li><a href="index.html">HOME</a></li>
                    <li><a href="">PORTFOLIO</a></li>
                    <li class="dropdown hidden-xs"><a href="index.html" class="navbar-brand"><img id="logo-navbar-middle" src="C:\Users\Carolin_2\Desktop\nicole\logonew.png" width="50"</img></a></li>
                    <li><a href="index.html">LEISTUNGEN</a></li>
                    <li><a href="">KONTAKT</a></li> 
                </ul><!-- /navbar-nav -->

                <ul class="nav navbar-nav navbar-center visible-xs  social nav-pills">
                    <li><a href="#"><i class="fa fa-lg fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-instagram"></i></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-500px"></i></a></li>

                </ul><!-- /visible-xs social --> 

            </div> <!-- /navbar-collapse-->

        </div><!-- /container fluid-->`
```

I want my navigation to have a centered brand with logo and the links to different pages left and right next to the logo. Then I want to have social media icons on the top right. 
In the mobile view I want a different order of menu items. the brand with logo on the top and the social media at the bottom.
Does this make any sense?

I really hope someone can help me with my problem. I am a beginner in bootstrap and it took me a while to come up with this navigation. converting it to wordpress makes my navigation style dissapear. :'(

best,

Carolina

**Comment by bahiirwa** [comment]
If I understand your query properly, why not just make several menus in the functions.php file and attach menus to your wordpress flow? ie

register_nav_menus( array(
    'center_menu' => 'Center Menu',
    'social_menu' => 'Social Menu',
) ); 

then call the menus separately in the work flow. 

Also look at Bryan's https://codepen.io/bootstrapped/pen/KwYGwq. Hope it helps

**Comment by carolinapdw** [comment]
Thank you I will check the site :) 
my problem is, that i am a beginner and have no idea how to do this... but i will definetly try.

**Comment by bhubbard** [comment]
@carolinapdw Please update to 2.0.5 and if you continue to have issues you can re-open this issue.
