### ISSUE TITLE
Issue with collapsible menu

### ISSUE THREAD

**Issue by ehuelsda** [wp-bootstrap/wp-bootstrap-navwalker#230]
Hi everyone! 

I'm having trouble with my collapsible menu in xs view. When pressing the nabber button the menu doesn't open. I know it's not an issue with my jQuery, as everything else works. 

Does anyone have an idea what I'm doing wrong? I'm using one menu for xs and another for larger widths - not sure if that has any impact. 

Here's my code (one screenshot of the non-functioning menu and one of the "old" functioning html-only menu):

![collapsible menu](https://cloud.githubusercontent.com/assets/17674872/17223454/e7ad5b58-54fc-11e6-9b37-f26369f51ba4.png)
![html only menu](https://cloud.githubusercontent.com/assets/17674872/17223455/e7d991be-54fc-11e6-8de5-9ddf3c7c5efd.png)

Best,
Elena

**Comment by pattonwebz** [comment]
In the first screenshot you have `data-target="#bs-example-navbar-collapse-1"` but the actual menu uses `#bs-example-navbar-collapse-2 as it's ID`.

Change the "2" to a "1" on the div and it should target correctly :)

**Comment by ehuelsda** [comment]
Oh, yeah true. But after changing that it still doesn't work :(

**Comment by ehuelsda** [comment]
So I found the issue myself in the end, after some careful scrutiny with inspect element. 
I didn't realise that the div around my nav is actually superfluous and just duplicated the container added by the menu. So after I removed the surrounding div with class of "collapse navbar-collapse" the menu collapsing menu worked again (opens on clicking the button).
