### ISSUE TITLE
Help incorporating three level dropdown to wp

### ISSUE THREAD

**Issue by ssoney200** [wp-bootstrap/wp-bootstrap-navwalker#232]
Hi guys, I wonder if you can assist me with a little help.

I am trying to integrate a three-level bootstrap sub-menu which I have on my website to Wordpress using the wp-bootstrap-navwalker.

It's creating 3 levels just fine but the issues I am having are with few of the styles not carrying over.

Here is a link to the bootstrap site http://braden-threadgold.com/ewp/. If you roll over the 'GB' menu point and then the 'age group women' you can see how the menu is intended to work.

Now if you go to the wordpress version at http://braden-threadgold.com/ewp-wp/  and check the 'GB' dropdown you will notice a couple issues:

1) no red button on 'age group women' to indicate there is a third level menu
2) the third level no longer pushes to right and has no bed background etc.

This is my first time implementing with navwalker so wondered first off, is this actually possible using navwalker, and if so, can you provide me a few pointers to acheive?

Many thanks in advance! 
Jamie

**Comment by pattonwebz** [comment]
This is a very old issue and the links inside it are no longer active. I'm closing this issue for now but if you need help please comment and I will reopen it or open a fresh issue.
