### ISSUE TITLE
Dropdown won't work on mobile

### ISSUE THREAD

**Issue by penguininthefreezer** [wp-bootstrap/wp-bootstrap-navwalker#233]
Please help. I've been trying to make it work for hours and hours and hours now.

This is my first from-scratch Wordpress theme so apologies in advance for being an irritating noob.

This is what I'm seeing on mobile:

<img width="388" src="https://cloud.githubusercontent.com/assets/22207071/18534970/201629a2-7aa5-11e6-887a-9b8d5cab290d.png">

The layout is a mess for one thing (the greyed-out title has waayyyy too much padding-top; I suspect it's a nav-collapse issue - I could fix if it was a normal Bootstrap page, but I'm totally lost over here in php-land), but the problem is that click on the hamburger dropdown menu it does nothing. There are items in the menu that need to open and be dropped-down, but clicking doesn't do a thing. On desktop view, it looks fine, and dropdowns work as they should.

There are no errors on load in error console, however when I click on the hamburger menu I get the "223 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined" error.

I'm using the latest version of wordpress and I don't really have any plugins installed yet.

header.php looks like this (sorry for the screencap, markdown isn't working properly for me):
![image](https://cloud.githubusercontent.com/assets/22207071/18535012/7efbc8b4-7aa5-11e6-9edf-bea39465669d.png)

And the pertinent area of functions.php is:
![image](https://cloud.githubusercontent.com/assets/22207071/18535036/aaebed5a-7aa5-11e6-9247-7c9e592ac49f.png)

bootstrap.min.js and bootstrap.min.css are both files that exist, they are in the relevant folders in the theme.

And the navbar has been added in functions.php too:
![image](https://cloud.githubusercontent.com/assets/22207071/18535062/defd2636-7aa5-11e6-8cc8-474369782a92.png)

I would really appreciate like whoah anyone being able to help me figure out what's going on. Good karma for helping a newbie? :)

**Comment by bhubbard** [comment]
@penguininthefreezer We just updated to 2.0.5, can you try updating and let us know if you are still running into problems?

**Comment by pattonwebz** [comment]
This is an old issue that has been inactive for some time. In the interest of cleaning out inactive issues to focus on active ones I'm closing this out. If help is still required feel free to comment and I'll reopen it or you can start a new issue.
