### ISSUE TITLE
Can i sell my theme with navwalker?

### ISSUE THREAD

**Issue by rodlessa** [wp-bootstrap/wp-bootstrap-navwalker#234]
The code would be open to anyone thought github and the link for navwalker github.

**Comment by pattonwebz** [comment]
Yeah - this code is GPL so it's free to be used however you choose. Both personal and commercial projects is fine.

**Comment by jilvin** [comment]
@pattonwebz GPL license terms need the whole source to be opened if it is to be distributed as a software. A wordpress theme is none other than a "software". So, it seems your license and your intentions vary. It's better if you change your license to the LGPL version.

**Comment by SideQuestDIY** [comment]
I'm the author, go right ahead. I would love to see what you build.

**Comment by jilvin** [comment]
@pattonwebz With all love and respect, use of this software as such or in modified version in web services does not violate the GPL license. But when a theme is sold, it is actually distribution of the software code and in turn requires whole of the theme source code to be opened and distributed under the same GPL license.

See [here.](http://choosealicense.com/licenses/gpl-2.0/)

**Comment by pattonwebz** [comment]
@jilvin I appreciate your concern over my ambiguous statement about sale of a theme and neglecting to go into detail about licencing. The OP says attribution would be given and source would be would be available. I don't think using the walker makes a theme a derivative of the walker so I see no need to enforce (or even state) GPL on the theme.

Whether or not a theme is a derivative of WordPress (and as such required to be GPL compatible) had its own set of complexities surrounding it to the point where it's not fit me to state a theme does or does not require GPL.

As far as the scope of this question goes I stand by the statement that selling is ok.

**Comment by jilvin** [comment]
@pattonwebz Yeah. It's just like the use of Linux kernel. Anyway, we clarified the facts and sorry for all the trouble. Cheers.

**Comment by jilvin** [comment]
@pattonwebz Yeah. It's just like the use of Linux kernel. Sorry for all the trouble. Anyway, we clarified the facts. Cheers.

**Comment by jilvin** [comment]
@twittem It's better if the next release, change license to a _Lesser GPL version_ rather than the GPL version. You'll have to take permission from all your contributors to do so. Cheers.

**Comment by jilvin** [comment]
@twittem It's better if the next release change license to a _Lesser GPL version_ rather than the GPL version. You'll have to take permission from all your contributors to do so. Cheers.
