### ISSUE TITLE
it can not work in the moblie mode?

### ISSUE THREAD

**Issue by wastonchen** [wp-bootstrap/wp-bootstrap-navwalker#235]
have no idea for this issue, anyone can help with this, thank you so much in advance!!

in the PC View mode :
![image](https://cloud.githubusercontent.com/assets/15075737/19028780/8bdf0592-8972-11e6-8c75-6f89bc785807.png)

missing see below:
![image](https://cloud.githubusercontent.com/assets/15075737/19028792/a30fc1d4-8972-11e6-9ca0-cccd1508226a.png)

**Comment by JamesVanWaza** [comment]
@wastonchen post your code below.

**Comment by pattonwebz** [comment]
Perhaps the main menu is hidden behind the WP menu?

**Comment by bhubbard** [comment]
I believe @pattonwebz is correct, the menu is hidden behind the WordPress adminbar. If you view the site logged out it shouldn't be a problem.
