### ISSUE TITLE
Does not work for me :(

### ISSUE THREAD

**Issue by Halkawt97** [wp-bootstrap/wp-bootstrap-navwalker#237]
Here is my code, and I do not know why it does not work :(
```
<nav class="navbar navbar-inverse" role="navigation">
          <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">

                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a href="#" class="navbar-brand scroll-top"><img src="http://auis-env.org/wp-content/uploads/2016/11/logoo-copy.png" style="margin:-15px 0" height="50" alt="Environment Keepers' logo"></a>
              </div>
              <!--/.navbar-header-->
              <div id="main-nav" class="collapse navbar-collapse">
                <?php
					wp_nav_menu( array(
						'menu'              => 'primary',
						'theme_location'    => 'primary',
						'depth'             => 2,
						'container'         => 'div',
						'container_class'   => 'collapse navbar-collapse',
						'container_id'      => 'bs-example-navbar-collapse-1',
						'menu_class'        => 'nav navbar-nav navbar-right',
						'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
						'walker'            => new wp_bootstrap_navwalker())
					);
				?>
              </div>
              <!--/.navbar-collapse-->
      		</div>
      		<!--/.container-->
      </nav>
```

can anyone tell me where is the issue ?
The URL is auis-env.org

**Comment by pattonwebz** [comment]
Hey,

Can you explain where you're putting this code? Generally it would go in somewhere like the `header.php` file for this kind of navbar.

Also did you include the `wp_bootstrap_navwalker.php` file?

**Comment by DZuz14** [comment]
Delete the surrounding div that contains the code,

`<div id="main-nav" class="collapse navbar-collapse">`

Bootstrap nav walker automatically adds another div without telling you, so you will end up with two different divs in your html with the same classes, which will cause the mobile menu to not work. Make sure to remove the closing div tag obviously.

For those of you having this issue, before changing it, right click and view source and check out your nav code, you will 100% see two divs with the same class names, like this,

`<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">`

**Comment by pattonwebz** [comment]
There has been no update from OP for a long time stating if they found the issue of if a provided solution worked. Closed this issue as inactive.
