### ISSUE TITLE
All menu items are marked active and "highlighted"

### ISSUE THREAD

**Issue by KSVQ** [wp-bootstrap/wp-bootstrap-navwalker#240]
I have noticed that all the menu items are highlighted as active on WP version 4.7. How could I resolve this?

**Comment by bhubbard** [comment]
@KSVQ We just updated to version 2.0.5, can you update and let us know if you are still seeing the issue? If so can you provide a url?

**Comment by pattonwebz** [comment]
With no op feedback in some time and in the interest of clearing out inactive issues to focus on active ones; I'm closing this for now. Feel free to reopen if this is still an issue.
