### ISSUE TITLE
Feature Request: Ability to Pull Featured Image for menu items

### ISSUE THREAD

**Issue by KSVQ** [wp-bootstrap/wp-bootstrap-navwalker#243]
I don't think of this as an issue of course but I was looking around and can't quite find a solution. if I wanted to pull a featured image into drop down items, how could I do this. Modifying the walker,,, how?

Can I mark this somehow other than an issue?

**Comment by asathoor** [comment]
I'd rather do such a thing in the WordPress menu - that is from the dashboard. If it's a glyphicon, just add the span to the menu header. Or simply add an `<img>` tag there. That's what I've done here: [Multimusen.dk](http://multimusen.dk/).

**Comment by KSVQ** [comment]
I need to pull a featured image above the anchor text in drop down menus...

**Comment by pattonwebz** [comment]
Sorry this was left around so long without activity @KSVQ :(

Were you ever able to find a solution to add images to your menu items or would you still like someone to look into how to make this happen?

**Comment by KSVQ** [comment]
I didn't find a solution and mean while I developed my own script so I ended up not looking into it.

**Comment by pattonwebz** [comment]
Glad to hear you were able to develop your own script for what you needed. I think was a good option as this walker and the WP menu manager don't natively support images.
