### ISSUE TITLE
active class on ancestor

### ISSUE THREAD

**Issue by wpxdm** [wp-bootstrap/wp-bootstrap-navwalker#246]
Hi Thanks for the awesome navwalker.

I replaced the "active" class section so the ancestor nav item would show as active when the descendant is selected.

Totally new to bootstrap, so still figuring this stuff out.

            if(array_intersect($classes, array('current-menu-item', 'current-menu-ancestor'))) {
				$classes[] = ' active';
            }

**Comment by bhubbard** [comment]
Please update to 2.0.5, if you continue to have any issues you can re-open this issue.
