### ISSUE TITLE
Make us the default walker

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#258]
wp_nav_menu_args filter

If other args are on the default value change them to BS ones. E.g menu_class

Originally reported from @szepeviktor

**Comment by pattonwebz** [comment]
I'm not sure that we should be changing defaults in the walker without people explicitly making it happen.

I had previously noted some code capable of modifying the args using the filter you mention in this [other issue comment](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/182#issuecomment-128832901).

I think the best method might be to add examples of functions in the documentation of how this could be done. Code like this can easily be modified to change any of the args that are set.

```
function modify_nav_menu_args( $args ) {
    return array_merge( $args, array(
        'walker' => new wp_bootstrap_navwalker(),
    ) );
}
add_filter( 'wp_nav_menu_args', 'modify_nav_menu_args' ); 
```

I can work on a PR to add some info about this to the readme.

**Comment by szepeviktor** [comment]
@pattonwebz My vision was to use wp-bootstrap-navwalker without [modifying code](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/master/README.md#usage) at all. To function like a "wp-bootstrap-navwalker plugin".

**Comment by szepeviktor** [comment]
Thank you. 
Can you think of a situation with a bootstrap-based theme where having wp-bootstrap-nav the default walker has a disadvantage?


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by pattonwebz** [comment]
There shouldn't be any major disadvantages to setting the walker as default in this way. There are situations where adding some extra classes and wrappers will be needed to get the styles working correctly but so long as those are also added to the filter it should be good :)

**Comment by szepeviktor** [comment]
Thank you.

What is blocking this to get into the plugin? Is there someone out there who is not using it as the default??

**Comment by szepeviktor** [comment]
> That could result in some unexpected situations ...

Maybe this?

**Comment by pattonwebz** [comment]
Nothing is really blocking making this a plugin to set it as the default for all menus. 

The unexpected situations I mentioned are about styling issues when certain wrapper classes aren't on the containers of different menu types. For example a navbar menu would need a wrapper with a `collapse` class but a footer menu on the same site probably won't need to collapse (but may need a different wrapper for maybe a pills or tabs style menu).

If different classes were needed on the different menus then either a conditional in the filter or modification to the theme would be needed.

**Comment by szepeviktor** [comment]
Thank you for the clarification.
