### ISSUE TITLE
Add/Support Schema

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#261]

**Comment by jakewhiteley** [comment]
So I was looking at this recently.

It can be achieved by injecting `itemscope itemtype="http://www.schema.org/SiteNavigationElement"` into the `items_wrap` argument, but would need a few checks first to avoid:

* duplicating the attributes if present
* overriding or invalidating the `items_wrap` argument if set when calling the nav_menu

The other issue is that this would have to be added as a filter, as the args cannot be modified from within a walker itself.

I will see what I come up with :)

**Comment by pattonwebz** [comment]
@jakewhiteley any progress with this one so far? Let me know if you hit any technical issues and I'll do my best to help out.

**Comment by ghost** [comment]
@pattonwebz @jakewhiteley 
any update on this guys? it would be nice to add some more properties: 
https://schema.org/SiteNavigationElement

I think `url` and `name` are a must

**Comment by christiaanbruijnes** [comment]
He placed the schema markup in every single li, which shouldn't. It should be added into the <nav> and add the `url` and `name` yourself.
