### ISSUE TITLE
Research Support for Caching

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#263]
https://www.doitwithwp.com/use-transients-speed-wordpress-menus/

https://generatewp.com/how-to-use-transients-to-speed-up-wordpress-menus/

**Comment by szepeviktor** [comment]
And https://wordpress.org/plugins/voce-cached-nav/
or https://vip-svn.wordpress.com/plugins/cache-nav-menu/cache-nav-menu.php

**Comment by pattonwebz** [comment]
The code at the doitwithwp link was code that I partially wrote and is in use on a relatively large production site currently. The caching works just fine when done in that manner.

**Comment by pattonwebz** [comment]
The readme file contains some information about caching of nav menus and links to some resources benefits and drawbacks of specific caching methods.
