### ISSUE TITLE
Feature Request: Improved Composer support by publishing at Packagist.org

### ISSUE THREAD

**Issue by sebask** [wp-bootstrap/wp-bootstrap-navwalker#269]
Recently Composer support was added (great update!). Adding the project to https://packagist.org would improve Composer support since Composer will use the Packagist to find this package.

You only need to submit and publish WP Bootstrap NavWalker at Packagist. :)

**Comment by bhubbard** [comment]
@sebask I have gone ahead and submitted it to packagist. Let me know if you see any issues with it.

https://packagist.org/packages/wp-bootstrap/wp-bootstrap-navwalker

**Comment by sebask** [comment]
@bhubbard Thanks for publishing the project! I just tested, and it works great.
