### ISSUE TITLE
The new version (2.0.1) doesn't work for me

### ISSUE THREAD

**Issue by nguyen-tam** [wp-bootstrap/wp-bootstrap-navwalker#27]
This bug happens on Wordpress 3.6 
![screenshot from 2013-08-30 23 08 44](https://f.cloud.github.com/assets/412378/1058828/c109ede0-118e-11e3-95f9-0afefbb98755.png)

Please take a look at my screenshot. The problem here is wp_nav_menu generate div class="nav navbar-nav" instead of ul class="nav navbar-nav". Here is the full html : 
![screenshot from 2013-08-30 23 09 12](https://f.cloud.github.com/assets/412378/1058829/c9bb411e-118e-11e3-81af-13b68d3560b4.png)

and here is my header.php :
![screenshot from 2013-08-30 23 09 25](https://f.cloud.github.com/assets/412378/1058830/d239900c-118e-11e3-84d4-8a79aff7d4c4.png)

**Comment by SideQuestDIY** [comment]
That is an interesting issue and I had the same problem. It was solved for my be assigning the `'menu_class' => 'nav navbar-nav'` which assigns the class to the menu and not the container. I am using the same `wp-nav-menu` declaration and getting a different result. 

![nav-walker-sample](https://f.cloud.github.com/assets/1471150/1059368/7a070cf6-1199-11e3-8341-94adb37598d9.jpg)

To troubleshoot a bit further, is your menu defined in your functions.php file?

``` php
register_nav_menus( array(
        'primary' => __( 'Primary Menu', 'THEME NAME' ),
) );
```

Do you have a menu assigned to the Primary menu in the WP admin?

**Comment by nguyen-tam** [comment]
You're right, I need check the [theme locations] checkbox to Primary Menu. I think you should put it in the readme file .

![screenshot from 2013-08-31 08 33 05](https://f.cloud.github.com/assets/412378/1061488/6fbf46f2-11dd-11e3-95aa-2b6f6b7a1f75.png)

Thank you

**Comment by SideQuestDIY** [comment]
I will look into this further, the issues is the arguments for the class names are not passing to the wp_page_menu fallback function as they should by default.
