### ISSUE TITLE
.active class added to each sub menu item when using # anchors

### ISSUE THREAD

**Issue by madebyiando** [wp-bootstrap/wp-bootstrap-navwalker#273]
#### Steps to reproduce the issue:

Parent section - About
Add anchor link sub menus to same page.
All submenu links are set to active. Although the page name is the same, the anchor links are different

e.g.

/about/
- /about/#payments
- /about/#findoutmore

#### What I expected:

The sub menu anchor link that is used should only be selected

#### What happened instead:

All sub menu links are set to active.

**Comment by pattonwebz** [comment]
Hmm this might be a little tricky to figure out but will look into it.

Thanks for the bug report!

**Comment by mpmullally** [comment]
@pattonwebz I am having the same issue. I have a multi page site but have 2 nav items that link to anchors on the home page and when you are on the home page they get the active class.

The original site i turned into a wordpress theme used scrollspy for those two items. Could you have the php require scrollspy be enabled on the menu? I wish i could test on my own but i don't pretend to completely understand the code well enough to try.

**Comment by pattonwebz** [comment]
@mpmullally That would be out of the scope of the project for the walker but could likely be added in via the available menu filters. When you say 'php require scrollyspy' do you mean having some `data-*`attributes in place for it to work with?

**Comment by pattonwebz** [comment]
I'm going to close out this issue as it's not something that can be fixed directly in the walker. The `.active` class is applied to all the items that WP tags as a `.current-menu-item` so the limitation is with how WP decides what page is the currently active one. It obviously disregards fragments and considers them as being the same page regardless of what comes after the '#'.

To make this work would require something along the lines of scrollspy which @mpmullally suggests but that is not something that the walker class handles as it does not bundle any additional scripts along with the single main class file.
