### ISSUE TITLE
Cannot read property 'Item' of undefined

### ISSUE THREAD

**Issue by epull** [wp-bootstrap/wp-bootstrap-navwalker#279]
Hi, i've try implementation with 2.0.4 version in to Sage, all menu looks normal but when i click dropdown menu not working. 

#### Error Console
outlayer.js:39 Uncaught TypeError: Cannot read property 'Item' of undefined
    at outlayer.js:39
    at outlayer.js:39

#### What I expected:
I just want to show the dropdown menu looks normal.

#### Which I have tried:
bower install outlayer -> for update this lib, but unfortunatelly still not working :(

**Comment by pattonwebz** [comment]
Hi Achmad, 

I've not got much experience with outlayer.js but I seem to recall it being a library for using things like masonry layouts etc. It should be the functions in the bootstrap.js file that handle click events on the menu so sounds like a conflict with outlayer. Probably need to exclude the nav elements from the list of items that outlayer binds to.

I'm going to label this issue as `out of scope` but I'll leave it open and see if I can help you in anyway with this. Honestly I'm not sure how best I could help but anything I could do let me know :)
