### ISSUE TITLE
The drop down class is added to the widget menus also 

### ISSUE THREAD

**Issue by diegochavez** [wp-bootstrap/wp-bootstrap-navwalker#28]
I just realized the drop-down class is added to the regular widget menu and i just want this setup for my top page navigation,

**Comment by SideQuestDIY** [comment]
This is interesting as the walker class it only applied to the menus you explicitly add the walker class to. The only reason I can think of that this might happen is that your widget menu and the top menu have the same menu declaration. I would try changing the name of your primary menu.
