### ISSUE TITLE
My open issues

### ISSUE THREAD

**Issue by szepeviktor** [wp-bootstrap/wp-bootstrap-navwalker#283]
Hello @bhubbard !

I've opened some issues in your fork - I do not quiet remember where.

Could you help me find them?
Thanks.

**Comment by pattonwebz** [comment]
You can use the author filter in search boxes - `author:szepeviktor`. I don't see any other issues of yours in this repo.

**Comment by szepeviktor** [comment]
Thank you.
Yes it was *another* repo/fork where I've opened those.

**Comment by szepeviktor** [comment]
I've found an old email

```
Public codeclimate badges (#12)

"Sorry I beat you 2 it, but feel free to start knocking out a few of the other issues."

https://github.com/wp-bootstrap/wp-bootstrap-navwalker/pull/12#issuecomment-241566768
```

**Comment by pattonwebz** [comment]
Ohhh I think I see what has happened. That issue must have been part of this repo but then it was either merged or overwrote when the upstream repo was merged down to here. Sorry for anything that you may have lost,  I'm not familiar with this transfer process so unsure if that original issue/PR could be recovered 😕

**Comment by szepeviktor** [comment]
Then I should rediscover those issues with the code!

**Comment by pattonwebz** [comment]
So I'm hoping that you have been unable to rediscover those issues with the code, @szepeviktor (because I really hope we've fixed them by now haha!) but I was wondering if you had spotted any other issues/features in the current version of the walker that you could note? I'm working on a version for BS4 now that the beta release is (finally!) getting close - would like to fix as many things as possible before then :smile:

**Comment by szepeviktor** [comment]
Thank you for the followup.
I am not *yet* a wp-bootstrap-navwalker user.
Anyway, going through a [WP plugin](https://github.com/szepeviktor/wordpress-plugin-construction) takes days for me.

**Comment by pattonwebz** [comment]
Well if you try this walker and need any guidance when it comes to using or modifying things let us know :) 

Also that is a pretty large collection of plugins and utilities in your repo. Looks like you've been curating those for many years. Very useful :+1:
