### ISSUE TITLE
sanitize_html_class() "breaks" container class

### ISSUE THREAD

**Issue by vlasscontreras** [wp-bootstrap/wp-bootstrap-navwalker#285]
I put "breaks" in quotes because the function [`sanitize_html_class()`](https://codex.wordpress.org/Function_Reference/sanitize_html_class) actually does the work correctly.  Is meant to be used for single classes so it will remove the spaces between them. In this case, it removes the space between `collapse` and `navbar-collapse`, so the navbar collapse won't work properly because it will be visible on load.

But I haven't had this problem before, so my theory is that is something related with PHP 7 maybe (?) not quite sure. My server setup is:

Debian 9 Stretch
Apache/2.4.25
PHP 7.0.19-1
WordPress 4.8

#### Using the default implementation of the walker:

```php
wp_nav_menu( array(
    'menu'              => 'primary',
    'theme_location'    => 'primary',
    'depth'             => 2,
    'container'         => 'div',
    'container_class'   => 'collapse navbar-collapse',
    'container_id'      => 'bs-example-navbar-collapse-1',
    'menu_class'        => 'nav navbar-nav',
    'fallback_cb'       => 'WP_Bootstrap_Navwalker::fallback',
    'walker'            => new WP_Bootstrap_Navwalker())
);
```

#### Results in:

```html
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <!-- ... -->
        </div>

        <div class="collapsenavbar-collapse" id="default-primary-menu">
            <ul class="nav navbar-nav" id="menu-primary">
                <!-- ... -->
            </ul>
        </div>
    </div>
</nav>
```

Note the `collapsenavbar-collapse` class should be `collapse navbar-collapse`.

#### My workaround:
I found a function that does the same than `sanitize_html_class()` but works with multiple classes (thanks to [justnorris](https://gist.github.com/justnorris/5387539)):

```php
if ( ! function_exists( 'sanitize_html_classes' ) && function_exists( 'sanitize_html_class' ) ) {
  /**
	 * sanitize_html_class works just fine for a single class
	 * Some times le wild <span class="navbar-collapse collapse"> appears, which is when you need this function,
	 * to validate both navbar-collapse and collapse,
	 * Because sanitize_html_class doesn't allow spaces.
	 *
	 * @uses   sanitize_html_class
	 * @param  (mixed: string/array) $class   'navbar-collapse collapse' or array(  'navbar-collapse', 'collapse'  )
	 * @param  (mixed) $fallback Anything you want returned in case of a failure
	 * @return (mixed: string / $fallback )
	 */
	function sanitize_html_classes( $class, $fallback = null ) {
		// Explode it, if it's a string
		if ( is_string( $class ) ) {
			$class = explode( " ", $class );
		} 
		if ( is_array( $class ) && count( $class ) > 0 ) {
			$class = array_map( "sanitize_html_class", $class );
			return implode( " ", $class );
		}
		else { 
			return sanitize_html_class( $class, $fallback );
		}
	}
}
```

So I modified the `::fallback` method on the line `207` and replaced this:

```php
if ( $container_class ) {
    echo ' class="' . sanitize_html_class( $container_class ) . '"'; }
echo '>';
```

With this:

```php
if ( $container_class ) {
    echo ' class="' . sanitize_html_classes( $container_class ) . '"'; }
echo '>';
```

And now the menu works fine. If I'm mistaken and this is not a correct solution let me know.

**Comment by pattonwebz** [comment]
Hey @vlasscontreras, 

This is most certainly a bug and you identified that it's due to multiple classes being passed to sanitize_html_class when it expects only a single class. I will look at fixing this in the next few days.

Thanks for such a detailed issue report with what you found out and what you already tried, it makes getting a fix for this so much easier :)
