### ISSUE TITLE
Two PHPCS config files

### ISSUE THREAD

**Issue by szepeviktor** [wp-bootstrap/wp-bootstrap-navwalker#292]
Why are there Two PHPCS config files?

1. phpcs.ruleset.xml
1. phpcs.xml

Found during #291

**Comment by pattonwebz** [comment]
I think the testing setup was added from a template. Perhaps there is 2 here because there was 2 in the template :stuck_out_tongue: 

Honestly I am unsure of why there is 2 here or if there is need for both. @bhubbard is who added the the testing setup so maybe he can shed some light on it?

**Comment by bhubbard** [comment]
I believe one was generated by WP Enforcer, and the other was generated by WP-CLI command for unit testing. I don't remember which created which.  Not sure if both can be configured to use one.

**Comment by szepeviktor** [comment]
Could I try adding a parameter to wp-enforcer?
https://github.com/stevegrunwell/wp-enforcer/blob/develop/bin/wp-enforcer#L44

This would result in a common config file.

**Comment by bhubbard** [comment]
@szepeviktor Go for it, I haven't had the time to try.

**Comment by szepeviktor** [comment]
@bhubbard What is the next issue you would like to be solved?

**Comment by pattonwebz** [comment]
Hey @szepeviktor I really appreciate your help on these issues :)

As for what to work on next you can really just pick any issue that you think is important. To me I would really like to get this version of the walker for Bootstrap 3 finished off. One specifically that I've been meaning to take care of but haven't yet is this one: #285 but feel free to look at any other one you prefer.
