### ISSUE TITLE
Update Readme with Details about Bootstrap v4

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#294]
Its probably gonna be a while until Bootstrap v4 is out of beta, we should update the readme providing info about the Bootstrap v4 Branch, and the status.

**Comment by knightknight** [comment]
This thread might also be worth referencing #238 it also has a [post](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/238#issuecomment-310944184) for a currently working [bs4navwalker](https://github.com/dupkey/bs4navwalker).
