### ISSUE TITLE
Divider not working in v4

### ISSUE THREAD

**Issue by ge022** [wp-bootstrap/wp-bootstrap-navwalker#301]
#### Steps to reproduce the issue: 
adding a Link menu item with a URL of # and a Link Text or Title Attribute of divider

#### What I expected: 
a divider to show up instead of the text

#### What happened instead: 
text showed up

Am I doing something wrong?

**Comment by pattonwebz** [comment]
Hey @ge022,

You're not doing anything wrong - dividers, headers and icon support is reworked for BS4 version and I have not managed to make dividers work correctly as of yet. Work will continue to add support for every feature available in Bootstrap 4 however at the moment icons and disabled links are the only link modifiers that are working :(

**Comment by ge022** [comment]
Okay, thanks for letting me know.
