### ISSUE TITLE
Caps in the menu array (copied how to text)

### ISSUE THREAD

**Issue by Mthibodeaux-hub** [wp-bootstrap/wp-bootstrap-navwalker#303]
#### What happened instead: it returned an error saying it could not find the file, I fixed this by correcting the capital letters in the example of what to add to your page. If you copy the text as is the call for the walker in the array inside your header PHP will cause an error, easy fix is to make sure you change  'fallback_cb'       => 'WP_Bootstrap_Navwalker::fallback',
                'walker'            => new WP_Bootstrap_Navwalker()) 

to          'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
                'walker'            => new wp_bootstrap_navwalker()) 

Lots of newbs probably had this issue, hope this helps!

**Comment by pattonwebz** [comment]
There shouldn't be any issue with calling the walker class with capitals like `WP_Bootstrap_Navwalker()` as in PHP function and class names are not case sensitive. Also the call to instantiate the walker is not the call which would throw a file not found error. 

It sounds like seen happen is maybe this: #278. Do you think that is the same issue you had here?

**Comment by pattonwebz** [comment]
With no feedback from OP in some time I'm closing this issue out for now. If you continue to have this problem feel free to reopen this issue.
