### ISSUE TITLE
Incorrect example in the readme

### ISSUE THREAD

**Issue by hkirsman** [wp-bootstrap/wp-bootstrap-navwalker#305]
This is missing /
```
// Register Custom Navigation Walker
require_once get_template_directory() . 'wp-bootstrap-navwalker.php';
```

So it should be:
```
// Make the menu structure Bootstrap compatible.
require_once get_template_directory() . '/wp-bootstrap-navwalker.php';
```

**Comment by pattonwebz** [comment]
Hey @hkirsman I merged in the original PR with the fix for this. Thanks for reporting it and going to the effort to make that PR for it as well though, I appreciate the effort :)

Feel free to open more issues if you spot any more problems and PRs are always very welcomed :grinning:
