### ISSUE TITLE
Composer: Change from `"type": "wordpress-plugin"` to `"type": "library"`

### ISSUE THREAD

**Issue by pattonwebz** [wp-bootstrap/wp-bootstrap-navwalker#308]
Related to: #284 

It has been requested that we swap from a 'wordpress-plugin' to a 'library' type at packagist so that it installs into the /vendor/ folder (inside a theme) and not into the /wp-content/plugins/ directory (outside of the theme).

Including inside of a theme is probably the most common usage so I think this change is a good one to make.

My worry is for anyone else using this with composer already and making that change could break their setups :confused: 

Anyone have any thoughts?

**Comment by j-bull** [comment]
As this is a single class adding functionality, I'd expect it to land in the vendor folder, and composer to autoload it, making the class available within my PHP layer, hence starting #284. Conversely, if I install a plugin via the admin area, I expect it to appear in plugins.

Backtracking the path chosen is a little more tricky, and is probably dependent on the breadth of adoption and their usage.

**Comment by bhubbard** [comment]
The addition of composer was very recent, so I doubt too many users were using it. 

We used the plugin method as it was quick when we were developing it, but library probably makes more sense considering how most people use it. I think changing it is a good idea.

**Comment by pattonwebz** [comment]
I'll make this change in a future version and push it concurrently some other changes that are technically _breaking_ changes. Hopefully pushing a major version number would allow those using the current version to continue with it and have no problems, updating only if they chose.

**Comment by j-bull** [comment]
What about making a plugin version available via wpackagist, where things like this typically do install to the plugins or themes folder?

I appreciate that adds a bit more overhead to the code management.

**Comment by pattonwebz** [comment]
I'd be interested in making available both versions and letting users choose but unsure how I could do that. Maybe just by maintaining an extra branch with modified compose file that was for a plugin varient?

**Comment by j-bull** [comment]
I'd be inclined to handle it as a separate repo rather than branch as the two codebases aren't directly relatable, but that's just our workflow here. 

If you create the Wordpress plugin, zip it up and submit it to the [Wordpress plugins SVN](https://wordpress.org/plugins/developers/add/), it will after a short while appear on wpackagist and be available there. The packagist version carries on as is, less the plugin stuff.

**Comment by pattonwebz** [comment]
OK I get how it works. I'll think about this and how best to use it as a plugin so it can be available through wpackagist as well. Appreciate the advice @j-bull :)

**Comment by pattonwebz** [comment]
The package type was changed in master with commit https://github.com/wp-bootstrap/wp-bootstrap-navwalker/commit/88959a70e587b4a19717e864e197e8b7cef6ae0e. 

Going forward the package type is likely to remain `library` as that seems like it's the most useful for people.
