### ISSUE TITLE
Fatal error : Class 'WP_Bootstrap_Navwalker' not found in 'http://header.php on line 54

### ISSUE THREAD

**Issue by alsultant** [wp-bootstrap/wp-bootstrap-navwalker#311]
hello,
i can't access the wp_boostrap_navwlker it seem result not found on php..
thank you

**Comment by pattonwebz** [comment]
Closing as duplicate of #310

**Comment by alsultant** [comment]
if i change the '_' to '-' this will be the result..
Fatal error
: Call to undefined function Navwalker() in
header.php
on line
54

**Comment by alsultant** [comment]
what is the best function php code for nav walker?
im still didnt active my menus on appearance..


<?php

 // Register Custom Navigation Walker
 require_once('wp_bootstrap_navwalker.php');

// Add theme support to bootstrap navigation
function tam_theme_setup()
{
    register_nav_menus(array(
        'primary' => __('Primary Menu')
        ));
}
add_action('after_setup_theme', 'tam_theme_setup');

that my code but didnt work
