### ISSUE TITLE
WordPress: Improve Travis config and take advantage of all test features we can

### ISSUE THREAD

**Issue by pattonwebz** [wp-bootstrap/wp-bootstrap-navwalker#314]
Currently the Travis config fails. Previously it ran on an old base image (precise) which was depreciated in favour of a `trusty` based image. Builds now fail due to various reasons including missing packages for php 5.3 in trusty and probably some more dependencies.

I propose we take a look at the overall Travis config and rework it to fix issues and, if possible, improve it on it by taking advantage of newer features or more in-depth testing.

**Comment by pattonwebz** [comment]
https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

**Comment by szepeviktor** [comment]
May I fix this one?
The lack of tests makes any project unstable.

**Comment by pattonwebz** [comment]
Yes, please do :). This has been in my backlog for a while but not get around to looking for a proper fix.

I know that the existing settings can work if it's set to use the old `precise` image  (since there's no PHP 5.3 on `trusty`). Ideally I want to test on both old PHP 5.2/5.3 as well as on more common (5.6) and modern PHP too.

Whatever you can do to fix this will be very appreciated by myself and probably the other users too :D

**Comment by szepeviktor** [comment]
> Whatever you can do to fix this will be very appreciated

OK! :) $1 000 000

**Comment by szepeviktor** [comment]
Look like it is complete: https://travis-ci.org/szepeviktor/wp-bootstrap-navwalker

**Comment by szepeviktor** [comment]
😢 *Composer requires PHP 5.3.2+ to run.* - no 5.2 support...
https://getcomposer.org/doc/00-intro.md#system-requirements

**Comment by szepeviktor** [comment]
@pattonwebz Which issue is the next sought after?

**Comment by szepeviktor** [comment]
@pattonwebz Where could I contribute further?
