### ISSUE TITLE
Fix Multi Level Bootstrap Menu and Open on Mouse Hover

### ISSUE THREAD

**Issue by Serpentsoft** [wp-bootstrap/wp-bootstrap-navwalker#32]
Thanks for awesome work,
A. but there's an issue in multi level menu (it's not open) ..
replace line:
`if($args->has_children) { $class_names .= ' dropdown'; }`
with:
`if($args->has_children && $depth === 0) { $class_names .= ' dropdown'; } elseif($args->has_children && $depth > 0) { $class_names .= ' dropdown-submenu'; }`

B. Hover Dropdown Menu
To open menu on hover use (bootstrap-hover-dropdown.js) from ([CWSpear](https://github.com/CWSpear/twitter-bootstrap-hover-dropdown)) and ..
replace line:
`$atts['data-toggle'] = 'dropdown';`
with:
`$atts['data-hover'] = 'dropdown';`

and thanks again for your work and your time .. hope to help

**Comment by SideQuestDIY** [comment]
Hey @Serpentsoft, 

Thanks for the feedback! However, Bootstrap 3 does not officially support multi-level dropdowns so it was intentionally removed from this version of the class.  If you would like it use multi-level dropdowns I would suggest using Bootstrap 2.3.2 and the legacy version of the walker found here. 

https://gist.github.com/twittem/6358588
