### ISSUE TITLE
Not working with 2nd level submenu

### ISSUE THREAD

**Issue by royrakesh** [wp-bootstrap/wp-bootstrap-navwalker#321]
#### Steps to reproduce the issue:

Create a menu with multiple level link : http://prntscr.com/hab4fi

  Example:
           **1. Home**
               1.a) Home 1
               **1.b) Home 2**
                       1.b.i) Home 1 a
                        1.b.ii) Home 1 a
               1.c) Home 2
         2. About

#### What I expected:

caret  icon on **1. Home , 1.b) Home 2**

#### What happened instead:
   Only caret icon On **1. Home** and **1.b) Home 2** and  **1.b.ii) Home 1** a hidden
  image link : http://prntscr.com/hab41v

**Comment by pattonwebz** [comment]
Hey @royrakesh,

Additional levels of dropdown menu are not supported in Bootstrap 3 and have not been supported for a very long time. I do not think support was even provided when BS3 released in 2012 :( https://github.com/twbs/bootstrap/pull/6342#issuecomment-11594010

This walker works with the styles and scripts provided in Bootstrap Core and does not modify those in any way. Some substantial modifications are required to the core code (and some to the walker too) to make it support several levels of dropdown.

At the moment multiple levels of dropdown is not something I am pursuing with the master branch or the v4 branch of the walker. There are some other issues in the repo that were about this issue and do provide some insights into making that happen if you wanted to search some of the other threads.
