### ISSUE TITLE
Add a menu not working on v4

### ISSUE THREAD

**Issue by agentcdp** [wp-bootstrap/wp-bootstrap-navwalker#322]
#### Steps to reproduce the issue:
https://github.com/wp-bootstrap/wp-bootstrap-navwalker - <strong>Working Fine</strong>
https://github.com/wp-bootstrap/wp-bootstrap-navwalker/tree/v4 <strong> If there is no menus available in WP, Add a menu option not showing.
 </strong>
#### What I expected:
Add a Menu
#### What happened instead:
Nothing

**Comment by anfelsss** [comment]
dude can u send me the working code that you've made? cause I always encounter by ==> Fatal error: Class 'WP_Bootstrap_Navwalker' not found in C:\xampp\htdocs\red_circle\wp-content\themes\red_circle_theme\header.php on line 54

can u help me with that?

**Comment by pattonwebz** [comment]
@cdandapat I'll look into this when I have time, it sounds like the fallback function isn't working right for the v4 branch of the walker - I will fix that as soon as I can.

Note that the fallback link isn't required to reach the menu editor and set a menu for the location, you can reach it by going to the `Dashboard -> Appearance -> Menus` and set the menu that way.

@anfelsss There has been some issues with the code in the readme and in the github pages referencing the old filename when the filename was updated some time ago. 

What version of the walker are you using? The v4 version? Can you paste the code you have that includes the file along with the code you have that is for the `wp_nav_menu` function and I will take a look.

**Comment by anfelsss** [comment]
oh sorry its been fixed.... i just wrong when typing the functions.php ... I was type function.php without the s so thats the main problem... but anyways  I got another problem with the dropdown menu~~" 

Here is my header.php code :

[header.txt](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/files/1484684/header.txt)


Then this the functions.php code :

[functions.txt](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/files/1484685/functions.txt)


Hope u can help me with that problem. Cause I need to make a theme for wordpress , to fulfill my interview task.


anyways thanks for reply my massage.

and here's the wp-bootstrap-navwalker.php code that I use :

[navwalker.txt](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/files/1484693/navwalker.txt)

**Comment by pattonwebz** [comment]
@anfelsss could you clarify what the problem with the dropdown is?

I can think of 2 things that you might mean:

1. That the mobile toggle isn't working.
1. That the dropdowns only work with 1 level and has no _dropdown in dropdown_ ability.

are either of those things your problem?

**Comment by anfelsss** [comment]
2. The dropdowns only work with 1 level and has no _dropdown_ in _dropdown_ ability.

it just like when I moving the mouse cursor to the dropdown nav bar it wouldn't appear the pages that I've setup before. Even when i click the arrow icon it wouldn't appear anything. 

sorry if my word hard to be understand... cause my english isn't that good~~"

**Comment by pattonwebz** [comment]
I understand your english well :)

I'm sorry to say that this walker does not support more than 1 level of dropdown or opening the dropdown on hover. 

That isn't something which is imposed by the walker - it's set this way in the Bootstrap Core files on purpose. It's set that way because hover menus are not touch-friendly and having many nestled levels of dropdown is not mobile-friendly and also considered bad for accessibility reasons.

There are other issue threads in this repo that have some information about making this walker support more than 1 level and also about hover menus - use the search box at the top to try find those if you needed them.

Honestly though if you need to build a WP theme for an interview task them I would suggest you look at using a different walker (and perhaps not even use bootstrap if hover menus and multi-level dropdowns are a requirement for the coding challenge).

**Comment by anfelsss** [comment]
ah.... i see..... do u have any suggestion for the walker that I should use? 

By the way thanks for all your suggestion and ill try to find the other way :D

**Comment by anfelsss** [comment]
I got the navwalker that support the dropdown menu now!!! 

From here : https://github.com/geekofer/wp-bootstrap-navwalker-dropdown

thanks god!! hahahaha :D

**Comment by pattonwebz** [comment]
Fixed in https://github.com/wp-bootstrap/wp-bootstrap-navwalker/commit/d55fe1ab845cb44f1a408d7b8416747bdc948654

@cdandapat thanks for reporting this :+1:
