### ISSUE TITLE
Dropdown clicks not working

### ISSUE THREAD

**Issue by brunomiguel** [wp-bootstrap/wp-bootstrap-navwalker#33]
First of all, I don't know if this is something related to the theme I'm developing, your  script or any other thing.

I'm using this script to implement a Bootstrap theme in Wordpress. Everything works fine in the menus, except the click on the one that have submenus. When I click it, the "open" class is not added to the 'li class="dropdown"' part.

I have done everything according to the instructions in this repository, but this is not working. I can't tell if it's related to this or any Javascript bits.

Best regards;
Bruno Miguel

**Comment by brunomiguel** [comment]
Well, I made a precipitated decision of bug reporting here. Solved. (javascript bits).

**Comment by SideQuestDIY** [comment]
haha, Thats exactly what I was thinking it was but it seems you have beat me to it.

**Comment by brunomiguel** [comment]
I spent a few hours with my head around it to figure out the problem: I was using simple HTML to call the javascript files, when I should also use the Wordpress functions to state that the *.js files are in the theme folder. I didn't developed anything for Wordpress for a long time; I'm rusty.

Thanks for this excellent script! :smile: :+1:

**Comment by SideQuestDIY** [comment]
I definitely know tat feeling. I'm glad you found it useful and if you have any other questions feel free to ask. :)
