### ISSUE TITLE
[v4] Fix special class field processing

### ISSUE THREAD

**Issue by szepeviktor** [wp-bootstrap/wp-bootstrap-navwalker#332]
See https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/287#issuecomment-348567178

**Comment by pattonwebz** [comment]
Hey @szepeviktor,

I don't mean to be a nuisance as I know I asked if you could look at this but I had made some work towards handling this one in recent `v4` branch updates.

If you have made any progress on this we could compare both methods to see which approach is best before I finalize the v4 version of the walker to go into master.

**Comment by pattonwebz** [comment]
I put an improved method of handling these in the v4 branch which is in master just now. If you have a better method to handle these reopen the issue :smile:
