### ISSUE TITLE
Is version 4 in maintenance?

### ISSUE THREAD

**Issue by ZhangChengLin** [wp-bootstrap/wp-bootstrap-navwalker#334]
#### Steps to reproduce the issue:
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

#### What I expected:
More energy into the bootstrap 4 version
bootstrap beta2 is a drop-down menu of this format, which is not the case with v4! ! !
https://getbootstrap.com/docs/4.0/components/navbar/

#### What happened instead:
line:53
            $output .= "\n$indent<ul role=\"menu\" class=\" dropdown-menu\" " . $labledby . ">\n";

**Comment by pattonwebz** [comment]
Version 4 is not under heavy development at this time however I am aware of the ability to now use only a `<div>` as the container instead of a list.

I chose to retain the list method as I feel it's more semantically correct. I asked several people involved with WP accessibility and WCAG guidelines and they tend to agree that lists are the prefered format.

**Comment by pattonwebz** [comment]
@zhang-chenglin with Bootstrap v4.0.0 in stable release I have spent a lot more time working on the v4 version of the walker. If you are still interested in seeing more energy going into the updated version feel free to open up more issues :)

Closing this one out as full development focus is on the v4 version.
