### ISSUE TITLE
Fix Fontawesome 5 Styles

### ISSUE THREAD

**Issue by Whornat** [wp-bootstrap/wp-bootstrap-navwalker#335]
Hi,
Great walker! I using FontAwesome 5 and I found that additional class "light, bold, regular" (fas, far, ect.) were not displayed on the <i> element.

For information, I modified the code as well.
Have a good day

line 93 : 
if ( 'fas' === $class || 'far' === $class || 'fal' === $class || 'fab' === $class ) {
					$icon_class_string .= $class . ' ';
					unset( $classes[ $key ] );

**Comment by pattonwebz** [comment]
Hey @Whornat,

Thanks for pointing out the modifications required to get FA5 working with this. I have not yet used it but I've seen a lot of people talking saying it's a nice improvement for many aspects.

Will look at adding in full FA5 support as soon as I can get some free time this week.

**Comment by pattonwebz** [comment]
I have full working support for FA5 in the updated `v4` branch of the walker :)

Closing this issue now - with the caveat that this is not solved in the v3 branch of the walker and is likely never going to be unless there is a lot of people needing it for older projects.
