### ISSUE TITLE
more then 2 levels of depths

### ISSUE THREAD

**Issue by Adamsess** [wp-bootstrap/wp-bootstrap-navwalker#336]
Hello,

Everything works fine, except when I have more then 2 levels in the menu.
Is there an option for depth =>0
?
Thanks

**Comment by pattonwebz** [comment]
Hey @Adamsess,

There isn't an option for infinite depth or depths greater than 2.

Sadly Bootstrap styles and scripts are not written to use more than a single level of dropdown. This walker doesn't add any styles or scripts of it's own to handle the extra menu levels.
