### ISSUE TITLE
Change default link from '' to '#'

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#345]
https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/6620271ea1eee4adfad97795d03daa0f219b563b/class-wp-bootstrap-navwalker.php#L192

If this line is changed so that the default href is '#' that will prevent unset links from redirecting to the homepage, instead doing nothing.

**Comment by pattonwebz** [comment]
Hey @evandentremont,

Thanks for pointing this out, will fix this and bundle it for next release. If you spot any more things feel free to open more issues. Bug reports always appreciated :)
