### ISSUE TITLE
Implement Composer Autoloading

### ISSUE THREAD

**Issue by vpillinger** [wp-bootstrap/wp-bootstrap-navwalker#346]
#### Steps to reproduce the issue:
Install package via composer.
#### What I expected:
Composer to auto-load the package.
#### What happened instead:
Composer did not auto-load the package, requiring me to manually import it.

The fix for this is to add the following to composer.json. Please add in both v3 and v4 branches.

 "autoload": {
    "files": ["wp-bootstrap-navwalker.php"]
 },

**Comment by pattonwebz** [comment]
Would the change to the compose.json file in this PR change it to work like what you are after? https://github.com/pattonwebz/wp-bootstrap-navwalker/blob/ccd04391f8f2653b97ed4ec02dd9fd1d86e6f150/composer.json#L19-L21

**Comment by pattonwebz** [comment]
@vpillinger Hey man, not sure if you saw my reply because I didn't mention you when posting it. I have added what I think is the correct lines to the `composer.json` file but if you could confirm that for me before I merge and backport the changes that would be awesome.

Thanks for pointing this out :)

**Comment by vpillinger** [comment]
@pattonwebz Yes this is correct. 

I guess I should also mention that any consuming developer will have to ensure that they autoload the wordpress nav walker class as well (or get an error about the class not existing).

This solves what I needed without having to manually edit the package... thanks!

**Comment by pattonwebz** [comment]
Hey again @vpillinger, 

I merged this into v3 and v4 branches. If you have a little spare time do you think you would be able to create a PR for master branch and add a note about using the walker with composer? Or even just post some basic notes here and I would add them to the readme?

I am not familiar with setting up or configuring composer packages beyond just running the install command whenever a project's instructions tell me too :stuck_out_tongue:. Any guidance on the best set of general purpose instructions to present in the readme would be very appreciated.

**Comment by vpillinger** [comment]
Hi, For the v3 branch I noticed that there is an error caused by the class name being incorrect. 

You import ["class-wp-bootstrap-navwalker.php"] but in v3 branch the file is actually ["wp-bootstrap-navwalker.php"]. This filename seems to have changed between branches. My apologies that I did not catch this sooner. I will make a pull request with this fix included as well as some info in the Readme about using composer later today.

**Comment by pattonwebz** [comment]
Ahh yes... a copy/paste oversight on my part sadly and I realize the mistake now that you point it out.

And thank you for offering to fix and provide some docs about using things with composer. That has been on my todo list for quite some time but I never got around to it. The contribution will be a welcome addition and very much appreciated :smile:
