### ISSUE TITLE
Dividers

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#35]
The word "Divider" has to be in the "Title Attribute" field or else it won't work.
The code seems to say the same thing:

Line 49: <code>$item->attr_title, 'divider'</code>

Therefore, the documents should say:

...a Link Text or Title Attribute of divider...

**Comment by SideQuestDIY** [comment]
Good eye! 

I removed the `$item->title, 'divider'` code when updating the class for Bootstrap 3.0 in an effort to make the syntax match for all extra elements. I do like being able to simple do this by the link text so I added in back in and the current documentation should now be valid again. 

:)

**Comment by ghost** [comment]
You could have kept it like it was, but change the document/help file...

**Comment by SideQuestDIY** [comment]
I know, but I chose to do it the other way as that is how I use it personally. lol
