### ISSUE TITLE
Github Description References BS3

### ISSUE THREAD

**Issue by lkhedlund** [wp-bootstrap/wp-bootstrap-navwalker#355]
I noticed that the Github description references Bootstrap 3 -- until today I've avoided this repo because I didn't know that 4 was supported. Just a heads up :).

> A custom WordPress nav walker class to fully implement the Twitter **Bootstrap 3.0+** navigation style in a custom theme using the WordPress built in menu manager. https://wp-bootstrap.github.io/wp-boo…

**Comment by pattonwebz** [comment]
Hey @lkhedlund,

I appreciate you pointing this out, I did not realise it would be an issue. I've updated the description to show that the project supports Bootstrap 4.

> A custom WordPress nav walker class to fully implement the Twitter Bootstrap 4.0+ navigation style (v3-branch available for Bootstrap 3) in a custom theme using the WordPress built in menu manager. 

Thanks for highlighting this, it is very useful to know how things are perceived when people land on the project page for the first time :smile:

**Comment by lkhedlund** [comment]
No problem! Happy to help out :)
