### ISSUE TITLE
Addition of auto-load breaking in default composer/word-press setups

### ISSUE THREAD

**Issue by vpillinger** [wp-bootstrap/wp-bootstrap-navwalker#356]
#### Steps to reproduce the issue:
Start with bedrock installation of WordPress (or other composer based installation)
Install package via composer
Load Site

#### What I expected:
Site continues with no change

#### What happened instead:
Site throws error "cannot find class Walker_Nav_Menu" because bootstrap core is not yet loaded

**The solution** here is to spin off the addition of  "autoload" lines in the composer.json into its own branch so people who want to use it can, without breaking the package for everyone else. Or you can just remove it entirely since its probably not adding that much benefit to really justify two branches.

So when I had originally asked for the addition of auto-loading for this, I was using composer in such a way that delayed autoloading until after core WP classes were loaded. What I did not realize is that this causes the package to break in many common setups like Bedrock.

Sorry for wasting your time with the original request that just ended up causing issues for other people.

**Comment by pattonwebz** [comment]
@vpillinger Hey again,

Don't worry about causing me to waste time, I appreciated the advice you gave and trust you gave it with best intentions. I also appreciate you coming back and informing me of the problem before anyone else had ran into the issue. 

I will look to drop the autoload in the coming days but lets keep this issue open for a little while to see if anyone can chime in with their use cases for autoload or how best to implement it for this package.
