### ISSUE TITLE
question: dropdown menu parent link

### ISSUE THREAD

**Issue by rehmulus** [wp-bootstrap/wp-bootstrap-navwalker#358]
Hey,
Is there a way to get the parent's original link instead of 'href="#"'?
I want to use it as a hoverable dropdown menu while being able to click the parent.

Thank you!

**Comment by pattonwebz** [comment]
Hey @rehmulus,

The walker does not have a way built in to toggle the output of those links. They are `#`ed hout for a reason and that is for better accessibility and touch screen device support.

There are some other issues threads that are closed in this repo that can explain how to do what you need though. Maybe start with this issue and see if it helps you get what you need done https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/351.

Good luck!
