### ISSUE TITLE
Top level menu items only.

### ISSUE THREAD

**Issue by Becca800** [wp-bootstrap/wp-bootstrap-navwalker#365]
#### Steps to reproduce the issue:
I am not able to set the menu to show only top level menu items (array =1). On a desktop, the screen minimized to mobile size displays the menu correctly, only showing the top menu items. But on the actual phone it does not.
[custom-menus.php.txt](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/files/1892107/custom-menus.php.txt)

#### What I expected:
Expected mobile menu to only show top level

#### What happened instead:
Shows correctly on minimized desktop, but not actual mobile.

**Comment by pattonwebz** [comment]
Hey @Becca800,

I am having a little trouble visualising what you mean by it not showing only the top level items in mobile. Are you saying that on mobile items that are contained within the `dropdowns` (level 2) of the menu are all toggled open by default? Or is it a different problem?

Maybe a screenshot of the broken behavior on mobile might help if you can obtain one as I cannot quite figure out what you mean.

**Comment by Becca800** [comment]
Sorry. I'm a horrible explainer of things. On a mobile, all items were toggled by default.  However, I was able to fix things. It was not this piece of code, but the CSS I royally screwed up. My apologies.

**Comment by pattonwebz** [comment]
Hey again @Becca800,

There is no need to apologize for posting the issue, I'm always happy to help diagnose things if my eyes would be of assistance. And you did managed to explain things well, I just got myself confused about it lol

I am happy to hear that you figured it out and got a working solution in place quickly :D
