### ISSUE TITLE
Mega Menu creation option?

### ISSUE THREAD

**Issue by NICrichard** [wp-bootstrap/wp-bootstrap-navwalker#366]
Is this possible using this navwalker?

**Comment by pattonwebz** [comment]
Hey @NICrichard,

Unfortunately this walker does not implement any kind of options to enable a mega menu on it's own. 

There are filters provided in the walker that may make it possible to create a mega menu with it but I think that extending the `WP_Bootstrap_Navwalker` class or using it as a reference point then adding your own support might be a more robust solution. Sorry I can't be of more help.
