### ISSUE TITLE
CSS Classes set for menu item dont work.  

### ISSUE THREAD

**Issue by pierrerocket** [wp-bootstrap/wp-bootstrap-navwalker#368]
#### Steps to reproduce the issue:

When going to appearances > menu and setting custom css classes on a menu item they are not applied to the <li> on the frontend.

#### What I expected:

The class to be appended to the li of the menu item

**Comment by pierrerocket** [comment]
I'm apparently super unobservant.  It was there.

**Comment by pattonwebz** [comment]
No worries, I'm happy you figured it out quickly :)

Did you miss the classes because I split out icon and link mod classes to move them into the `<a>` tag?
