### ISSUE TITLE
Fatal Error on Wordpress

### ISSUE THREAD

**Issue by SlamDuncan8** [wp-bootstrap/wp-bootstrap-navwalker#372]
Class 'WP_Bootstrap_Navwalker' not found in "...themes/understrap-child/header.php" on line 93

#### What happened instead: Fatal error

				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse justify-content-end',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>

"Class 'WP_Bootstrap_Navwalker' not found"

How do I fix this?

**Comment by SlamDuncan8** [comment]
Found the answer in another issue that was posted. I'm sorry - I didn't find it on my initial search.

**Comment by pattonwebz** [comment]
Hey @SlamDuncan8,

No need to apologize. I am glad you got a fix for it :) 

I am curious what is up that caused the fatal error, is there something in the documentation that directed you with the wrong instructions? If it's something up with the documentation let me know and I'll fix it :)

**Comment by SlamDuncan8** [comment]
We update our WP site intermittently, so today I did the theme upgrade. In line 93 of the theme header, it had, 
'walker'          => new WP_Bootstrap_Navwalker(),
instead of 
'walker'          => new understrap_WP_Bootstrap_Navwalker(),

I'm not very savvy, so I'm probably not giving you a good answer. But changing line 93 to include understrap did the trick.

**Comment by pattonwebz** [comment]
Ahh ok I understand. The author of your theme changed something at some point between the last time you updated and now. That change caused it to break. And you fixed it by changing that line back to what it used to be. That makes sense :)

Do you mind if I ask what theme it is that you are using that has the problem? This project does not share themes (it is just a piece of helper software to create menus) but I could reach out to the author of your theme and see if I could help them with getting a good integration that won't cause fatal errors for their users on update.
