### ISSUE TITLE
Menu text color

### ISSUE THREAD

**Issue by angeidheal** [wp-bootstrap/wp-bootstrap-navwalker#376]
I've added a background color to my navbar and want to change the text color to white.

I've add the following to my CSS file but it doesn't change the color. Adding it to the aditional CSS section in the Wordpress customiser does change the color though.

.navbar-default .navbar-brand {
    color: #fff;
}

.navbar-default .navbar-nav > li > a {
    color: #fff;
}

**Comment by erhandemirci** [comment]
in your style file put :

  .collapse ul li a span
    {
        color:F7FBC9;
    }
