### ISSUE TITLE
Depth parameter not working as worpdress documentation says

### ISSUE THREAD

**Issue by fab120** [wp-bootstrap/wp-bootstrap-navwalker#384]
#### Steps to reproduce the issue:
If you don't specify depth param equal to 2, dropdown menus won't work correctly.
E.g.:
```
wp_nav_menu( array(
	'theme_location'  => 'primary',
	'container'       => 'div',
	'container_class' => 'collapse navbar-collapse',
	'container_id'    => 'bs-example-navbar-collapse-1',
	'menu_class'      => 'navbar-nav mr-auto',
	'fallback_cb'     => 'WP_Bootstrap_Navwalker::fallback',
	'walker'          => new WP_Bootstrap_Navwalker(),
) );
```

#### What I expected:
Dropdowns working without any problem.

#### What happened instead:
Dropdowns are not working because the `data-toggle="dropdown"` and other related attributes are not generated.

As stated in the WordPress documentation for function [wp_nav_menu()](https://developer.wordpress.org/reference/functions/wp_nav_menu/):
```
depth
(int) How many levels of the hierarchy are to be included. 0 means all. Default 0.
```
the default value for depth parameter is 0 and it means all levels.
So if i don't specify a depth, dropdowns have to work.

**Comment by IanDelMar** [comment]
Closing this issue as the current master branch no longer restricts the depth to be strictly positive.
