### ISSUE TITLE
Make <a> menu item span full heigth of parent item 

### ISSUE THREAD

**Issue by adrisantos07** [wp-bootstrap/wp-bootstrap-navwalker#386]
Hi,
I'm using the nav walker which comes bundled with the underscores theme. 
I have modified css for the elements in the navbar n to make the  navbarnavdropdow items heigth equal to the  navbar. The issue now is that the `<a>` item's height does not span the full heigth of the parent. To make it span the full heigth of it's parent and still have  the text vertically centered, I would like to wrap it in a `div`, so I can make this `div` a flex container and set `text-align: center` on it.

How can I modify the navwalker class to wrap every `li` inside a `div`, or is there any other solution that does not imply modifying the html?

I attach pictures below. Thanks, any help is much appreciated.

![image](https://user-images.githubusercontent.com/29485401/42343069-3559e39e-8098-11e8-920b-03e13d07c428.png)

![image](https://user-images.githubusercontent.com/29485401/42343135-625c1a56-8098-11e8-8d4a-cbdd42467f34.png)

![image](https://user-images.githubusercontent.com/29485401/42343123-57de7fe2-8098-11e8-959f-3db0086f3309.png)

**Comment by pattonwebz** [comment]
Hi @adrisantos07, the walker does not yet have a way to easily add in a different wrapper here but I have recently spent soem time making some changes that could allow this. 

It is not yet completed however the plan is to add filters to all the various places they are currently missing - which would let you filter in the `div` you want around the link. If you ping me tomorrow or Sunday and remind me I will look at how to make this happen for you :)

**Comment by WebDragon** [comment]
Not for nothing but why not make the .nav li {display: flex;
flex-direction: row; justify-content: center; align-items: center; } and
leave it at that ? (with adjustments for your navbar height, of course)

**Comment by adrisantos07** [comment]
@WebDragon I tried your stuff, actually thats what I am using now, however using that the <a> item does not expand the full height of the navbar.

**Comment by adrisantos07** [comment]
@pattonwebz I figured out an easier solution. I am not sure the one I initially posted works...
If you can wrap the text inside each `<a>` in a `<span>` , then we can set the `<li>` to `align-items: stretch;` , and the `<a> display:flex; align-items:center;` and it works as expected, the `<a>` item spans the full navbar height and the text is centered.
I can share it in a codepen if you need it.
Thanks!

**Comment by adrisantos07** [comment]
I figured out how to wrap each `<a>` into a `<span>`, and now it is working as expected.
Modified these 2 lines in class-wp-bootstrap-navwalker.php 
Line 233: `$item_output .= '<a' . $attributes . '><span>';`
Line 284: `$item_output .= '</span></a>';`
