### ISSUE TITLE
Parent menu items clickable - how to?

### ISSUE THREAD

**Issue by marekka** [wp-bootstrap/wp-bootstrap-navwalker#388]
Hi, I've found it easy to swap $atts['href']   		= '#'; with a url, but it's still not opening the link

How to make the parent link clickable and make the subitems open on hover?

**Comment by CornelioDev** [comment]
I have the same problem and any kind of solution on the web. The temporary solition i have done is to put the parent as a sub item :/

**Comment by christiaanbruijnes** [comment]
I wrote an answer here: #398

**Comment by pattonwebz** [comment]
Solution for this was kindly posted by @christiaanbruijnes in #398. I'm closing this issue out as there is a resolution available that I think is acceptable but feel free to reopen this if you think something else could be done.
