### ISSUE TITLE
How can I inject before last closing tag of container?

### ISSUE THREAD

**Issue by codyburleson** [wp-bootstrap/wp-bootstrap-navwalker#389]
In order to get a search widget in the top-right of the header navbar, it needs to go before the closing tag of the container generated by the navwalker. Is it possible in some way now to use a param to inject with `get_search_form(true)` or `get_search_form(false)`, foe example?

**Comment by pattonwebz** [comment]
For this one you should be able to just not output a container via `wp_nav_menu()` by passing something like `false` in the args for `container` like so:

```
wp_nav_menu( array(
            'theme_location'    => 'primary',
            'depth'             => 2,
            'container'         => 'false',
            'menu_class'        => 'nav navbar-nav',
            'fallback_cb'       => 'WP_Bootstrap_Navwalker::fallback',
            'walker'            => new WP_Bootstrap_Navwalker(),
        ) );
```

And wrapping it yourself in whatever container you want allowing you to add anything before or after it :)
