### ISSUE TITLE
Multilevel menu support

### ISSUE THREAD

**Issue by RichForever** [wp-bootstrap/wp-bootstrap-navwalker#391]
Is it any way to create multilevel menu support? I want to create menu like this

<ul>
<li>Menu item
<ul><li>sub item</li><ul><li>sub sub item</li></ul></ul>
</li>

**Comment by MWDelaney** [comment]
Bootstrap itself doesn’t support multi-level dropdowns so adding them here would seem to be out of scope of this tool.

**Comment by PaolaMaglia** [comment]
Goodmorning, 
I've the same problem of RichForever.
I can't tell to my client that Bootstrap doesn't support multilevel dropdown, 'cause he's not a developer and he can't understand it.
Is there a way to get around the problem?
Thanks

**Comment by pattonwebz** [comment]
@PaolaMaglia there are some other issues in this repo that have various ideas and methods for enabling additional levels. I have not tried any of them myself but I have seen comments from others saying thanks for sometimes so I expect there are enough notes (sadly they are spread through lots of different issue threads) to make it happen.

**Comment by pattonwebz** [comment]
@RichForever there is not a way to make it happen using this walker and bootstrap - without modifications. Have a search through other older issues though as I know there are notes in there that have details about how to make it happen.

**Comment by schoenj** [comment]
Good evening,
as @pattonwebz already mentioned, that this is not possible without any modifications.
But for those, who need a fast fix, i fixed it for me with the Github project(bootstrapthemesco/bootstrap-4-multi-dropdown-navbar) and six additional lines of code.

In the start_el mehtod, i copied the first if statement and modified it like that
`}elseif ( isset( $args->has_children ) && $args->has_children && 0 < $depth && $args->depth > 1 ) {
				$atts['href']          = '#';
				$atts['data-toggle']   = 'dropdown';
				$atts['aria-haspopup'] = 'true';
				$atts['aria-expanded'] = 'false';
				$atts['class']         = 'dropdown-toggle dropdown-item';
				$atts['id']            = 'menu-item-dropdown-' . $item->ID;`

I'm sure you could write that more beautiful.

**Comment by ikender** [comment]
Wilt a little css and js you can do this (change depth in your `wp_nav_menu()` call to greater than 2 (I try to limit mine to 3, but you can go more)

for your css add
```
/* multilevel navigation */
.dropdown-submenu { position: relative; }
.dropdown-submenu .dropdown-menu { top: 0; left: 95%; margin-top: -1px; }
```

for your javascript add
```
// dropdown multilevel
$('.dropdown-menu > li > .dropdown-menu').parent().addClass('dropdown-submenu').find(' > .dropdown-item').attr('href', 'javascript:;').addClass('dropdown-toggle');
  $('.dropdown-submenu > a').on("click", function(e) {
    var dropdown = $(this).parent().find(' > .show');
    $('.dropdown-submenu .dropdown-menu').not(dropdown).removeClass('show');
    $(this).next('.dropdown-menu').toggleClass('show');
    e.stopPropagation();
  });

  // hide all open menus if the parent closes
  $('.dropdown').on("hidden.bs.dropdown", function() {
    $('.dropdown-menu.show').removeClass('show');
  });
```

**Comment by reginaldoradel** [comment]
> Wilt a little css and js you can do this (change depth in your `wp_nav_menu()` call to greater than 2 (I try to limit mine to 3, but you can go more)
> 
> for your css add
> 
> ```
> /* multilevel navigation */
> .dropdown-submenu { position: relative; }
> .dropdown-submenu .dropdown-menu { top: 0; left: 95%; margin-top: -1px; }
> ```
> 
> for your javascript add
> 
> ```
> // dropdown multilevel
> $('.dropdown-menu > li > .dropdown-menu').parent().addClass('dropdown-submenu').find(' > .dropdown-item').attr('href', 'javascript:;').addClass('dropdown-toggle');
>   $('.dropdown-submenu > a').on("click", function(e) {
>     var dropdown = $(this).parent().find(' > .show');
>     $('.dropdown-submenu .dropdown-menu').not(dropdown).removeClass('show');
>     $(this).next('.dropdown-menu').toggleClass('show');
>     e.stopPropagation();
>   });
> 
>   // hide all open menus if the parent closes
>   $('.dropdown').on("hidden.bs.dropdown", function() {
>     $('.dropdown-menu.show').removeClass('show');
>   });
> ```

Working on WordPress 5.3 👍

**Comment by beshealthcare** [comment]
Has anyone experienced as issue with the above fix whereby if you have more than one top level drop down, if you click the first drop down then go to click another top level drop down, the original stays open? This is my current issue.

**Comment by beshealthcare** [comment]
I'm having an issue with the above script where by I have multiple drop down menus. If I open one, I cannot open another without clicking somewhere else on the page an input or the background first.
