### ISSUE TITLE
Top level menu of subnav are not clickable

### ISSUE THREAD

**Issue by HendricksenDesign** [wp-bootstrap/wp-bootstrap-navwalker#398]
Top level menu of subnav are not clickable and replace it with a # instead. Is there a fix to it?

**Comment by christiaanbruijnes** [comment]
Find `$atts['href'] = '#';` and replace it with `$atts['href'] = ! empty( $item->url ) ? $item->url : '#';`.

You also need some jQuery:

`$('.dropdown-toggle').click(function() {
        if ($(window).width() > 768)
            if ($(this).next('.dropdown-menu').is(':visible'))
                window.location = $(this).attr('href');
    });`

**Comment by squarepixel** [comment]
If you do that since the bootstrap menu is click to activate, will you ever get to the dropdown menu?

**Comment by reb197** [comment]
@squarepixel, the fix suggested by @christiaanbruijnes opens the dropdown menu on the first click, and then navigates to the top-level page on the second click (i.e. when the sub-menu is open clicking the item behaves differently). An alternative approach would be a [split button](https://getbootstrap.com/docs/4.1/components/dropdowns/#split-button) but that will require some additional coding.

**Comment by owebudde** [comment]
> Find `$atts['href'] = '#';` and replace it with `$atts['href'] = ! empty( $item->url ) ? $item->url : '#';`.
> 
> You also need some jQuery:
> 
> `$('.dropdown-toggle').click(function() { if ($(window).width() > 768) if ($(this).next('.dropdown-menu').is(':visible')) window.location = $(this).attr('href'); });`

Thanks for the advice. Adds the url fine, but as for menu item, it only opens the dropdown. Any advice?

**Comment by pattonwebz** [comment]
@inksea did you include the jquery code in the frontend as well as making the change to the walker? You may need to change all of the `$` in the snippet to `jQuery` depending on your inclusion method.

Since this issue has a posted solution (that is quite nice) I am going to close this issue out but feel free to reopen it or make a new one if anyone needs to.
