### ISSUE TITLE
Missing semicolon in v3.1.0 wp-bootstrap-navwalker.php

### ISSUE THREAD

**Issue by achilles283** [wp-bootstrap/wp-bootstrap-navwalker#399]
Using composer to install and getting a parse error due to the missing semi-colon on line 149:

https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/d590c37dcbde17b8f5cbd3b19309d76d844fd49c/wp-bootstrap-navwalker.php#L149

**Comment by pattonwebz** [comment]
Hey, thanks for reporting this. I pushed out a bugfix release of v3.1.1 to solve this.
