### ISSUE TITLE
Not Working on the Online Server but work well on localhost

### ISSUE THREAD

**Issue by rudevils** [wp-bootstrap/wp-bootstrap-navwalker#4]
Hi Edward, sorry to disturb your day,
I'm using your walker function to my  wp themes, i'ts working well on the local server.
But sadly it's not working when I make it online ( http://greenlotresidence.com ) 
Where did i go wrong ?

**Comment by rudevils** [comment]
Ups sorry man, i forgot to upload my new footer.php, it's working now thx

**Comment by SideQuestDIY** [comment]
No problem man, just stilling down to work now over here in Canada.

The site looks awesome, its great to see it in use!
