### ISSUE TITLE
Search form

### ISSUE THREAD

**Issue by dovanquynhz** [wp-bootstrap/wp-bootstrap-navwalker#409]
Can't use search form inline with menu like example Bootstrap 4
Link here: https://getbootstrap.com/docs/4.2/components/navbar/

**Comment by pattonwebz** [comment]
You can do this. Just place the form outside of the container with menu items but inside the main nav container.

You can see how I did this before in this theme: https://github.com/pattonwebz/best-reloaded-bootstrap-theme/
