### ISSUE TITLE
Uncaught Error: Class 'WP_Bootstrap_Navwalker' not found

### ISSUE THREAD

**Issue by SalmaTouati** [wp-bootstrap/wp-bootstrap-navwalker#414]

**Comment by smrtrnx** [comment]
did you add this line in your menu 'walker' => new wp_bootstrap_navwalker())

it should be something like this:

	<?php
		wp_nav_menu( array(
		'menu'              => 'primary',
		'theme_location'    => 'primary',
		'depth'             =>  4,
		'container'         => 'div',
		'container_id'      => 'bs-example-navbar-collapse-1',
		'menu_class'        => 'navbar-nav mr-auto',
		'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
		'walker'            => new wp_bootstrap_navwalker())
		);
	?>

**Comment by pattonwebz** [comment]
Hi @SalmaTouati,

That error indicates that the navwalker class doesn't exist in your runtime. That usually means that you have not `require`d the file in your theme or something breaks before it gets included. 

If you could share the code you use to add the class and the code you call to get the menu that would be great.

**Comment by pattonwebz** [comment]
Since I have not heard a reply here I am closing this issue for now. If you continue to have this issue and still are not able to resolve it then please reopen the ticket or create a fresh one if there seems to be a different problem.

**Comment by SalmaTouati** [comment]
I will try again thanks

Le 28 févr. 2019 17:23, "William Patton" <notifications@github.com> a
écrit :

**Comment by pattonwebz** [comment]
Let me know how I can help when you do @SalmaTouati :)

Reopening the issue.

**Comment by mikaykun** [comment]
@pattonwebz This issue can be closed again.
