### ISSUE TITLE
Custom navmenu item not getting the active class

### ISSUE THREAD

**Issue by rarestamaian** [wp-bootstrap/wp-bootstrap-navwalker#416]
#### Steps to reproduce the issue:
So besides the regular navmenu, using navwalker, I added a custom navmenu item using add_filter('wp_nav_menu_items', 'myFunctionName', 10, 2); In my case it's a mincart. The thing is that this item is not created using the navwalker.
#### What I expected:
I thought that it would behave like the other elements- when I click it, it recieves the class "active"
#### What happened instead:
The custom elements doesn't get the active class when clicked.

**Comment by pattonwebz** [comment]
Hmmm I am not certain how I can act on the items added via that filter if the walker does not already. Will look into support for this in the upcoming version.

**Comment by rarestamaian** [comment]
All right. It doesn't bother me, it was just something that I noticed. Thanks a lot anyways. And have a nice day!

**Comment by pattonwebz** [comment]
I will still look into this, it might be something I am doing wrong. Seems like something that should be supported in the walker - I just need to look into where best to add it and how.

And I hope you have a great day too :)

**Comment by IanDelMar** [comment]
@xrareselX , @pattonwebz `wp_nav_menu_items` is applied after the the menu items have been walked, therefor items added via a filter added to `wp_nav_menu_items` are not accessible to the walker. See https://core.trac.wordpress.org/browser/tags/5.6/src/wp-includes/nav-menu-template.php#L228 and  https://core.trac.wordpress.org/browser/tags/5.6/src/wp-includes/nav-menu-template.php#L259. 

I can't imagine a situation where this would be needed. There are 2 types of nav links: 1) links to a page on the same site and 2) links to another site. If 1) applies the page can be added to the menu via the menu editor, will be walked and receives the active class if clicked. If 2) applies the page will per definition never become active; once you click it you leave the site.
If by 'mincart' you mean a mini cart which is a modal popping up when you click it then you're not leaving the current page and again per definition the active state of any page won't change. @xrareselX is there something I am not aware of? Why can't you add the item via the menu editor?

**Comment by IanDelMar** [comment]
As outlined above this is beyond the scope of the project.

**Comment by IanDelMar** [comment]
@xrareselX It's been a long time but this issue might be of interest to you if you need to add the said nav item via code: #519
