### ISSUE TITLE
current_menu_ancestor not being added with custom post types or blog posts

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#419]
When viewing a blog post, or a single custom post type post, there are no `current_menu_ancestor` or similar classes to identify the parent menu items.

Thesea are not native Wordpress classes (for some reason, so could these be added in?, or at least some form of including the Bootstrap `.active` class when the menu item is a parent item for either a post, or custom post type?

**Comment by ghost** [comment]
It seems like this is probably an issue with Wordpress core, as I've found a issue in the Trac that perfectly seems to explain this behaviour, so there may not need anything doing to this.

https://core.trac.wordpress.org/ticket/38486

**Comment by pattonwebz** [comment]
I see the ticket your talking about. Grabbed it and will look into it as soon as I can there :)

**Comment by ghost** [comment]
Wow that was incredibly lucky for you to also b able to action stuff in the WP Trac.

I would love to be able to make PRs for WP.

Thanks for looking further into this.

**Comment by pattonwebz** [comment]
Right there is the beauty of WordPress development process and open source in general - anyone can action things :)

I can do it and so can you. Anyone that has the knowledge to write the code can contribute the patches and have them committed to core. Anyone with insight into a problem or enhancement can post their thoughts in comments. Anybody that sees something they don't like can open tickets to get it changed.

Open source software really is a wonderful, wonderful thing :)

**Comment by ghost** [comment]
Hey, just wondering if there's any progress? I can't see anything on the Trac ticket, but wondering if anything's got closer?

I don't think anyone else has solved this, and it still seems to be an issue with the current release of the navwalker.

Any ideas for the time being?

So for current pages, the classes 'current_page_item' and 'active' are added (the former is default WP I believe, and the latter is navwalker, is this correct?)

**Comment by IanDelMar** [comment]
@leecollings That's correct! The class `active` is added by the walker and the class `current_page_item` is a default WP [menu item class](https://developer.wordpress.org/reference/functions/wp_nav_menu/#menu-item-css-classes).

It seems as this has been resolved. I tested it using WP 5.6. A category menu item receives the class `active` when viewing a post of that category.

I consider this fixed. Please, feel free to re-open the issue.
