### ISSUE TITLE
navbar-right

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#42]
Hi, nice work, thanks for sharing! I was wondering if there was a way to make a link with ul class: navbar-right? Kinda like a Login link flush-right...

http://getbootstrap.com/components/#navbar-default

Thanks

**Comment by ghost** [comment]
I think I figured it out...

I removed the "container" and "container_class" on 2 objects (primary_nav, user_nav), wrapped both inside the div class "collapse navbar-collapse navbar-ex1-collapse" and gave the user_nav a "menu_class" of "nav navbar-nav navbar-right" ! Awesome!

**Comment by SideQuestDIY** [comment]
Thats exactly how I would have done it! 

The `container_class` and `menu_class` attributes are extremely powerful, and allow you to use the walker for almost any application you need a list for. For instance I use it for single dropdown buttons too.
