### ISSUE TITLE
Dropdown menu only working in index.php

### ISSUE THREAD

**Issue by Marianour10** [wp-bootstrap/wp-bootstrap-navwalker#421]
So im using navwalker to set up my main menu, even used this video for reference: https://www.youtube.com/watch?v=bTp3Pt_RQmA

walker.php =>

`<?php

/* Collection of Walker classes */

/*
	wp_nav_menu()

	<div class="menu-container">

*/

class Walker_Nav_Primary extends Walker_Nav_menu { 
	
	function start_lvl( &$output, $depth ){ //ul
		$indent = str_repeat("\t",$depth);
		$submenu = ($depth > 0) ' sub-menu' : '';
		$output .="\n$indent<ul class=\"dropdown-menu$submenu depth_$depth\">\n";
	}
	
	function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ){ //li a span
		
		$indent = ($depth) ? str_repeat("\t",$depth) : '';
		
		$li_attributes = '':
		$class_names = $value = '';
		
		$classes = empty( $item->classes ) ? array() : (array) $item->classes;
		
		$classes[] = ($args->walker->has_children) ? 'dropdown' : '';
		$classes[] = ($item->current || $item->current_item_anchestor) ? 'active' : '';
		$classes[] = 'menu-item-' . $item->ID;
		if( $depth && $args->walker->has_children){
			$classes[] = 'dropdown-submenu';
		}
		
		$class_names = join( ' ', apply_filters('nav_menu_css_class', array_filter( $classes ), $item, $args) );
		$class_names = ' class="' .esc_attr($class_names).'" ';
		
		$id = apply_filter('nav_menu_item_id', 'menu-item-'.$item->ID, $item, $args);
		$id = strlen( $id ) ? ' id="' . esc_attr( $id ). '"' : '';
		
		$output .= $indent . '<li' . $id . $value . $class_names . $li_attributes . '>';
		
		$attributes = ! empty( $item->attr_title ) ? ' title="' .esc_attr($item->attr_title). '"' : '';
		$attributes .= ! empty( $item->target ) ? ' target="' .esc_attr($item->target). '"' : '';
		$attributes .= ! empty( $item->xfn ) ? ' rel="' .esc_attr($item->xfn). '"' : '';
		$attributes .= ! empty( $item->url ) ? ' href="' .esc_attr($item->url). '"' : '';
		
		$attributes .= ( $args->walker->has_children ) ? ' class="dropdown-toggle" data-toggle="dropdown"' : '';
		
		$item_output = $args->before;
		$item_output .= '<a' . $attributes . '>';
		$item_output .= $args->link_before . apply_filters( 'the_title', $item->title, $item->ID ) . $args->link_after;
		$item_output .= ( $depth == 0 && $args->walker->has_children ) ? '<b class="caret"></b></a>' : '</a>';
		$item_output .= $args->after;
		
		$output .= apply_filters( 'walker_nav_menu_start_el', $item_output, $item, $depth, $args );
	}
	
	function end_el(){ // closing li a span
		
	}
	
	function end_lvl(){ // closing ul
		
	}
}`

 Also required the file in Function.php =>

`require get_template_directory() . '/inc/walker.php';`

desa.bacrc.com

**Comment by pattonwebz** [comment]
This is an implementation issue with how you are adding bootstrap in your theme and not specifically an issue related to the navwalker or anything from this repo.

On the index.php page the bootstrap.min.js file is present, on the inner pages I tested it is not. Look at where you enqueue the script and see if anything may be conditionally applying around that.

**Comment by Marianour10** [comment]
Hey! Great advice man, thanks a lot.. This is how I enqueued it:

`wp_enqueue_script( 'bootstrap-script', $template_url . '/js/bootstrap.min.js', array( 'jquery' ), null, true );`

Do you see anything im not seeing? Sorry for my novice level

**Comment by pattonwebz** [comment]
We are all novices at different things, no need to apologise!

So I don't see anything in that line of code that would be causing this not to be output on pages other than the index but I do see that you have the final parameter as `true` which will load this script in the footer at `wp_footer()` hook instead of at `wp_head()` hook. 

On your test site I can see that there are indeed scripts loaded in footer on index.php but none of them are loaded on inner pages. Does your footer for inner pages use different template parts and maybe none of them contain the `wp_footer()` call?

Front the main page:
![Screenshot from 2019-04-15 20-38-59](https://user-images.githubusercontent.com/3902039/56160336-e0b69d80-5fbe-11e9-9035-28cc1c3089aa.png)
From inner pages:
![Screenshot from 2019-04-15 20-41-21](https://user-images.githubusercontent.com/3902039/56160345-e4e2bb00-5fbe-11e9-971c-04a9c1aaaf35.png)

**Comment by pattonwebz** [comment]
Also as a quick workaround for testing purposes could you set that last parameter to `false` and check if the menu then works?

**Comment by Marianour10** [comment]
Dude! You are a genius, its now working! Yes definitely im im pulling different footers in the index and in the other pages, just because in other pages than index footer was half way the screen and so I made it stick to bottom!

**Comment by pattonwebz** [comment]
Glad that I was able to help you out :)

If you swapped to using `false` in the call and it worked that does still indicate a missing call to `wp_footer()` in your theme (or that something is failing when trying to output there causing other things to fail as well) so is worth looking into that as well as the more permanent fix.
