### ISSUE TITLE
nav_menu_css_class lacks $args attribute

### ISSUE THREAD

**Issue by Boberro** [wp-bootstrap/wp-bootstrap-navwalker#424]
Steps to reproduce:
Apply nav_menu_css_class filter and try to get third argument $args from it

What happens:
Wordpress throws "missing argument 3" error.

**Comment by pattonwebz** [comment]
This seems to work in my testing. The code for that filter is in the walker here and it has all 4 expected arguments passed:

https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/d856aae8af72742bb59f9754cdccc92a3ccf473e/class-wp-bootstrap-navwalker.php#L146
