### ISSUE TITLE
Add rel="noopener" to target="_blank" links by default in bootstrap-navwalker

### ISSUE THREAD

**Issue by LukaszJaro** [wp-bootstrap/wp-bootstrap-navwalker#425]
**Suggestion**

WordPress core recently added this to the navwalker:
https://core.trac.wordpress.org/ticket/43290

Without adding these attributes google audit flags as a security risk, suggested change for class-wp-bootsrap-navwalker.php:

`//$atts['rel'] = ! empty( $item->xfn ) ? $item->xfn : '';

		if ( '_blank' === $item->target && empty( $item->xfn ) ) {
			$atts['rel'] = 'noopener noreferrer';
		} else {
			$atts['rel'] = $item->xfn;
		}`

**Comment by IanDelMar** [comment]
@pattonwebz added in #444
