### ISSUE TITLE
Mobile menu not appearing

### ISSUE THREAD

**Issue by pavanyogi** [wp-bootstrap/wp-bootstrap-navwalker#426]
#### Steps to reproduce the issue:
I included navwalker, followed all given steps. Menus are working in desktop view. But in mobile view nothing appears when i clicks on toggle button on right corner.

#### What I expected:
I expect mobile menus to be appear when i clicks on toggle button in mobile view. 

#### What happened instead:
Nothing happened, No mobile menu appeared.

**Comment by acelliott91** [comment]
Did you include the bootstrap JavaScript files in the footer of your theme? These are required for the menu to function correctly.

**Comment by pavanyogi** [comment]
working now.
