### ISSUE TITLE
Nav Bar Not working on smaller screens

### ISSUE THREAD

**Issue by briantm1998** [wp-bootstrap/wp-bootstrap-navwalker#432]
#### What happened instead:

I'm designing a website from a new theme putting it into wordpress and i'm using the wp_bootstrap_navwalker for my menus.On bigger screens its working properly but on smaller screens its not working
This is the code for the menus
`<div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <?php 
                        wp_nav_menu( array(
							'menu'              => 'top-menu',
                            'theme_location'    => 'top-menu',
                            'depth'             => 2,
                            'container'         => 'div',
                            'container_class'   => 'collapse navbar-collapse main-menu-item justify-content-end',
                            'container_id'      => 'navbarSupportedContent',
							'menu_id'           => 'bs-example-navbar-collapse-1',
                            'menu_class'        => 'navbar-nav align-items-center',
                            'fallback_cb'       => 'WP_Bootstrap_Navwalker::fallback',
                            'walker'            => new WP_Bootstrap_Navwalker(),
                             ) );
                             ?>
                    </div>

                    `

**Comment by pattonwebz** [comment]
Hey, I expect by this point you either found a solution or moved on to something else. Usually this problem happens when bootstrap JavaScript or styles are not included in the page.

I am going to close this issue now but if it is still a problem for you reopen it and someone will try help if they can.

**Comment by briantm1998** [comment]
I already found your solution with your help obviously.I thank you

*Kind Regards*

*Brian Mpofu *
*Phone: +263785688985 ,+263734198348*

*Email: briantm1998@gmail.com <briantm1998@gmail.com>,
brian.mpofu@centricdata.net <brian.mpofu@centricdata.net>*

**Comment by pattonwebz** [comment]
:smiley:
