### ISSUE TITLE
Accessibility Enhancement: bootstrap navwalker aria-current="page"

### ISSUE THREAD

**Issue by LukaszJaro** [wp-bootstrap/wp-bootstrap-navwalker#433]
WordPress added this to core in about version 5.1 I believe:

$atts['aria-current'] = $item->current ? 'page' : '';

Reference here: https://developer.wordpress.org/reference/classes/walker_nav_menu/

This allows screen-readers to know where they are, it's already working on paginate links.

Thanks.

**Comment by pattonwebz** [comment]
This was added by #434
