### ISSUE TITLE
Show carets on version 4

### ISSUE THREAD

**Issue by astbarc** [wp-bootstrap/wp-bootstrap-navwalker#435]
Hi,

I've recently updated to version 4 and I've noticed that the menus are not using 'carets' for dropdowns anymore.
Is there any way to show 'carets' on version 4?

Thanks,

**Comment by OziOcb** [comment]
Hi, 

I'm having the same issue. 
Apparently the walker isn't adding .dropdown-toggle class to the <a class="nav-link">
