### ISSUE TITLE
Navbar isn't working on mobile - Please help

### ISSUE THREAD

**Issue by dvhdesign** [wp-bootstrap/wp-bootstrap-navwalker#437]
#### Steps to reproduce the issue:

Downloaded wp-bootstrap-navwalker
and followed the instructions perfectly

#### What I expected

A dropdown menu that downsizes perfectly on mobile devices

#### What happened instead:

A great dropdown menu but the toggle menu is disabled on mobile devices

Please help I am trying to get this working on my soon to be launched website but it just works fine on desktop but doesn't display on a toggle menu

The website in its current state can be viewed at http://dvhdesign.co.uk.gridhosted.co.uk/

**Comment by pattonwebz** [comment]
Website that the link redirects to has a bootstrap nav menu with the mobile menu working so I am assuming that it has been figured out.
