### ISSUE TITLE
Exception when I try this command php artisan ui bootstrap

### ISSUE THREAD

**Issue by BouamraHiba** [wp-bootstrap/wp-bootstrap-navwalker#452]
Hello,
Actually I am new in Laravel .
I tried to run this command php artisan ui bootstrap but an exception has occured. 
Error:
local.ERROR: copy(C:\xampp\htdocs\Connect\resources\js/bootstrap.js): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): copy(C:\\xampp\\htdocs\\Connect\
esources\\js/bootstrap.js): failed to open stream: No such file or directory at C:\\xampp\\htdocs\\Connect\\vendor\\laravel\\ui\\src\\Presets\\Bootstrap.php:53)

 ErrorException  : copy(C:\xampp\htdocs\Connect\resources\js/bootstrap.js): failed to open stream: No such file or directory

  at C:\xampp\htdocs\Connect\vendor\laravel\ui\src\Presets\Bootstrap.php:53
    49|      * @return void
    50|      */
    51|     protected static function updateBootstrapping()
    52|     {
  > 53|         copy(__DIR__.'/bootstrap-stubs/bootstrap.js', resource_path('js/bootstrap.js'));
    54|     }
    55| }
    56|

  Exception trace:

  1   copy("C:\xampp\htdocs\Connect\vendor\laravel\ui\src\Presets/bootstrap-stubs/bootstrap.js", "C:\xampp\htdocs\Connect\resources\js/bootstrap.js")
      C:\xampp\htdocs\Connect\vendor\laravel\ui\src\Presets\Bootstrap.php:53

  2   Laravel\Ui\Presets\Bootstrap::updateBootstrapping()
      C:\xampp\htdocs\Connect\vendor\laravel\ui\src\Presets\Bootstrap.php:16

Please can anyone help me

**Comment by IanDelMar** [comment]
Are you sure that this is related to WP Bootstrap Navwalker?

**Comment by IanDelMar** [comment]
Based on the lack of feedback and the time that has passed since the issue has been opened, I assume that you were able to resolve this issue. If this is not the case, feel free to re-open the issue.
