### ISSUE TITLE
Is there a missing "?>" at the end of /wp_bootstrap_navwalker.php?

### ISSUE THREAD

**Issue by numeroteca** [wp-bootstrap/wp-bootstrap-navwalker#46]

**Comment by claudiosanches** [comment]
Here my friend: http://programmers.stackexchange.com/questions/89553/closing-tag-on-php-files#answer-89560

And of course here: http://www.php.net/manual/en/language.basic-syntax.phptags.php

I recommend trying to learn PHP and search in Google it before you open an issue as well.

**Comment by numeroteca** [comment]
Sorry about that!

**Comment by SideQuestDIY** [comment]
Man, @claudiosmweb you are on top of things! :)

No problem @numeroteca, it wasn't long ago that I would have asked that same question of PHP. That tells me you did actually look at the code before submitting an issue and thats great.
