### ISSUE TITLE
wp-bootstrap-navwalker

### ISSUE THREAD

**Issue by Ahlam-Shahin** [wp-bootstrap/wp-bootstrap-navwalker#463]
Problem , the dropdown didn't show ...

Bootstrap v3.3.7

**Comment by pattonwebz** [comment]
Hey @moathafa the walker in the main branch of this repo is for v4 of Bootstrap. 

For v3 there is this walker version but it has not been updated in quite a long time: https://github.com/wp-bootstrap/wp-bootstrap-navwalker/tree/v3-branch

**Comment by Ahlam-Shahin** [comment]
also it didn't work , only appear the arrows
What can I do ??
install bootstrap v4 instead of v3

**Comment by davidshq** [comment]
@moathafa - I've used the v3 branch successfully recently. You did install v3 version of navwalker and it still wasn't appearing? If so, can you paste your wp_nav_menu call in your theme?

**Comment by IanDelMar** [comment]
@Ahlam-Shahin were you able to solve the problem?

**Comment by IanDelMar** [comment]
Based on the lack of feedback and the time that has passed in the meantime, I assume that the problem has been solved. Feel free to reopen the issue if the problem persists.
