### ISSUE TITLE
Issue with IE/Edge Browser

### ISSUE THREAD

**Issue by anton-mojica** [wp-bootstrap/wp-bootstrap-navwalker#466]
![edge-issue](https://user-images.githubusercontent.com/58734999/75401196-56f49200-593c-11ea-9a67-59b72cf935dd.gif)

Does anyone encounter this kind of issue with ms edge/ie? 

Looking forward to your response.

thanks

**Comment by IanDelMar** [comment]
Just tested with Edge 88 and IE 11 and found no such issue. Apart from that, you shouldn't use the title attribute this way. According to the specs the title attribute is for *additional* information.
https://www.w3.org/TR/html52/dom.html#the-title-attribute:
> The title attribute represents advisory information for the element, such as would be appropriate for a tooltip.

Therefor the default title attribute has been removed from the WP Bootstrap Navwalker in #468.

**Comment by IanDelMar** [comment]
@anton-mojica do you still have this issue? Is it still relevant to you?

**Comment by IanDelMar** [comment]
Based on the lack of feedback and the time that has passed since the issue has been opened, I assume that you were either able to resolve this issue or it is no longer relevant to you. If this is not the case, please feel free to re-open the issue.
