### ISSUE TITLE
How to add scrollspy ?

### ISSUE THREAD

**Issue by rheamaetorres** [wp-bootstrap/wp-bootstrap-navwalker#467]

**Comment by IanDelMar** [comment]
This can not be achieved within WP Bootstrap Navwalker. To enable scrollspy check your call to `wp_nav_menu`.
```php
wp_nav_menu(
	array(
		...
		'container_id'    => 'my-container-id',
		'menu_id'         => 'my-menu-id',
		'walker'          => new WP_Bootstrap_Navwalker_Walker(),
		...
	)
);
```
Then in your header.php or wherever you open the body tag do this
```php
<body <?php body_class(); ?> data-spy="scroll" data-target="#my-container-id">
```
or
```php
<body <?php body_class(); ?> data-spy="scroll" data-target="#my-menu-id">
```
If your menu is wrapped in a nav element, you may use its ID as well.

See https://getbootstrap.com/docs/4.6/components/scrollspy/#via-data-attributes

**Comment by IanDelMar** [comment]
I consider this fixed. Please feel free to re-open the issue if the problem persists.
