### ISSUE TITLE
Navwalker menu not working in mobile version

### ISSUE THREAD

**Issue by Laure2020** [wp-bootstrap/wp-bootstrap-navwalker#471]
Here is the code for my header:

<!DOCTYPE html>
<html <?php language_attributes(); ?>>
  <head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title><?php wp_title(''); ?> </title>

    
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
        
    <script src="https://use.fontawesome.com/dc1ab33924.js"></script>
        
    <?php wp_head(); ?>
  </head>
  <body <?php body_class(); ?>>
  
  
  
<header>

   
<div class="navbar-top">
    <a href="<?php echo esc_url( home_url() ); ?>"> <img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/keymilwaukeelogo1.png" alt="KEY Milwaukee"> </a>
</div>
 
  
<nav class="navbar navbar-default">
   
<div class="container-fluid">

           <div class="navbar-header">
               <button class="navbar-toggle collapsed" type="button"  data-toggle="collapse" data-target="#main-nav">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
               </button>
             
              </div> 
 <div class="collapse navbar-collapse">
                             
           <?php
wp_nav_menu( array(
    'theme_location'  => 'primary',
    'container'       => 'div',
    'container_id'    => 'main-nav',
    'container_class' => 'collapse navbar-collapse',
    'menu_class'      => 'nav navbar-nav navbar-right',
    'wp_bootstrap_navwalker::fallback',
    'walker'           => new 
    wp_bootstrap_navwalker()
                ));
                ?>
   </div> 
 </div> 
</nav>
    
  
        
    <div class="container-fluid">
      <div class="row feature">
         <img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/MilwaukeeSkyline3.jpg" alt="Milwaukee Skyline">
         <div class="feature-text col-xs-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">
         </div>
      </div>
     </div> 
      
</header>

And my functions.php:

<?php

if ( ! isset( $content_width ) ) {
    $content_width = 660;
}

function KeyGhanawp_setup() {
      
      add_theme_support( 'automatic-feed-links' );
      add_theme_support( 'title-tag' );
    
    // Register Naviigation Walker
require_once('class-wp-bootstrap-navwalker.php');
    
register_nav_menus( array(
    'primary' => __( 'primary menu', 'KeyGhana' ),
) );

}

add_action( 'after_setup_theme', 'KeyGhanawp_setup' );

function KeyGhana_scripts() {
    /* add styles */
    wp_enqueue_style( 'bootstrap-core', get_template_directory_uri() . '/css/bootstrap.min.css' );
    wp_enqueue_style( 'custom', get_template_directory_uri() . '/style.css' );
        /* add scripts */
    wp_enqueue_script( 'bootstrap-js', get_template_directory_uri() . '/js/bootstrap.min.js', array('jqurey'), true );

    if ( is_singular() ) wp_enqueue_script( 'comment-reply' );
}
add_action( 'wp_enqueue_scripts', 'KeyGhana_scripts' );

function new_excerpt_more( $more ) {
    return '...';    
}
add_filter( 'excerpt_more', 'new_excerpt_more' );

/**
 * Register our sidebars and widgetized areas.
 *
 */
function arphabet_widgets_init() {

	register_sidebar( array(
		'name'          => 'sidebar',
		'id'            => 'sidebar_blog',
		'before_widget' => '<div class="sidebar-module">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4>',
		'after_title'   => '</h4>',
	) );

}
add_action( 'widgets_init', 'arphabet_widgets_init' );

function featureText() {
    if ( is_front_page() ) {
        _e("EVENTS, ATTRACTIONS AND WHAT'S ON IN ACCRA");
        } elseif( is_home() ) {
        _e('MUSIC AND NIGHTLIFE');
        }
    }

?>

**Comment by pattonwebz** [comment]
If you have an online demo site where someone could see how this code generates it's output that would make it easier to help diagnose this.

Most of the time when mobile nav fails to work it is caused by missing bootstrap.js, popper.js or jQuery. I see you have bootstrap.js and jQuery here as enqueues but no popper.

Also check in the console and see if there are any JS errors that could be breaking the behaviours.

**Comment by Laure2020** [comment]
Thank you for the input.
This is the demo site:
http://visitingmilwaukee.com

**Comment by pattonwebz** [comment]
I don't see the bootstrap.js file being output to your page so maybe there is something wrong with where you run the `wp_enqueue_script()` for it?

Also I notice the bootstrap css is a v3 branch. The main repo here is for bootstrap v4 - the walker for v3 can be found here but it is very outdated: https://github.com/wp-bootstrap/wp-bootstrap-navwalker/tree/v3-branch

If you are building this site/theme new then I would suggest you upgrade to boostrap v4 since the version I see on the demo page is about 5 years old :s

**Comment by Laure2020** [comment]
Ok, let me try to figure this out and upgrade to the v4 version. Thank you so much.

**Comment by liukang93** [comment]
Can someone explain this code?
		    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="true" aria-label="<?php esc_attr_e( 'Toggle navigation', 'your-theme-slug' ); ?>">
		        <span class="navbar-toggler-icon"></span>
		    </button>

**Comment by liukang93** [comment]
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="true" aria-label="<?php esc_attr_e( 'Toggle navigation', 'your-theme-slug' ); ?>">
		        <span class="navbar-toggler-icon"></span>
		    </button>

**Comment by liukang93** [comment]
what's `esc_attr_e( 'Toggle navigation', 'your-theme-slug' );` ?

**Comment by IanDelMar** [comment]
@liukang93 `esc_attr` is a WordPress function that returns escaped attributes. `esc_attr_e` is the same but it let's you translate the attribute value and echos it.

You may want to have a look at https://developer.wordpress.org/reference/functions/esc_attr/.

**Comment by IanDelMar** [comment]
@Laure2020 were you able to solve the issue?

**Comment by IanDelMar** [comment]
Based on the lack of feedback and the time that has passed since the issue has been opened, I assume that you were able to sort this out @Laure2020. If that is not the case, please feel free to re-open the issue.
