### ISSUE TITLE
Classes Don't Match Spec -- HOWTO?

### ISSUE THREAD

**Issue by dan-bailey** [wp-bootstrap/wp-bootstrap-navwalker#491]
#### Steps to reproduce the issue:
Followed instructions for installation of Nav Walker.

#### What I expected:

The code that I have in my mockups looks like this:
`<ul class="nav">
    
    <li class="nav-item">
        <a class="nav-link" href="page.html">About</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="page.html">Services</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="blogindex.html">Blog</a>
    </li>

    
    <li class="nav-item nav-dropdown">
        <a class="nav-link" href="#">Contact</a>
        <ul class="dropdown-menu">
            <li><a href="contact.html">Contact Info</a></li>
            <li><a href="contact.html">Book Appointment</a></li>
        </ul>
    </li>
</ul>`

#### What happened instead:

What's being generated is:
`<ul id="menu-main-menu" class="nav navbar-nav">
    <li id="menu-item-64" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-64"><a href="http://localhost/WP/index.php/page-2/">Page 2</a></li>
<li id="menu-item-65" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-65"><a href="http://localhost/WP/index.php/page-1/">Page 1</a></li>
<li id="menu-item-66" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-66"><a href="http://localhost/WP/index.php/the-power-of-pt/">The Power of PT</a>
    <ul class="sub-menu">
	    <li id="menu-item-67" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-67"><a href="http://localhost/WP/index.php/2020/09/02/hello-world/">Hello world!</a></li>
    </ul>
</li>
</ul>`

I was expecting to have the LI tags to have a class of "nav-item" instead of "menu-item", the A tags to have a class of "nav-link", and the submenu UL tag to have the class of "dropdown-menu"...

I suspect I'm overlooking something in the documentation here.

**Comment by IanDelMar** [comment]
> I suspect I'm overlooking something in the documentation here.

That's my guess too but it's hard to tell without further information. Can you provide the code used to register the nav menu and the code used to display the nav menu?

**Comment by dan-bailey** [comment]
Hey, thanks for jumping in on this.  You can close out my item -- I was able to dig up an example of your code in use on another theme and figure out where my issue was.
