### ISSUE TITLE
NavWalker seems to disable the custom css classes in WP Admin

### ISSUE THREAD

**Issue by htcrestive** [wp-bootstrap/wp-bootstrap-navwalker#496]

**Comment by IanDelMar** [comment]
Hi @sbuckowing , could you be more precise please? What do mean with "disable the custom css classes"? Thank you!

**Comment by htcrestive** [comment]
This message is so old that I don’t remember anymore to be honest.

**Comment by IanDelMar** [comment]
Ok. Sorry for the late response! I close the issue then. Feel free to re-open it in case the issue pops up again!
