### ISSUE TITLE
Does not process inline HTML for superscript

### ISSUE THREAD

**Issue by allenfuller** [wp-bootstrap/wp-bootstrap-navwalker#497]
Thanks for this awesome snippet! It saved my bacon, but did run into an issue where it is not processing inline HTML from the menu item's navigation label. In my case, I need to add `<sup>&reg</sup>` to display a registration mark in the menu text, however the HTML outputs as a string.

#### Steps to reproduce the issue:

1. In Wordpress Menu, add `<sup>&reg</sup>` to the navigation label of a menu item (e.g. My Brand<sup>&reg</sup>)
2. Without the navwalker, the registration symbol displays as superscript in the menu
3. With the navwalker, the registration symbol AND HTML display as a string

#### What I expected:

I expected the registration symbol to display as a superscript.

#### What happened instead:

The `<sup></sup>` HTML displayed in the menu as a string.

**Comment by thimolor** [comment]
Change this to this: 
$title = apply_filters( 'the_title', esc_html( $item->title ), $item->ID );

To this:
$title = apply_filters('the_title', $item->title, $item->ID);

**Comment by allenfuller** [comment]
That worked -- thanks!
