### ISSUE TITLE
navbar is hide when we are login

### ISSUE THREAD

**Issue by Hujjat** [wp-bootstrap/wp-bootstrap-navwalker#50]
there is wordpress admin navbar which help as navigate between public site and admin area but when we use fixed top navigation class our navbar is at the backside of wordpress nav bar how to fix that problem.

and thank's from your nice work.

**Comment by claudiosanches** [comment]
Use: http://codex.wordpress.org/Function_Reference/body_class and paste in your style.css:

``` css
.admin-bar {
    padding-top: 28px;
}
```

**Comment by Hujjat** [comment]
Hi,
thank you sir
but I could not solve the problem I have added this code to header.php 

body_class("admin-bar");

 and that style to style.css but nothing happened.

**Comment by claudiosanches** [comment]
Only

``` php
<body <?php body_class(); ?>>
```
