### ISSUE TITLE
How to change the dropdown ::marker that is being used by WP Bootstrap Navwalker?

### ISSUE THREAD

**Issue by SunnyOz** [wp-bootstrap/wp-bootstrap-navwalker#501]
I am using the 4.3 class-wp-bootstrap-navwalker.php.  (I've tried both the Aug & Oct versions)  My setup uses WordPress 5.3 and Bootstrap 4.4.  (Note: This site is still in development uses localhost atm).

The navigation menu **_without any submenu items_** defined works great.  Here is what it looks like - with my customisations to match the theme's colour scheme:

![Nav-without-submenu](https://user-images.githubusercontent.com/21353689/105281655-bf0d3000-5c00-11eb-8381-d157719a1f58.png)

[http://haregroup.com.au/source/Nav-without-submenu.png](url)

However when I **_add a submenu item_**, the menu bar doesn't look good due to the very large (and strange looking) drop-down marker (indicating that there is a submenu item available).  Here is what it looks like:

![Nav-with-submenu](https://user-images.githubusercontent.com/21353689/105281659-c16f8a00-5c00-11eb-965a-e423095580e0.png)

[http://haregroup.com.au/source/Nav-with-submenu.png](url)

### **How/where can I change/override what drop-down ::marker is used.  I would prefer a smaller font-awesome down-arrow if possible.**

If I do an inspect element on the navigation bar, this is the code that is displayed: 

(Note: below I tried the "insert code" <> icon, but it doesn't display the source code for you, instead it appears to be executing the code, which I don't think is very helpful - so I have also included a link to a file that contains just the source code for the navigation bar)

[http://haregroup.com.au/source/Nav-bar-container-code.html](url)
[Nav-bar-container-code.zip](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/files/5846932/Nav-bar-container-code.zip)

`<div class="container">
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
			<ul id="menu-menu-1" class="navbar-nav mr-auto">
				<li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-307" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5 current_page_item active menu-item-307 nav-item">
					<a title="Home" href="http://localhost/HaReGroup/HaReGroupWP/" class="nav-link" aria-current="page">Home</a>
				</li>
				<li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-312" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-312 nav-item">
					<a title="Newletters" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-312">Newletters</a>
					<ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-312" role="menu">
						<li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-775" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-775 nav-item">
							<a title="Newsletters Archive" href="http://localhost/HaReGroup/HaReGroupWP/reward-strategy-newsletters/" class="dropdown-item">Newsletters Archive</a>
						</li>
					</ul>
				</li>
				<li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-316" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-316 nav-item">
					<a title="Contact Us" href="http://localhost/HaReGroup/HaReGroupWP/contact-us/" class="nav-link">Contact Us</a>
				</li>
			</ul>
		</div>
	</div>
</div>`

And here is the class-wp-bootstrap-navwalker.php file I used:

[http://haregroup.com.au/source/fiddlefiles/class-wp-bootstrap-navwalker.php](url)
[class-wp-bootstrap-navwalker.zip](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/files/5846925/class-wp-bootstrap-navwalker.zip)

As it stands now, it looks like I won't be able to use this nav-walker version - as I need 2 levels of menu.

Thanks for any assistance or direction you can provide to help me change the drop-down marker.

Cheers,
SunnyOz

**Comment by mitchellholzmann** [comment]
Bootstrap themselves don't support multiple levels of dropdowns since it's not user friendly.

You'll have to look up the css for it, or code it yourself.

**Comment by IanDelMar** [comment]
@SunnyOz (Assuming you're still using Bootstrap 4) The caret comes from Bootstrap's CSS. See [here](https://github.com/twbs/bootstrap/blob/6ffb0b48e455430f8a5359ed689ad64c1143fac2/scss/_dropdown.scss#L9-L14) and [here](https://github.com/twbs/bootstrap/blob/v4.6.0/scss/mixins/_caret.scss). The compiled CSS should look something like this:
```css
.dropdown-toggle::after {
    display: inline-block;
    margin-left: .255em;
    vertical-align: .255em;
    content: "";
    border-top: .3em solid;
    border-right: .3em solid transparent;
    border-bottom: 0;
    border-left: .3em solid transparent;
}
```
You may overwrite this like so (FA 4.7):
```css
.dropdown-toggle::after {
    font-family: fontawesome;
    content: "\f078"; /* chevron down */
    font-size: 0.75em;
    border-top: 0;
    border-right: 0;
    border-left: 0;
}
```
Alternatively, you may directly add the FA icon to the title of the nav item and hide Bootstrap's default caret.
Your nav item title should then look like `Newsletters <i class="fa fa-chevron-down" aria-hidden="true"></i>` and you have to add the following CSS
```css
.dropdown-toggle::after {
    display: none;
}
```
Note that this hides the default caret for all (!) dropdowns and you would have to add all toggle indicators manually. Of course, you could do this item specific like so
```css
.menu-item-insert-item-id-here > .dropdown-toggle::after {
    display: none;
}
```

**Comment by IanDelMar** [comment]
@SunnyOz Were you able to solve the issue?

**Comment by IanDelMar** [comment]
@SunnyOz Based on the lack of feedback, I assume that the question has been adequately answered. If this is not the case, please feel free to re-open the issue.
