### ISSUE TITLE
Grant repo access to IanDelMar

### ISSUE THREAD

**Issue by pattonwebz** [wp-bootstrap/wp-bootstrap-navwalker#520]
Hey @bhubbard,

Could you grant contributor repo access to @IanDelMar ? He has been contributing code here and helping users with issues for a very long time (probably 3 or so years). I don't have a lot of time to maintain here right now but I would trust decisions to be made by Ian.

Thanks in advance!

**Comment by pattonwebz** [comment]
Sorry, I just noticed he has collaborator status already.

@IanDelMar feel free to handle PRs, make some code updates etc. I can be available for code review and any help or questions you may have.

**Comment by IanDelMar** [comment]
@pattonwebz thank you! I'll get back to you on that offer to review code. I have a v5 proposal almost ready for a while now and want to finish it this summer.

**Comment by pattonwebz** [comment]
A v5 version of the walker would be much appreciated by anyone new to using bootstrap. I don't think anyone is building a fresh site with BS3 (I hope!) or BS4 at this point.

Just ping me in the PR when you have something ready for me to check out. Also please feel free to start merging any current open PRs if you have an idea of any that are valuable to pull in before moving to a V5 for the walker.
