### ISSUE TITLE
Skipping data-toggle attribute and dropdown-toggle class (for mobile and tablet viewports)

### ISSUE THREAD

**Issue by afzaliwp** [wp-bootstrap/wp-bootstrap-navwalker#522]
#### What happened instead:

On line 165, 
"if ( isset( $args->has_children ) && $args->has_children && 0 === $depth && $args->depth > 1 )"
When I created a menu that has children items (depth = 1), Walker should add classes and attributes to the 'a' tag.
Classes and attributes are added but the "if" statement is returning false because of "$args->depth > 1".
$args->depth should be removed because it was always 0.

I fixed the issue this way and it's okay for my project. but maybe in another project and with a bigger $depth, my solution may not work. (I didn't try it).

Also,  $atts['data-toggle'] in bootstrap 5 should change to  $atts['data-bs-toggle'];

**Comment by IanDelMar** [comment]
@afzaliwp thanks for reaching out and reporting this issue. 

`$args->depth` is whatever the user provided when calling `wp_nav_menu()` and 0 by default. What makes you think it's always 0? I guess you did not provide the depth argument. It therefore defaults to 0. Have a look at the readme which states you should set the depth argument to 1 if you don't want dropdowns and to 2 if you do want dropdown.

```php
wp_nav_menu( array(
    'theme_location'  => 'primary',
    'depth'           => 2, // 1 = no dropdowns, 2 = with dropdowns.
    'container'       => 'div',
    'container_class' => 'collapse navbar-collapse',
    'container_id'    => 'bs-example-navbar-collapse-1',
    'menu_class'      => 'navbar-nav mr-auto',
    'fallback_cb'     => 'WP_Bootstrap_Navwalker::fallback',
    'walker'          => new WP_Bootstrap_Navwalker(),
) );
```

Please read the readme, there you'll find instructions of how to use the walker with Bootstrap 5. v5 of the walker will be fully compatible with Bootstrap 4 and Bootstrap 5.

**Comment by afzaliwp** [comment]
Thank you for your clarifications. I was using the class the wrong way!

**Comment by IanDelMar** [comment]
You're welcome!
