### ISSUE TITLE
How to keep the submenu opened when clicking thru submenu voices

### ISSUE THREAD

**Issue by fulvioromanin** [wp-bootstrap/wp-bootstrap-navwalker#54]
hi, 
first and foremost thanks for your great code.
My problem is: i open a submenu, i click on the submenu voice and then when the page is reloaded the submenu is closed again, but i'd need to keep that submenu opened . I'd need to fix this as my customer asked me for a horizontal submenu - which i achieved via css.

My menu code is this:
http://pastebin.com/DNybHXmC

(the backup query is there for other purposes...)

how can i achieve the aforementioned result?
thanks in advance for your reply :)

**Comment by fulvioromanin** [comment]
and, uhmmm, a .current class on main and submenu voices would help a lot... :)

**Comment by SideQuestDIY** [comment]
I am not really sure what you are asking here. 

If you want the submenu to stay open from page to page you will have to do some fancy scripting that is definitely outside the scope of this project as it is a very unique use case.
