### ISSUE TITLE
How can I change color of navbar

### ISSUE THREAD

**Issue by Hujjat** [wp-bootstrap/wp-bootstrap-navwalker#55]
I want to change the color of navbar how can i do that there is just two color navbar-inverse and the default one but i want to have orange color.

**Comment by SideQuestDIY** [comment]
You will have to change the navbar color by editing the .less or .css files for the menu. Bootstrap by default only comes with navbar-default & navbar-inverse.

**Comment by Hujjat** [comment]
thank's
