### ISSUE TITLE
Parent clickable and mobile expanded

### ISSUE THREAD

**Issue by mattiazer** [wp-bootstrap/wp-bootstrap-navwalker#59]
How can i make the parant clickable? now the parent has the link # and when in mobile every thing should be expanded so i can see parents children and be able to click parent in mobile?

is that possible?

**Comment by SideQuestDIY** [comment]
This is not supported with wp-bootstrap-navwalker and would require modification of the walker class. 

This class is intended to implement Bootstrap 3+ as is with me modification to the features. What you talking about is definitely possible but from a UX standpoint I would challenge you to rethink your content structure. 

There are two options I usually discuss with clients.

The first it having the sub navigation only on the parent page, and inside the page (such as a sidebar menu) content not in the main menu. If your menu is quite complex this is the best option.

The second, eliminate the parent page all together. If you have a dropdown people rarely view the parent page as it's redundant, top menu items should be general a require no explanation. Say your top level item is "Services" you user doesn't need a rundown of the fact that you offer services and then another page that describes a single service. I usually put it all on one page, or skip to the parent page as people don't want to have to drill down to find content.

**Comment by Markj89** [comment]
What about setting a media query where when it's at a certain size. It removes the #href="" only becoming a dropdown while keeping the mobile UX.
