### ISSUE TITLE
IE 8 only shows Collapsed Mode

### ISSUE THREAD

**Issue by searsandrew** [wp-bootstrap/wp-bootstrap-navwalker#66]
I'm having a strange issue in IE8 where the menu is only showing up in the collapsed mode. I can click the button, and it expands to show the menu items, and they work - but the normal menu view is not working, even when the page is expanded to full screen.
I am wondering if anybody else has had this issue.

**Comment by searsandrew** [comment]
My apologies I was going to leave a comment, and accidentally clicked close. I tried my site in IE10 and IE9, and it works as expected. But as soon as I go to IE8 or IE7, I run into the issue. I am using a child theme if that helps at all.

**Comment by n-i-m-a** [comment]
does your theme load html5shiv.js and respond.js for IE8?

---

addition as Claudio mentioned, this is an issue from Bootstrap, where it can usually be fixed by adding something like http://snipt.org/BZA1 before the closing of the head tag on your theme's header.php file.

**Comment by claudiosanches** [comment]
This is an issue of Bootstrap.
Javascript problem does not come from this code.

**Comment by searsandrew** [comment]
Adding html5shiv and respond worked. I was not aware thank you!

**Comment by SideQuestDIY** [comment]
Wow, the discussion went so quick I didn't even get to jump in! Glad to see everything resolved so quickly. :)
