### ISSUE TITLE
Bug with WP 3.8 ???

### ISSUE THREAD

**Issue by hmanprod** [wp-bootstrap/wp-bootstrap-navwalker#69]
Hi 
I've test this class with WP 3.6 and 3.7 successfully but now it's seems to have some trouble to generate correctly the menu with WP 3.8 :
- container_class and container_id is missing
- All item is empty like <ul><li><a></a></li>......

**Comment by SideQuestDIY** [comment]
I haven't yet run into this with WordPress 3.8 and I have 4 themes on 6 different sites using 3.8. 

Can you please share:
- Your `wp_nav_menu()` declaration and the code wrapping it
- The HTML that is being output
- The walker version number you are using

This will help me to diagnose what is going on with your integration specifically.
