### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#70]
does not work with wordpress 3.8 or bootstrap 3.1.0

**Comment by ghost** [comment]
updated the readme file

**Comment by SideQuestDIY** [comment]
I am yet to get around to testing the walker with Bootstrap 3.1.0, at the moment is has been tested to Wordpress 3.8.1 and Bootstrap 3.0.3.

For future reference, in order to troubleshoot what is going on with a project more information is required than "does not work with wordpress 3.8 or bootstrap 3.1.0"

**Comment by ghost** [comment]
I fixed it, did you see the update on readme file?

**Comment by cristovaov** [comment]
Hi, I just did a simple test locally for Bootstrap 3.1.0 with WP 3.8.1 and WP 3.9-alpha 
- I didn't encounter any issue on my end, everything works fine.
  I used the Testing Menu from the WP Theme Unit Test with the default example 
  from the wp-bootstrap-navwalker readme file. Added one divider and one glyphicon (star) 
- emulated the Apple iPhone 5 with Chrome Dev Tools

As for your update in the readme file I find it a bit redundant (unless Edward wants to have it matching the navbar example for the Bootstrap docs) : if your navbar `data-target` matches your nav container class or id there shouldn't be any problem with the mobile version /responsiveness of the menu.
-Cheers

**Comment by SideQuestDIY** [comment]
Thanks for this @cristovaov, I did some testing with Bootstrap 3.1.0 with WP 3.8.1 and WP 3.9-alpha last night as well, and on mobile with my Nexus 5 & Nexus 7 running Android 4.4 yielding the same results. I am currently preparing an update for the walker and an extensive update to the docs and I will take the new markup into consideration.
