### ISSUE TITLE
Add megamenu

### ISSUE THREAD

**Issue by fulvioromanin** [wp-bootstrap/wp-bootstrap-navwalker#75]
hi, it would be nice if you could add some megamenu feature to this already great walker. Imagining something into the menu description box like for glyphicons. :)

**Comment by SideQuestDIY** [comment]
@FulvioRomanin if you take a  look at the readme you will notice it already supports glyphicons

**Comment by fulvioromanin** [comment]
please, read back the issue. It's not about glyphicons, it's about megamenus like http://geedmo.github.io/yamm3/

thank you.

**Comment by SideQuestDIY** [comment]
I'm sorry the wording of the suggestion was confusing. As for a megamenu, it's not something that I am interested in implementing as: 
- It cannot be cleanly managed from the built in wordpress menu manager
- The walker is intended to implement Bootstrap as is without adding features.
