### ISSUE TITLE
CSS Classes (optional)

### ISSUE THREAD

**Issue by cvdleij** [wp-bootstrap/wp-bootstrap-navwalker#77]
Hi,

I'm losing my head over this. I'm trying to apply a class to a specific menu item in the CSS Classes (optional) box. Unfortunately I can't seem to get a response in the front-end. Think it has something to do with nav_menu_css_class... correct me if i'm wrong.

I need to set a class on an menu item for a margin-right because of my logo (It's in the middle of navigation)

Can you help me out?

**Comment by cristovaov** [comment]
have a look at @twittem 's answer here, perhaps this can set you on your way: https://github.com/twittem/wp-bootstrap-navwalker/issues/73

**Comment by cvdleij** [comment]
Tnx @cristovaov,  I was thinking of that solution. Stupid to say that if found the answer in jQuery nth-childselector. Sorry for the unnecessary issue ;)
