### ISSUE TITLE
I Can't Get dropdown to work....

### ISSUE THREAD

**Issue by sashifflett** [wp-bootstrap/wp-bootstrap-navwalker#79]
My dropdown menu for my site is not working... I have tried to look at some of the other solved issues relating to this and I can not seem to find a solution that will work for me.  I am sure I am overlooking something so small that is making big problems for me.  Any help on this issue would be really appreciated.  My site is http://bdpwp.stacyshifflett.com/.   Below is my header.php and functions.php  
![header](https://f.cloud.github.com/assets/6797568/2274861/266bf7da-9f21-11e3-8cef-943485ae75b5.jpg)

![functions](https://f.cloud.github.com/assets/6797568/2274862/2f6d33f8-9f21-11e3-845a-8f4f200c9028.jpg)

**Comment by SideQuestDIY** [comment]
That is a interesting one. Looking at the code that is output it looks like everything with the waker is working correctly form a structural perspective.

If you open dev tools and look at the code, when you click the link it is applying the `open` class to the button. This leads me to believe that the bootstrap javascript is working as well. 

By process of elimination is looks to me like the issue is your CSS is missing the class to display the dropdown or it is being overwritten. Try adding this at the bottom of your CSS.

``` css
.open>.dropdown-menu {
    display: block;
}
```

**Comment by sashifflett** [comment]
Just added it and it still doesn't want to work.

**Comment by ghost** [comment]
i'm guessing you are a newbie to web design and bootstrap, let me give you a little hint ( jQuery)

**Comment by sashifflett** [comment]
@brody182, I am a newbie and I was wondering if jQuery is the problem.  But could it be the problem if some of the items that require jQuery work fine, like the mobile nav (except for the drop-down inside of that of course).

**Comment by ghost** [comment]
if you look in the source do you see jQuery?

**Comment by ghost** [comment]
if you are using bootstrap 3.1 use this code, (not the code twittem gave you)

<?php
       wp_nav_menu( array(
           'menu'              => 'primary',
     'theme_location'    => 'primary',
       'depth'             => 2,
       'container'         => 'div',
      'container_class'   => 'collapse navbar-collapse',
    'container_id'      => 'bs-example-navbar-collapse-1',
          'menu_class'        => 'nav navbar-nav',
         'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
          'walker'            => new wp_bootstrap_navwalker())
          );
      ?>

**Comment by sashifflett** [comment]
@brody182 you are a genius!!!  Thank you so much for your help, I have been trying to get this to work for weeks!
