### ISSUE TITLE
Navbar Brand

### ISSUE THREAD

**Issue by emiluzelac** [wp-bootstrap/wp-bootstrap-navwalker#82]
This is not an issue with the walker itself.

Menu example shows:

```
<a class="navbar-brand" href="<?php echo home_url(); ?>">
    <?php bloginfo('name'); ?>
</a>
```

we needed as:

```
<a class="navbar-brand" href="<?php echo esc_url( home_url( '/' ) ); ?>">
    <?php bloginfo( 'name' ); ?>
</a>
```

Here we're sanitize the URL.

Thanks for the great walker!

Emil

**Comment by SideQuestDIY** [comment]
Thanks @emiluzelac, I will update this will a new walker commit later today.

**Comment by emiluzelac** [comment]
Thank you kind sir :)
