### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by gmoisio** [wp-bootstrap/wp-bootstrap-navwalker#85]
Hi, I modified the start_el function to take Font Awesome rather than Glyphicon. I think that a lot of people using Bootstrap include The font Awesome icons. It would be nice to add a test in the function, so that people have the choice to use the Bootstrap icons with "glyphicon-" or the Font Awesome with "fa-".
Thanks
Regards

**Comment by cristovaov** [comment]
Hello there,
This is something that is in the works for a future update>
See https://github.com/twittem/wp-bootstrap-navwalker/issues/84
-cheers

**Comment by gmoisio** [comment]
Well thank you. This class is used all around the world in a lot of templates. Could you please add on the list the fact to make "Add a menu" translatable, so that we can use po/mo?
Thanks
Regards

**Comment by SideQuestDIY** [comment]
We can definitely add that, thank you for the suggestion.

**Comment by gmoisio** [comment]
Nice, thanks
