### ISSUE TITLE
Implement plans

### ISSUE THREAD

**Issue by szepeviktor** [wp-bootstrap/wp-bootstrap-navwalker#9]
Hello @bhubbard !
I am planning to fix pending issues and implement new features (for example caching).

Could you fix codeclimate badges and make this project public?

**Comment by bhubbard** [comment]
@szepeviktor Could you provide some more details?

I believe this project is public on github, and the codeclimate badges appear to be working correctly. You can see the codeclimate details for the project at https://codeclimate.com/github/wp-bootstrap/wp-bootstrap-navwalker

**Comment by szepeviktor** [comment]
- I would go through the PR-s and issues of the original repo
- Solve all issues here
-  Implement Travis CI tests (examine the HTML output)

**Comment by szepeviktor** [comment]
> the codeclimate badges appear to be working correctly

They link to a private page.
