### ISSUE TITLE
readme wrong

### ISSUE THREAD

**Issue by Firestorm-Graphics** [wp-bootstrap/wp-bootstrap-navwalker#93]
the read me  says:
 "The most noticeable functionality change in Bootstrap 3.0.0+ is that it only supports a single dropdown level. This script is intended to implement the Bootstrap 3.0 menu structure without adding additional features, so additional dropdown levels will not be supported."

however when depth is set to 0 i can achieve unlimited amount, this is good for my purposes, just thought i'd give a heads up. otherwise a great walker class :+1:

**Comment by cristovaov** [comment]
Little hack, don't tell anyone  ;)
