### ISSUE TITLE
Filter Menu Classes

### ISSUE THREAD

**Issue by ernstoarllano** [wp-bootstrap/wp-bootstrap-navwalker#96]
Is there a way to filter out certain classes from the nav_menu_css_class? In particular I'm looking to get rid of these classes: menu-item, menu-item-type-post_type, menu-item-object-page, menu-item-#.

**Comment by SideQuestDIY** [comment]
You could potentially filter them by using WordPress's built in filters as they are part of WordPress core. 

Here is a link to the correct filter for reference:
http://codex.wordpress.org/Plugin_API/Filter_Reference/nav_menu_css_class
