### ISSUE TITLE
Cleaner walker

### ISSUE THREAD

**Issue by lopinsjk** [wp-bootstrap/wp-bootstrap-navwalker#98]
This is not an issue but a request:

it is possible to clean the output?

Walker_Nav_Menu (WordPress default) example output:

``` html
<li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8"><a href="/">Home</a></li>
<li id="menu-item-9" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-9"><a href="/sample-page/">Sample Page</a></li>
```

 My Nav Walker example output:

``` html
<li class="menu-home"><a href="/">Home</a></li>
<li class="menu-sample-page"><a href="/sample-page/">Sample Page</a></li>
```

Thank you ;)

**Comment by SideQuestDIY** [comment]
Thank you for the input but we will not be implementing this.

The standard WordPress classes are included as many use them in their designs and functionality, you can definitely modify the walker yourself if you would like to strip the output.
