### ISSUE TITLE
Menu items aligment

### ISSUE THREAD

**Issue by ghost** [wp-bootstrap/wp-bootstrap-navwalker#99]
Hi Edward, thanks for this useful plugin. But I have a problem so, I have to align right some menu items on navbar like this example: http://getbootstrap.com/examples/navbar-static-top/. How can I do it? Thanks in advance for your interest.

**Comment by cristovaov** [comment]
Hi there, please see my reply in issue #102
Same principle, but instead of the login button you add your elements.
-cheers 

UPDATE: check Edwards comment in issue #73 as well
